### ISSUE TITLE
Linux: Unable to activate license

### ISSUE THREAD

**Issue by ClementN** [spatie/ray#102]
**Describe the bug**

The license is not activated and I can't find a way to retry to add it. 

**Versions**
Ray version (you can see this in "About Ray"): 1.0.8

**To Reproduce**

When the App was launched for the first time, there was a window asking for the license. 
I pasted the license there. 

Now, at the bottom fn the main Ray window it says I am on the trial mode and on the https://spatie.be/products/ray#purchases 
it says the license has not been activated.

When I click on ```Help -> Manage License ...``` it redirects me to the Ray website.  

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS

**Comment by ClementN** [comment]
Solved: After a system reboot, the license window re-appeared and I was able to insert the license.

**Comment by Kashterion** [comment]
Hey there.

I have an issue using my license key. I recently had to delete my .config/Ray folder (Ubuntu 22.04) and now I cannot use my license key. It just keep saying the license key is not valid, tho I registered this device.

I'm using Ray 2.7.5 AppImage.

Thanks in advance for the support.
