### ISSUE TITLE
App not work in Ubuntu 20.04.

### ISSUE THREAD

**Issue by shankhadevpadam** [spatie/ray#106]
While I download ray app for Linux version using this link. https://spatie.be/products/ray/download/linux/latest it downloads a binary file which is not executed in ubuntu 20.04

**Comment by pascalchevrel** [comment]
You need to chown a+x the downloaded file (works for me in Ubuntu 20.10)

**Comment by freekmurze** [comment]
Thanks for your response @pascalchevrel
