### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by HPWebdeveloper** [spatie/ray#107]
**Describe the bug**
ParseError
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'

**Versions**
Ray version:  1.0.8 (1.0.8)

You can use `composer show` to get the version numbers of:
- spatie/ray package version:  1.5.0
- spatie/laravel-ray package version (if applicable):  1.3.4

PHP version:
Laravel version (if applicable): PHP 7.4.14

**To Reproduce**
On a fresh Laravel
COMPOSER_MEMORY_LIMIT=-1 composer require spatie/laravel-ray
[memory_limit](https://stackoverflow.com/questions/49212475/composer-require-runs-out-of-memory-php-fatal-error-allowed-memory-size-of-161)

The homepage gives this error:
ParseError
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'

**Screenshots**
![IMG](https://user-images.githubusercontent.com/16323354/104178730-98bde800-53e9-11eb-8a3d-4cc7ae69e65d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.14.6

**Comment by freekmurze** [comment]
The package does not contain a syntax error. You are not running PHP 7.4 or higher. Please upgrade your PHP version on both the web and CLI.
