### ISSUE TITLE
showQueries() and queries() does not exist when trying to show queries.

### ISSUE THREAD

**Issue by bagwaa** [spatie/ray#109]
**Describe the bug**
I have installed a fresh Laravel application, I then added some MySQL config in the env file and created a database called "ray", I then added one user, and then from within the default web.php route file added the following :- 

I also installed the composer package using `composer require spatie/ray`

```
Route::get('/', function () {
    ray()->showQueries();

    $users = User::all();

    ray()->showQueries();

    return view('welcome', [
        'users' => $users
    ]);
});
```

This causes an error when attempting to load the page : 

```
BadMethodCallException
Method showQueries does not exist.
```

**Versions**
Ray 1.0.8

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.5.0
- spatie/laravel-ray package version (if applicable): Not installed this package yet, I am however wondering if these methods are part of this package, the documentation said "install ray OR laravel ray"

PHP version:
Laravel version (if applicable): latest 8.21.0

**To Reproduce**
Add the code above to the web.php as the main route and try to dump out the queies

**Expected behavior**
To dump the queries back to ray and to not throw an exception

**Screenshots**
![Screenshot 2021-01-11 at 13 54 38](https://user-images.githubusercontent.com/825428/104190812-8e651380-5414-11eb-96be-6dc6a70c43d3.png)

**Comment by bagwaa** [comment]
Also, as a quick side note, if I run `ray('Hello world');` and remove the `ray()->showQueries()` command, it correctly dumps to the app as expected.

**Comment by riasvdv** [comment]
For queries in a Laravel app you should install `laravel-ray` using `composer require spatie/laravel-ray`. `laravel-ray` is an extension of the base `ray` package

**Comment by stefgosselin** [comment]
Hi, fyi I do not know if this was resolved, I am having the same issue in a unit test tearDown() method.

    public function tearDown(): void
    {
        parent::tearDown();
        ray()->showQueries();
        Product::destroy($this->product);
    }
    
   Returns:
   
   /usr/local/bin/php /Users/stephanegosselin/dev/autogo-api/vendor/phpunit/phpunit/phpunit --configuration /Users/stephanegosselin/dev/autogo-api/phpunit.xml --filter "/(Tests\\Unit\\Routes\\FavoritesTest::testGetFavoriteListingsAuthenticatedShouldReturnFavoriteList)( .*)?$/" --test-suffix FavoritesTest.php /Users/stephanegosselin/dev/autogo-api/tests/Unit/Routes --teamcity
Testing started at 3:15 p.m. ...
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.


BadMethodCallException : Method showQueries does not exist.
 /Users/stephanegosselin/dev/autogo-api/vendor/spatie/macroable/src/Macroable.php:66
 /Users/stephanegosselin/dev/autogo-api/tests/Unit/Routes/FavoritesTest.php:55
