### ISSUE TITLE
Windows 10 + Docker dev environment

### ISSUE THREAD

**Issue by Jackpump** [spatie/ray#112]
**Describe the bug**
When trying to open a file from the Ray app (clicking a link on list files)
It tries to open VSCode, which is correct, but the generated path to open is incorrect

The local path where I work is "F:\Projects\MyProject"
The path generated by the application is the same than in the docker machine "/opt/www/html/~~~"

**Versions**
Ray version (you can see this in "About Ray"): 1.2.0.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.5.2
- spatie/laravel-ray package version (if applicable): 1.3.4

PHP version: 7.4.13
Laravel version (if applicable): 8.21.0

**To Reproduce**
1. Go to a sandbox controller with a ray function call
2. reload the web browser to trigger that ray function call
3. go to ray app
4. click on "List files" > click SandboxController.php
5. VSCode triggers an alert that an external application wants to open a file or folder. (Here we can see the incorrect path "\\opt\www\html\app\Controllers\SandboxController.php:20")
6. Click yes
7. It doesnt open

**Expected behavior**
It should open the local file on VSCode where I am working

**Screenshots**
![image](https://user-images.githubusercontent.com/6856142/104219545-e21b3100-5403-11eb-93c7-03ce8c749ace.png)
![image](https://user-images.githubusercontent.com/6856142/104219646-00812c80-5404-11eb-926b-e8022bd75fb4.png)
![image](https://user-images.githubusercontent.com/6856142/104219523-db8cb980-5403-11eb-930e-0eb64c0bb276.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2
 
 **Additional context**

Already tested using RAY_LOCAL_PATH, RAY_REMOTE_PATH with these values: 
"F:/Projects/MyProject"
"F:/Projects/MyProject/"
"F:\Projects\MyProject" --> this doesn`t work because of escaping
"F:\\Projects\\MyProject"

**Comment by oliverhermanni** [comment]
I learned today, that RAY_REMOTE_PATH must be filled also with the path from the Docker container (see [my issue on laravel-ray](https://github.com/spatie/laravel-ray/issues/61)).

**Comment by Jackpump** [comment]
Found the solution Thx!

RAY_REMOTE_PATH='/opt/www/html/'
RAY_LOCAL_PATH='F:/Projects/MyProject/'
