### ISSUE TITLE
Add CORS to ray endpoint

### ISSUE THREAD

**Issue by m1guelpf** [spatie/ray#130]
As discussed with @freekmurze, the logger endpoint needs CORS to allow for ray() calls from the frontend.

**Comment by AdrianMrn** [comment]
@m1guelpf Do you think this is what we need? https://expressjs.com/en/resources/middleware/cors.html

Can I test it by running a fetch call to the app from within a browser?

**Comment by AdrianMrn** [comment]
Added in 1.2.5 (will release later today)
