### ISSUE TITLE
Linux: Tray icon is almost invisible (black on black)

### ISSUE THREAD

**Issue by pascalchevrel** [spatie/ray#137]
**Describe the bug**
The tray icon is a black icon, the default Ubuntu theme has a black tray bar, that makes the icon almost invisible

**Versions**
Ray version (you can see this in "About Ray"): 1.2.4

**Screenshots**
![image](https://user-images.githubusercontent.com/454375/104442925-0ad33000-5596-11eb-8ba9-c46957b09632.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version20.10
 
 **Additional context**

**Comment by AdrianMrn** [comment]
@willemvb If you can create an inverted version of the tray icon as a png, I'll make sure it gets used on Linux 👍

**Comment by willemvb** [comment]
@AdrianMrn inverted tray icons are ready to use

**Comment by AngelOD** [comment]
I'm having the same issue on Windows 10, as I use a dark background on there. If you had a background on your icon, that would be massively helpful and should work no matter the system's background colour.

**Comment by bartbrinkman** [comment]
The icon also doesn't translate too well in the running app.

![image](https://user-images.githubusercontent.com/8309358/115408880-85dd5f80-a1f1-11eb-9222-b3c93f49e9a2.png)

**Comment by leslieeilsel** [comment]
I'm having the same issue on Windows 10 Dark Theme.
![微信截图_20210507104528](https://user-images.githubusercontent.com/25165449/117391110-e4a91580-af21-11eb-8b1b-33a430215cd4.png)
