### ISSUE TITLE
Linux: almost invisible tray icon

### ISSUE THREAD

**Issue by pascalchevrel** [spatie/ray#138]
**Describe the bug**
The tray icon is a black icon, the default Ubuntu theme has a black tray bar, that makes the icon almost invisible

**Versions**
Ray version (you can see this in "About Ray"): 1.2.4

**Screenshots**
![image](https://user-images.githubusercontent.com/454375/104442925-0ad33000-5596-11eb-8ba9-c46957b09632.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version20.10
 
 **Additional context**

**Comment by AdrianMrn** [comment]
duplicate #137
