### ISSUE TITLE
Package "spatie/laravel-ray" is not installed

### ISSUE THREAD

**Issue by NeptuneDesign** [spatie/ray#14]
Hello I have a mistake that tells me that I didn't install spatie/laravel-ray when it's a good installation can you help me? Thanks (I'm on windows 10)
https://flareapp.io/share/17Dn1GXm#F12

**Comment by freekmurze** [comment]
The installation instructions of Ray are here: https://spatie.be/docs/ray/v1/getting-started/installation-in-a-framework-agnostic-php-project

**Comment by NeptuneDesign** [comment]
Désolé je me suis trompé de dépôt
