### ISSUE TITLE
ray()->measure() testing Laravel

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/ray#144]
Hi there,

Trying to use a ```ray``` ```measure``` when testing and ...

```terminal
Exception in Tests\Feature\MedicationProductsTest::tearDownAfterClass
Target class [path.storage] does not exist.
```

**Versions**
laravel/framework: 8.22.1
spatie/laravel-ray: 1.4.0
spatie/ray: 1.6.0
PHP: 7.4.13

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: BigSur
 
 **Additional context**
```php
    public static function setUpBeforeClass(): void
    {
        ray()->measure();
    }

    public static function tearDownAfterClass(): void
    {
        ray()->measure();
    }
```

**Comment by freekmurze** [comment]
I don't think we can solve this. You can't use anything Laravel specific in `setUpBeforeClass` as the framework has not booted yet.
