### ISSUE TITLE
OutOfBoundsException: Package "spatie/laravel-ray" is not installed

### ISSUE THREAD

**Issue by nexxai** [spatie/ray#151]
**Describe the bug**
When executing tests in a Laravel 8.x project, I'm getting `OutOfBoundsException: Package "spatie/laravel-ray" is not installed` error.  I am just using the normal Laravel testbench, which I think includes orchestra(?) so as the documentation suggests, I *think* I've added this to the correct BaseTestCase (/tests/TestCase.php):

```php
// add this to your base test case

protected function getPackageProviders($app)
{
    return [
        \Spatie\LaravelRay\RayServiceProvider::class,
    ];
}
```

**Versions**
Ray version (you can see this in "About Ray"): n/a; happening in the Gitlab runner where my tests are being run

You can use `composer show` to get the version numbers of:
- spatie/ray package version: `spatie/ray                         1.7.2              Debug with Ray to fix problems faster`
- spatie/laravel-ray package version (if applicable): `spatie/laravel-ray                 1.5.2              Easily debug Laravel apps`

PHP version: `PHP 7.4.12 (cli) (built: Nov  5 2020 20:09:22) ( NTS )`
Laravel version (if applicable): `Laravel Framework 8.22.1`

**To Reproduce**
1. Run tests

**Expected behavior**
The tests not to fail

**Screenshots**
```
1) Tests\Feature\ExampleTest::this_is_an_example_test
OutOfBoundsException: Package "spatie/laravel-ray" is not installed
/builds/nexxai/myproject/vendor/spatie/laravel-ray/src/Ray.php:170
/builds/nexxai/myproject/vendor/spatie/laravel-ray/src/RayServiceProvider.php:110
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:391
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:236
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Log/Logger.php:210
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Log/Logger.php:176
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Log/Logger.php:87
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:551
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:238
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:404
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:112
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:508
/builds/nexxai/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:320
/builds/nexxai/myproject/tests/Feature/ExampleTest.php:55
```

**Desktop (please complete the following information):**
 - OS: PHP 7.4 official docker image
 - Version [e.g. 22] n/a
 
 **Additional context**

**Comment by freekmurze** [comment]
I cannot reproduce this. Can you share an example app where I could easily trigger this error?

**Comment by freekmurze** [comment]
Thanks!

**Comment by nexxai** [comment]
@freekmurze Can I temporarily invite you to a private repo here so you can see the actual code?

**Comment by freekmurze** [comment]
I'd rather not. I don't have time to debug actual projects. Please create a minimal example for me to look at.

**Comment by freekmurze** [comment]
Maybe it's just a case of your test not hitting the `getPackageProviders` method. Could you put a `die('I am here')`, to see if it is actually called?

If not, create that minimal example for me to look at, and open a new issue.

**Comment by ricardoaugusto** [comment]
I was having this issue a couple minutes ago and my steps to fix were:

- Composer on local machine was `v2.0.8` and remote was still `v1.9.x`, so **`composer self-update --2`** on remote, then;
- added `Spatie\LaravelRay\RayServiceProvider::class,` to Laravel config/app.php file _(which probably didn't make any difference, but still)_, and finally;
- ran **`composer dump-autoload`**
