### ISSUE TITLE
[Linux] Link to IDE line doesn't work

### ISSUE THREAD

**Issue by yoyosan** [spatie/ray#158]
Ray version: 1.11.0
OS: Manjaro KDE 5.77
IDE: PHPStorm 2020.3.1

Whenever I'm clicking on the link below the message(with class name and line number), I'm getting this error.

![image](https://user-images.githubusercontent.com/32405/104594345-b1dcc800-5679-11eb-9460-98c8f7de02a1.png)

I've used this project https://github.com/sanduhrs/phpstorm-url-handler to install the phpstorm-handler.

**Comment by bintzandt** [comment]
I'm getting the same problem here. My guess is that `phpstorm-url-handler`/PHPStorm does not handle the URL encode (`%2F`) correctly.

**Comment by henzeb** [comment]
Not the only one I guess, currently on version 1.5.1

**Comment by yoyosan** [comment]
Still happens in 1.6.0

**Comment by yoyosan** [comment]
> I'm getting the same problem here. My guess is that `phpstorm-url-handler`/PHPStorm does not handle the URL encode (`%2F`) correctly.

Mmm, I don't see anything wrong in there.

**Comment by yoyosan** [comment]
It still doesn't work.

Can you please specify what values are sent to PHPStorm handler?
So that I can debug it myself.

**Comment by vicenterusso** [comment]
Similar problem here. Using ubuntu, clicking does nothing, not even the the error popup. Mouse over points to the correct local path though

**Comment by bintzandt** [comment]
Have you tried installing https://github.com/sanduhrs/phpstorm-url-handler to handle the PHPStorm URL?

**Comment by yoyosan** [comment]
> 
> 
> Have you tried installing https://github.com/sanduhrs/phpstorm-url-handler to handle the PHPStorm URL?

That's what I'm using.

**Comment by vicenterusso** [comment]
> Have you tried installing https://github.com/sanduhrs/phpstorm-url-handler to handle the PHPStorm URL?

Just installed. Not working. local path on mouse over is correct, but now I have the error popup. As @yoyosan pointed, local path is not being parsed correctly

**Comment by UnSeulT** [comment]
Same here, ray v1.14.7, not launching Sublime on Linux Mint 19.3 despite the local path on mouse over is correct.
And no error popup.

**Comment by lloricode** [comment]
Same here ray v1.15.0

**Comment by lloricode** [comment]
> I'm getting the same problem here. My guess is that `phpstorm-url-handler`/PHPStorm does not handle the URL encode (`%2F`) correctly.

i tested this with command line, it is working fine as expected

**Comment by lloricode** [comment]
HI i fixed the urldecode

you can clone my PR https://github.com/sanduhrs/phpstorm-url-handler/pull/16

then run this on your local 

```bash
sudo cp phpstorm-url-handler /usr/bin/phpstorm-url-handler && sudo desktop-file-install phpstorm-url-handler.desktop && sudo update-desktop-database
```

**Comment by freekmurze** [comment]
Closing here, as the problem lies with the `php-url-handler`
