### ISSUE TITLE
[VSCode] Click on File:LineNumber opens file in new window instead of the opened project's one

### ISSUE THREAD

**Issue by bzrncev** [spatie/ray#16]
Is this a feature or a bug? :)

**Comment by freekmurze** [comment]
I guess a bug 🙂 Can you test this and fix it @AdrianMrn

**Comment by jasonvarga** [comment]
Same thing happens in Ignition. I'm guessing it's a limitation of `vscode://` links though. If you can work it out, that would be doubly cool!

**Comment by AdrianMrn** [comment]
I sometimes had a similar issue while developing, I'll see if I can reproduce this one!

**Comment by AdrianMrn** [comment]
It looks like this was implemented in vscode in this PR https://github.com/microsoft/vscode/pull/15320, and they encountered the same issue (https://github.com/microsoft/vscode/pull/15320#pullrequestreview-8158394). It seems like they should have fixed this, so I'm not sure what is still going wrong… If anyone else cares to take a look, feel free!
