### ISSUE TITLE
After installation Ray seems not working

### ISSUE THREAD

**Issue by davide-casiraghi** [spatie/ray#166]
**Describe the bug**
I have installed Ray and when I try to run in a controller I'm debugging anything related with Ray nothing happens.

```
ray('test'):  //nothing happens  

ray($myvariable); //nothing happens  

dd($myvariable); //I get the dump of the variable    
```

**Versions**
1.3.0 

You can use `composer show` to get the version numbers of:
- spatie/ray package version:  1.5.2 
- spatie/laravel-ray package version (if applicable):   1.7.2  

PHP version:
Laravel version (if applicable): 7.4

**Desktop (please complete the following information):**
 - OS:  macOS Catalina
 - Version 10.15.2

**Comment by freekmurze** [comment]
Could you create a minimal app for me to look at where in Ray is not working?

**Comment by freekmurze** [comment]
Maybe you app is in production mode? Try manually enabling it by calling `ray()->enable()`

**Comment by freekmurze** [comment]
If it doesn't work after these tips, reopen a new issue at spatie/laravel-ray with a link to that minimal app.

**Comment by davide-casiraghi** [comment]
I tried with `ray()->enable()` and checking if by change I was in production mode but in my .env file I have `APP_ENV=local`.
When I have a bit of time I will create the minimal app and share the link.

**Comment by freekmurze** [comment]
If you're using homestead / docker, do check our docs for a few additional tips

**Comment by davide-casiraghi** [comment]
Yes I'm using Homestead!
after doing: `php artisan ray:publish-config --homestead`
now is working!!

Sorry I missed that line in the documentation.  

Thank you! <3
