### ISSUE TITLE
[Sail] RAY_LOCAL_PATH not used unless RAY_REMOTE_PATH is set

### ISSUE THREAD

**Issue by tcov189** [spatie/ray#177]
**Describe the bug**
When using Laravel Sail, setting `RAY_LOCAL_PATH` in `.env` doesn't get used for the file path in Ray unless `RAY_REMOTE_PATH` is also set.

**Versions**
Ray version (you can see this in "About Ray"):
1.5.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.11.0
- spatie/laravel-ray package version (if applicable):  1.6.1

PHP version: 7.4.3
Laravel version (if applicable): 8.21.0

**To Reproduce**
1. Set `RAY_LOCAL_PATH` to local path
2. Run `./vendor/bin/sail -d`
2. Run `sail artisan config:clear` // Not sure if this is needed, just habit
3. Send event to Ray
4. Path to file will have `/var/www/html/` instead of `RAY_LOCAL_PATH`
5. Add `RAY_REMOTE_PATH="/var/www/html"
6. Run `sail artisan config:clear` // Again not sure if needed
7. Send event to Ray
8. Path to file will have `RAY_LOCAL_PATH`

**Expected behavior**
I would expect that the file path that I set in `RAY_LOCAL_PATH` would be used in the file path.

**Screenshots**
![image](https://user-images.githubusercontent.com/8125119/104768922-0e042280-5734-11eb-931e-154ea6a99b11.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 
 - Version 20.04

**Comment by freekmurze** [comment]
Hi, the local and remote paths are being used in the code here: https://github.com/spatie/ray/blob/3a63651ce404c4d9ae50afb02ff7e1fcdf673643/src/Payloads/Payload.php#L19-L23

Code you take a look if these variables hold the values you are expecting? We use these values to do a simple string replace.

I hope you'll be able to figure out the issue with this info.

**Comment by tcov189** [comment]
@freekmurze Thank you for your response. I will take a look and see if I can work on the issue.

**Comment by gertvdv** [comment]
Hi, having a similar issue on Ubuntu 20.04. For troubleshooting this problem, I have set both local and remote path in my .env to the path where the files are located on my local machine (where the IDE is running). However, all traces are incorrectly linked to /var/www/html/

**Comment by freekmurze** [comment]
@gertvdv could you also take a look at which values there are in the code snippet above? https://github.com/spatie/ray/issues/177#issuecomment-761800975

**Comment by tcov189** [comment]
@freekmurze This is what I get 
![image](https://user-images.githubusercontent.com/8125119/104954002-1dca7380-598d-11eb-8ff0-a305e0b7bd03.png)

Since `$this->remotePath` is null, the if expression is truthy and it returns the `$filePath`.

In @gertvdv case, neither `$this->remotePath` and `$this->localPath` are null, but when the code makes it to the `str_replace` the `$filePath` doesn't contain the string that's in `$this->remotePath` or `$this->localPath` so the original `$filePath` is returned. 

I can make a PR but first I would need to know what the expected behavior should be. In my opinion, if I pass `RAY_LOCAL_PATH` then that should be the path used in the trace, regardless of what's in `RAY_REMOTE_PATH`. I am also not sure if either of those variables are used anywhere else though.

**Comment by freekmurze** [comment]
I'm thinking that in this case `local_path` should be set to `/home/trevorc` and `remote_path` to `/var/www/html`

This why the path will be translated to `/home/trevorc/ray-test/routes/web.php` which is probably the path you need, right?

**Comment by tcov189** [comment]
Yes that makes sense to me. 

I can make a PR to handle instances where `local_path` is set and `remote_path` is not.

**Comment by freekmurze** [comment]
I don't see now how that will work, but feel free to convince me with code 🙂 

Closing this as the original issue is solved.

**Comment by tcov189** [comment]
Just to clarify, are you saying that the original issue is solved by having both `remotePath` and `localPath` set in order for `localPath` to be used in traces?

**Comment by freekmurze** [comment]
Yeah, to me it seems that you always need to to have `local_path` and `remote_path` filled out, in order for that str_replace to work.

**Comment by tcov189** [comment]
Gotcha. I will see if I can make it work in a PR and send it your way. 

If not then this works for me. Thank you for your time
