### ISSUE TITLE
Ray does not display the location of debugging statements.

### ISSUE THREAD

**Issue by Polfo** [spatie/ray#18]
In my case, when using 
`ray($variable1, $variable2)` 
the location of that statement is not displayed, 
`...\vendor\spatie\ray\src\helpers.php:16` 
is displayed instead.

![image](https://user-images.githubusercontent.com/10303392/103948471-1bb91700-513a-11eb-8a51-257410366d22.png)

**Comment by Polfo** [comment]
I saw the correct location in the ray app on some occasions,  but cannot reproduce it because of expired trial license.

**Comment by freekmurze** [comment]
Please open up a new issue when you are able to reproduce this 👍

**Comment by Polfo** [comment]
I use other versions now and can't reproduce it any more.
