### ISSUE TITLE
Windows: "Help > Report a bug" doesn't work

### ISSUE THREAD

**Issue by slaFFik** [spatie/ray#180]
**Describe the bug**
When I try to report a bug using "Help > Report a bug..." menu item it switches to my default browser but it doesn't open any URLs. It just makes the Chrome active - and that's it.

**Versions**
Ray version: 1.5.0.0

**To Reproduce**
1. Go to the Ray app
2. Click on Help > Report a bug
3. See your browser going in focus - 
4. No tab is opened

**Expected behavior**
A new tab should be opened with a page where I can report a Ray app bug.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2

**Comment by freekmurze** [comment]
This will be fixed in the upcoming v1.5.1 of Ray.
