### ISSUE TITLE
Not choosing any Pause selection will autoskip pause() on subsequent requests in new window

### ISSUE THREAD

**Issue by gm-lunatix** [spatie/ray#187]
**Describe the bug**
When you use pause() and you do not select any option to continue or stop the execution and you open a new window and send a new request to your app, the pause() is skipped in the new window and the rest of the code automatically executes. If I go back the the older window and click on any of the pause option button, do the same in any window with an outstanding pause option displayed, the pause() is respected again in the next request.

**Versions**
Ray version: 1.5.0.0
- spatie/ray package version: 1.8.0
- spatie/laravel-ray package version (if applicable): 1.7.1

PHP version: 7.4.13

**To Reproduce**
1. Use ray()->pause();
2. Do not click on either Continue nor Stop Execution
3. Clear the Ray window with the hotkey / open a new Ray window ([+])
3. Send another request to your app
4. See screenshot how the pause is auto skipped

**Expected behavior**
A. automatically close any other outstanding pause by force when a new Ray window is opened, and respect the pause() request
B. Respect the pause() request in any new window regardless the state of any previous pause() request in any other Ray window

**Screenshots**
See how ray executes the rest of the code without requiring the user to select any pause() triggered option:
![image](https://user-images.githubusercontent.com/73477545/104849916-5e0cf180-58ba-11eb-977f-ecc1fbe8c7f5.png)

**Desktop (please complete the following information):**
 - OS: windows10
 - Version 2004

**Comment by freekmurze** [comment]
I cannot seem to reproduce this...


I've got a demo app with this route set up:
https://github.com/spatie/laravel-ray-demo-app/blob/428272bbd2b5c32fb7360a257491d7f11257fbe4/routes/web.php#L12-L16

When I open /pause in two tabs, the process is halted for both those processes. I see both pauses in Ray. Each one can be continued individually by pressing the continue button. TLDR: it seems to work like expected.

Can you try out that demo and let me know if it works for you? Can you create a minimal demo that fails for you for me to test?

**Comment by freekmurze** [comment]
Closing as this one cannot be reproduce. If this is still failing for you, please create a minimal app to easily reproduce the issue you are seeing.
