### ISSUE TITLE
Ray crash after clicking in a Mail Notification

### ISSUE THREAD

**Issue by leganz** [spatie/ray#188]
If you create a mail notification and print it via:

```
ray()->markdown($message->render());
```

After clicking on a link in this mail => the app crashes.

**Comment by leganz** [comment]
<img width="856" alt="Bildschirmfoto 2021-01-17 um 21 47 52" src="https://user-images.githubusercontent.com/3373530/104855571-d05af180-590d-11eb-8e79-881dceda9b45.png">

**Comment by freekmurze** [comment]
I cannot seem to reproduce this. I've have a demo app here where `markdown` is used.

https://github.com/spatie/laravel-ray-demo-app/blob/30e4b126118ab2943a3e07e1eedea05c64d63cbe/app/Console/Commands/MarkdownCommand.php#L18

It displays a link in Ray. When I click it, the browsers opens and shows the right page.

Could you try out if that works for you? Could you create a demo for me which can be used to quickly reproduce the issue?

**Comment by leganz** [comment]
Here is the repository to reproduce the issue:
https://github.com/leganz/bug-repo-ray-188

By clicking on the action link ray (1.6.0 - got the update about ~10 minutes ago) the app crashes. Hope that helps :-) 
Let me know if i can help somehow.

(Btw: i know that might not be the ideal solution - i was just trying how to render the notification in ray :-) )

**Comment by freekmurze** [comment]
Thanks for creating the repo. How can I trigger that notification? Is there an artisan command to do that?

**Comment by leganz** [comment]
php artisan test 
Sry forgot to mention that

**Comment by freekmurze** [comment]
I can reproduce the error. Thanks for the repo.

Investigating on how we can fix this.

**Comment by freekmurze** [comment]
@AdrianMrn could you take a look at this? Seems like a link to `http://localhost` lets Ray crash.

**Comment by AdrianMrn** [comment]
A fix for this will be included in the next release (likely 1.14.1)
