### ISSUE TITLE
Ray not receiving calls | Laravel Sail

### ISSUE THREAD

**Issue by williamengbjerg** [spatie/ray#189]
I'm using docker with laraval sail on my Mac Mini (M1) with **docker preview**. Nothing is happning when I run my commands or try to output something with `ray("msg")`

I also tried to change host: `'host' => env('RAY_HOST', 'host.docker.internal'),` (Same issue)

Anyone with similar issues? i just bought the app (Version 1.5.0 (1.5.0))

![Screenshot at Jan 17 21-47-20](https://user-images.githubusercontent.com/54719/104855522-9c7fcc00-590d-11eb-90db-f52804141eb3.png)

**Comment by freekmurze** [comment]
Ray listens for messages on port 23517. You should create a map port 23517 on docker to send all traffics to the same port on your local environment.

Unfortunately, I don't have much Docker experience myself, so I hope you can figure out the exact command to achieve this.

**Comment by williamengbjerg** [comment]
Looks like it works after the new 1.6 version :)

**Comment by freekmurze** [comment]
Nice!
