### ISSUE TITLE
Ray asking restart every day even without an Update

### ISSUE THREAD

**Issue by keshansandeepa** [spatie/ray#192]
**Describe the bug**
Ray asking restart every day even without an Update

**Versions**
Ray version (1.5.1):

PHP version:7.4
Laravel version 7:

**Comment by AdrianMrn** [comment]
@keshansandeepa Could you recreate the issue [using the template](https://github.com/spatie/ray/issues/new?assignees=&labels=&template=bug_report.md&title=) please, that'll give us all the information to reproduce the issue and will make it a lot easier on us to find the cause and fix it.
