### ISSUE TITLE
No feedback from (Laravel) Ray

### ISSUE THREAD

**Issue by Dixens** [spatie/ray#194]
Hey guys

Bought Ray a couple of days ago and can't seem to make it work. Been using Spatie packages for ages, never had an issue so surely it's us.

**Config**
Mac Catalina 10.15.7
Laravel 7.30.3
Ray: Version 1.5.0 (1.5.0)
Composer 2
spatie/ray ^1.7.2
spatie/laravel-ray * 1.6.1
MAMP 6.3
PHP 7.4.12
Config ray.php as is

**Issue**

In any file, the following line

```php
ray('My first ray call')
```

does not trigger anything in Ray (same "Welcome to Ray!..." message).

As the local URL is something like https://myapp:8890/, we tried to adapt config file but to no avail.

Any idea?

Thank you.

**Comment by freekmurze** [comment]
Are you using Homestead / Docker? Then take a look in [our docs](https://spatie.be/docs/ray).

Ray just listens for messages on port 23517. The laravel-ray package sends message to that port. 
Make sure that your Laravel app is not in production mode.
You could try to call `ray()->enable()` and see if that works.

**Comment by Dixens** [comment]
Thank you for your quick reply.

We use MAMP (see above).

Our app is in APP_ENV=local.

Inserting then removing

```php
ray()->enable()
```

did the trick though.

Thank you.
