### ISSUE TITLE
Ctrl + Shift + K overrides the same PHPStorm binding even if Ray is not on top

### ISSUE THREAD

**Issue by basepack** [spatie/ray#201]
**Describe the bug**
When a ray.exe process is active the PHPStorm `Ctrl + Shift + K` default binding for `Git Push` does not work anymore. So even when I close Ray it keeps ray.exe's active, so the binding won't work again before I kill all Ray.exe processes.

**Versions**
Ray 1.6.0
spatie/ray 1.12
spatie/laravel-ray 1.7.1
Windows 10 Pro
PHPStorm 2020.2

PHP version: 7.4
Laravel version 8.22.1

**To Reproduce**
1. Start PHPStorm on Windows
2. Hit Ctrl + Shift + K
3. See the Git Push window appear
4. Now start Ray 
5. Hit Ctrl + Shift + K
6. Now you do not see the Git Push window appear

**Expected behavior**

**Comment by AdrianMrn** [comment]
The hotkeys are global and are supposed to work even when the window is not in focus, I guess the last one that was registered takes priority over others.

You should reassign the hotkey in the preferences to another key: 

![image](https://user-images.githubusercontent.com/12762044/105009052-507e7580-5a3a-11eb-9bb9-85891a3e1586.png)
