### ISSUE TITLE
[Docker] Ray tries to open the wrong file

### ISSUE THREAD

**Issue by bintzandt** [spatie/ray#202]
**Describe the bug**
Ray refers to the wrong file when clicking on the file name.

It uses the file path from the Docker container. I suspect that a mapping is needed from Docker container filesystem to the local filesystem since most people are running their editor on the local file system.

**Versions**
Ray version: 1.6.0

PHP version: 8.0
Laravel version (if applicable): 8.21.0

**To Reproduce**
1. Add a `ray()` statement to a file
2. Execute the code. Make sure that it shows up in Ray
3. Click on the `filename:line_number` link
4. See that it refers to a file path in the Docker container

**Expected behavior**
1. Add a `ray()` statement to a file
2. Execute the code. Make sure that it shows up in Ray
3. Click on the `filename:line_number` link
4. See that it refers to a file path on the local machine

**Screenshots**
![image](https://user-images.githubusercontent.com/8782235/105009486-d1d60800-5a3a-11eb-86eb-7982be41d5bc.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 
 **Additional context**
I'm using the `php:8.0-fpm-alpine` Docker image.

**Comment by freekmurze** [comment]
You'll need to use the `local_path` and `remote_path` options of the config file. Check the docs to know more.

**Comment by bintzandt** [comment]
Oof, I'm sorry! Totally missed that part :(

Might be worth to write a small section about that on https://spatie.be/docs/ray/v1/environment-specific-configuration/docker though. I see it mentioned in the configuration but it is easy to skip over that imo.

**Comment by freekmurze** [comment]
Np!

Feel free to PR improvements, there's an edit button on the top of every page.
