### ISSUE TITLE
Ray processes won't stop when using something else than "Menu > Quit Ray"

### ISSUE THREAD

**Issue by kbondurant** [spatie/ray#203]
**Describe the bug**
If i close the app using the close button in the top right of the window or by pressing ALT+F4,
the app window closes but the processes are still running, but if i use Menu > Quit Ray,
everything seems to work correctly all processes are killed.

**Versions**
Ray version (you can see this in "About Ray"): 1.6.0

**To Reproduce**
1. Go to Ray app
2. Click on the close window button or press ALT+F4
3. Look at your process monitor
4. See Ray proccesses are still running

**Desktop (please complete the following information):**
 - OS: Linux Mint (Ubuntu)
 - Version [e.g. 22]: 20.1

**Comment by AdrianMrn** [comment]
This is expected behaviour, this is something that a lot of apps do nowadays (Slack, Steam, Discord, WhatsApp to name a few).

**Comment by kbondurant** [comment]
Not exactly, those apps processes are still running only if it's still running in system tray,
so the user always have an indication that the software is running in backgroud and can reopen them using tray icon,
if you disable this option all of their processes are killed whatever way you choose to close the app.

Atm Ray processes are still running with no visible indication that the software is running (when the show app option is on task bar only which is the default option), and when i reopen the software i have a double window for a short time, it looks like one of the duplicate process is killed at this moment.

And i just noticed another small bug, if i change de "Show app" option from "Tray" to "Task bar", the Ray icon stays in tray but no action can be performed on it anymore (i can't reopen the app window with it anymore), and this lasts until i close the app using "Menu > Quit Ray".

**Comment by AdrianMrn** [comment]
Thanks for your feedback!

>Atm Ray processes are still running with no visible indication that the software is running

In a future version, we're changing the visibility options so the app cannot be hidden from the Tray as log as it is running.

>And i just noticed another small bug, if i change de "Show app" option from "Tray" to "Task bar", the Ray icon stays in tray but no action can be performed on it anymore (i can't reopen the app window with it anymore), and this lasts until i close the app using "Menu > Quit Ray".

I'll have a look at this.
