### ISSUE TITLE
Logging false reports as null

### ISSUE THREAD

**Issue by SteveEdson** [spatie/ray#208]
**Describe the bug**

```php
ray('null', null);
ray('false', false);
ray('true', true);
```

Shows `null` in the output (although styled differently to an actually null value).

**Versions**
Ray version (you can see this in "About Ray"):
1.6.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.3.5
- spatie/laravel-ray package version (if applicable): 

PHP version:
Laravel version (if applicable):
7.4.16

**To Reproduce**
```php
ray('null', null);
ray('false', false);
ray('true', true);
```

**Expected behavior**
`false` should be visible in the logs.

**Screenshots**
<img width="512" alt="Screenshot 2021-01-19 at 14 55 19" src="https://user-images.githubusercontent.com/1201960/105051325-8df8f800-5a66-11eb-8b16-6cd708cd7b75.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 22] BigSur
 
 **Additional context**

**Comment by freekmurze** [comment]
This will be fixed in the next release of Ray, which will be released soon!

<img width="802" alt="image" src="https://user-images.githubusercontent.com/483853/105060330-8d695d00-5a78-11eb-9864-eea26ebf2c87.png">

**Comment by SteveEdson** [comment]
Excellent thanks! I spent ages trying to figure out why my code wasn't working until I realised it was ray reporting incorrectly! 😂

**Comment by freekmurze** [comment]
Sorry about that 😅

**Comment by SteveEdson** [comment]
No worries, I expect ray will more than make up for it in future debugging scenarios 👍
