### ISSUE TITLE
Zoom In / Zoom out shortcuts

### ISSUE THREAD

**Issue by TheBurgerShot** [spatie/ray#212]
Not really a bug more a convenience thing. 

With the 'Zoom In' shortcut being '⌘+' and the 'Zoom Out' shortcut being '⌘-' it requires to use (⌘ + Shift + '+') for zooming in and ('⌘ + '-') for zooming out.

**Version**
Ray version: 1.6.0

**Expected behavior**
It would be nice, in my opinion, to be able to just Zoom In with just ('⌘ + '+')

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by freekmurze** [comment]
Hi, thanks for suggestion this. We're following OS default and we'll probably leave it as it is for now.
