### ISSUE TITLE
Collapsing doesn't work

### ISSUE THREAD

**Issue by emohamed** [spatie/ray#219]
Bug Report is here: 
https://github.com/spatie/ray/discussions/218

> When I click on the collapse triangle, it doesn't actually collapse the branch of the object / array:
>
> https://user-images.githubusercontent.com/536840/105142768-a5d28980-5b03-11eb-8d4f-55f406b49adf.mp4

**Versions**
Ray Version: Version 1.7.0 (1.7.0)
composer - spatie/laravel-ray                   1.8.0
composer - spatie/ray                           1.13.0
PHP 7.4.8
MacOS 10.15.7

**Comment by freekmurze** [comment]
I've tried to reproduce this, but for me this is working. 

I've executed `ray(app())` and the triangles work to open, close stuff

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/483853/105145181-a583bf80-5afe-11eb-9799-e9c491c9151c.png">

@emohamed is there any extra info you can give us to reproduce this?

@AdrianMrn do you have an idea why this might not be working for @emohamed ?

**Comment by emohamed** [comment]
Thanks for looking into this. I will try a few things later today and get back to you with any additional information I have.

**Comment by emohamed** [comment]
Tried restarting the whole OS, and to install ray 1.6. The issue persist. 

Here is a more detailed video:
https://user-images.githubusercontent.com/536840/105160167-93167f80-5b18-11eb-8c4e-09a17a9ec56f.mp4

It seems to me that anchors are working, but not javascript. 

@freekmurze is there way for me to see the console in the electron browser? 

Also, Cmd+F doesn't give me search prompt, not sure if this is supposed to be included as a feature.

**Comment by RyanNutt** [comment]
I'm seeing something similar with arrays.
![image](https://user-images.githubusercontent.com/7416974/105375153-16de7380-5bce-11eb-96c3-2fc8f430fa0c.png)

The dropdown arrow works, but there are 3 of them. 

But if the same array is a property on a model that I send to ray with `ray()->model($theModel)` I can't expand the array.
![image](https://user-images.githubusercontent.com/7416974/105375316-3c6b7d00-5bce-11eb-82a3-c0e67b3d5798.png)
And it has 2 arrows. 

Ray: 1.7.0
Windows 10

**Comment by freekmurze** [comment]
@RyanNutt I have seen this once too but couldn't reproduce it. Do you get this behaviour every time? Which version of the Ray packages too you use?

**Comment by RyanNutt** [comment]
Looks like it happens on subsequent output. I just put several `ray(request()->all())` calls on consecutive lines. The last one sent to ray correctly and I can toggle the visibility of the outer and any inner arrays.

I sent a total of 4 calls. The first has 4 arrows, the second has 3 arrows, the third has 2 arrows, and the fourth and last has 1 arrow. Only the one with 1 arrow will toggle the dropdown.

I had the option set for new output to go to the top of the window. Just tried switching it back to bottom and there are only single arrows and they appear to toggle correctly. 

Ray version 1.7.0
laravel-ray version 1.8

**Comment by freekmurze** [comment]
@RyanNutt I feel that your issue is another one, then the original reporter. Would you mind creating a new issue, and filling in the entire issue template? Thanks!

**Comment by RyanNutt** [comment]
Of course #233

**Comment by adevade** [comment]
I posted about this issue in the `wordpress-ray` repo a couple of days ago, and now I saw this issue so I closed mine in the other repo. It is however the exact same error as OP in this thread. The arrows doesn't work at all for me.

I'm now on app version 1.10.1.0 and WordPress plugin version 1.2.2, still the same problem.
Let me know if you need any more info.

Original issue from `wordpress-ray` repo ([link](https://github.com/spatie/wordpress-ray/issues/30)):

-----

<img alt="2021-01-21_16-46-40" src="https://user-images.githubusercontent.com/1066486/105374697-44481300-5c08-11eb-9f2f-a4af785b6372.png">

I'm sure that this is not a problem with `wordpress-ray`, but with the Electron app. But I didn't know where to file bugs for that.

Using the latest 1.7.0 version of Ray for Windows 10 I can't fold the code. Don't know if the problem was there in earlier versions as well.

**Comment by ibadin** [comment]
I have same problem with collapsing.
**Versions:**
— Ray 1.10.1 
— Wordpress Plugin 1.2.2
— macOS Catalina 10.15.5
— PHP 7.4.2

**Comment by DonDiegoAA** [comment]
I have same problem with collapsing.
Versions:
— Ray 1.12.0.0
— Laravel 7.28.3
— composer "spatie/laravel-ray": "^1.12"
— Windows 10 - Laragon - Php 7.4.11

**Comment by roberttolton** [comment]
I am experiencing this too.

Mac OS Catalina `10.15.7 (19H15)`
Ray App  `1.13.0 (1.13.0)`
laravel/framework `7.29.3`
spatie/laravel-ray `1.9.1`
spatie/ray `1.17.1`

When I click on the arrows to collapse dumped arrays etc, nothing happens.

**Comment by AdrianMrn** [comment]
@roberttolton What command are you running to get the uncollapsible dumps? Could you try installing the demo app (https://github.com/spatie/laravel-ray-demo-app) and running `ray(app())`? This seems to work perfectly fine for me.

**Comment by adevade** [comment]
I still have this issue as well, using latest desktop client and the WordPress plugin. 
I'm just running the default `ray($object || $array)` and it has never worked on my machine. Any way to open the Chromium JS console to look for any errors?

**Comment by roberttolton** [comment]
@AdrianMrn I'm just using `ray()` to output an array, which is at most about 4 levels deep. No doubt the demo app would probably work, but would be useful to have access to the Ray error log or something.

**Comment by AdrianMrn** [comment]
@adevade @roberttolton To get a terminal for the app, please follow the following steps on Windows:

- Open your cmd/powershell
- Run `cd C:\Users\Adriaan\AppData\Local\Programs\Ray` (or wherever the app is installed on your system, don't forget to at least change your user directory)
- Run `.\Ray.exe ----remote-debugging-port=20987`
- Open your browser and navigate to `localhost:20987` and click "webpack app", you should now be able to open the console and see any errors that occur in the renderer

Please let me know if this allows you to see any errors when the app is rendering the collapsible arrows! Also, if anyone is able to create a small repo where I can reproduce this error, it'd make it much easier for me to debug, and would be greatly appreciated!

**Comment by adevade** [comment]
@AdrianMrn Just tried this on my Windows machine, but I get `ERR_CONNECTION_REFUSED` when I try to access `localhost:20987`. Tried with Valet-win running and with it stopped. Tried with four dashes for the argument (as you wrote) and with only two.

This is the output I'm getting in PowerShell:
```powershell
PS C:\Users\adeva\AppData\Local\Programs\Ray> .\Ray.exe --remote-debugging-port=20987

DevTools listening on ws://127.0.0.1:20987/devtools/browser/40417924-af1d-4e55-a601-redacted
15:03:49.239 > Checking for update
```

But I can't access that page for some reason.

**Comment by patinthehat** [comment]
@adevade You can try browsing to `chrome://inspect` in chrome and see if you're able to open it from there.

**Comment by adevade** [comment]
@patinthehat Thanks! Got it working thanks to you!

This is the console error I get when I click on an arrow to close an array:

```log
main.js:62 Uncaught TypeError: Cannot read property 'substr' of null
    at main.js:62
    at HTMLPreElement.<anonymous> (main.js:62)
    at HTMLPreElement.l (main.js:18)
(anonymous) @ main.js:62
(anonymous) @ main.js:62
l @ main.js:18
```

**Comment by PanjiNamjaElf** [comment]
I have same problem with collapsing.
Versions:
— Ray 1.14.4.0
— Laravel 7.28.4
— composer "spatie/laravel-ray": "1.17.1"
— Windows 10 -  Xampp PHP 7.4.16

But when i try to latest laravel app and send `ray(app())` or `dd($array)` i can collapse & uncollapse the array

![image](https://user-images.githubusercontent.com/16651293/111560572-576cfe80-87c5-11eb-9ac9-8b73bf6bf2a4.png)

**Comment by AdrianMrn** [comment]
Thanks to @adevade's I've found where the error occurs, but I still can't reproduce this. If someone could create a minimal reproducible example and share it with me on GitHub, I'd be very much obliged!

**Comment by adevade** [comment]
@AdrianMrn I've created a default WP install where I still see the bug. 

https://github.com/adevade/ray-debugging

There's a SQL-dump in the root.

Username for login is `admin` and password is `password` on `/wp-login.php`.

The Ray plugin is installed, and I added a custom plugin that just dumps the WP database object.

Custom plugin is located in `/wp-content/plugins/ray-debugging.php`.

**Comment by AdrianMrn** [comment]
@adevade Thanks a bunch for the repo! I managed to reproduce the issue, and figured out that it was caused by the Symfony dump in WordPress working slightly different from the Laravel version.

I've managed to fix the bug, but I might have broken other things along the way because I'm not entirely familiar with the Symfony dump script 😁 Please let me know if you run into any new issues when 1.14.7 releases!

**Comment by adevade** [comment]
@AdrianMrn Woop woop!! 🎉🎉
