### ISSUE TITLE
Getting buggy when "Show app" set to "On Menubar"

### ISSUE THREAD

**Issue by pieterhielkema** [spatie/ray#22]
**Describe the bug**
Not able to reach context menu in the left top. (worked with any other app)
Not able to go to settings in any way
No app icon in the menubar

**Versions**
Ray version: 1.0.2
spatie/ray package version:
spatie/laravel-ray package version (if applicable): 
Laravel version (if applicable):
Media Library Pro version:

**To Reproduce**
1. Go to preferences
2. Set "Show App" to "On Menubar"
3. Close settings

**Expected behavior**
Icon added to menubar I guess?!?
Just the normal mac context menu, shown when focused (was visable before changing this setting)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Version 11.0.1
 
 **Additional context**
When the auto update came, I had a change to go the the tips page. There was a link to the config on the "Tips" page, so I could set it back to "On Dock"

**Comment by pieterhielkema** [comment]
If the menubar icon contains a link to settings, the only problem is the icon not showing up.

**Comment by AdrianMrn** [comment]
@pieterhielkema Could you update the app to the latest version (it should automatically update when launching), and see if this issue still occurs?

If the problem persists, I'll reopen the issue and investigate further.
