### ISSUE TITLE
local_path is shown twice on file hover

### ISSUE THREAD

**Issue by sinnbeck** [spatie/ray#220]
**Describe the bug**
Path to file is listed double when hovering the filename

```
'remote_path' => env('RAY_REMOTE_PATH', '/app'),
'local_path' => env('RAY_LOCAL_PATH', '/var/www/intranet'),
```

**Versions**
Ray version: 1.7.0
You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.14.0
- spatie/laravel-ray package version: 1.8.0

PHP version:
Laravel version : 8.23.1

**To Reproduce**
1. Set a local_path in the config file
2. Send though a ray() message
3. Hover the file

**Expected behavior**
I wouldnt expect it to be listed twice :)

**Screenshots**
![image](https://user-images.githubusercontent.com/13980140/105180658-25278380-5b2b-11eb-90ab-735020785ed1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version  20.04
 - Running on Docker

**Comment by sinnbeck** [comment]
Seems to be happen when missing a trailing / in local_path and remote_path 

```
    'remote_path' => env('RAY_REMOTE_PATH', '/app/'),
    'local_path' => env('RAY_LOCAL_PATH', '/var/www/intranet/'),

**Comment by freekmurze** [comment]
I'll investigate this soon. If you already know a good fix, please send a PR!

**Comment by sinnbeck** [comment]
The issue comes from the fact that `str_replace()` will replace all occurences found

The string will look like this `/app/app/Http/Controllers/HomeController.php`. So when replacing `/app`, it will be replaced twice.

I will look into helping out with a fix when I can find the time :)
