### ISSUE TITLE
Ray shows `<code>null</code>` for a FALSE value

### ISSUE THREAD

**Issue by joanfabregat** [spatie/ray#223]
**Describe the bug**
Ray shows `<code>null</code>` for a `false` value in v1.7.

**Versions**
Tested with Ray v1.7.0 with the the v1.12.0 of the `spatie/ray` PHP client.

PHP version:
```
➜  ~ php -v
PHP 7.4.14 (cli) (built: Jan  8 2021 13:20:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies
```

**To Reproduce**
Execute:
```php
ray(false);
```

Ray will display:
<img width="1082" alt="Screenshot 2021-01-20 at 19 28 48" src="https://user-images.githubusercontent.com/4227907/105218852-fa065980-5b55-11eb-9698-076cfb78aa2a.png">

**Expected behavior**
Ray should display `false` instead of `<code>null</code>`.

**Desktop (please complete the following information):**
macOS v11.1
 
 **Additional context**
PHP is installed using Homebrew.

**Comment by freekmurze** [comment]
This is fixed in the latest version of the package. Please run composer update to pull it in 👍

**Comment by joanfabregat** [comment]
@freekmurze Thanks, I'll update it
