### ISSUE TITLE
String on SQL queries printed not surrounded with quote

### ISSUE THREAD

**Issue by zynth17** [spatie/ray#228]
**Describe the bug**
Debugging an sql queries on laravel prints no problem, the problem is only if the string data does not surround by quote or double quote so when i try to run it on my mysql queries i need to change it one by one

**Versions**
Ray version 1.7.0.0

- spatie/ray package version:  1.14.0
- spatie/laravel-ray package version (if applicable): 1.8.0

PHP version: 7.4.3
Laravel version (if applicable): 8

**To Reproduce**
1. run ray()->showQueries()
2. run any queries loading with string variable (e.g where name = 'john doe')
3. check the printed queries in ray

**Expected behavior**
string on show queries supposed to be surronded by quote

**Screenshots**
![image](https://user-images.githubusercontent.com/45350572/105333425-4c07b780-5c08-11eb-8b60-5b8f5c89c819.png)

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by AdrianMrn** [comment]
I don't write SQL that often anymore, but am I correct in assuming every binding/value should be wrapped in quotes, except for integers? Or are there other types of queries where wrapping in quotes in unnecessary and/or could break the query?

**Comment by zynth17** [comment]
> I don't write SQL that often anymore, but am I correct in assuming every binding/value should be wrapped in quotes, except for integers? Or are there other types of queries where wrapping in quotes in unnecessary and/or could break the query?

yes it is correct that every binding/value should be wrapped in quotes  and integer can also wrapper in quotes but it is better that integer does not wrapped in quotes
