### ISSUE TITLE
Docs: Configure link redirects so different page

### ISSUE THREAD

**Issue by jmslbam** [spatie/ray#230]
**Before creating a new bug report**
No duplicate bug report found

**Describe the bug**
When I click the link "Configure Ray if needed" on this page https://spatie.be/docs/ray/v1/getting-started I get to see a different page then expected:

Href value in link: https://spatie.be/docs/ray/v1/configuration/general
Redirects to: https://spatie.be/docs/ray/v1/introduction
Expected link to show page: https://github.com/spatie/ray/blob/master/docs/using-a-config-file/general.md

Don't know if you want to rename the directory or change the link to `using-a-config-file` if I suspect the Docs generation to work like this.

**Versions**
Docs in master branch.

**Expected behavior**
Expected link to show page generate based on this Markdown file: https://github.com/spatie/ray/blob/master/docs/using-a-config-file/general.md

Thank you for building Ray, already love it!

**Comment by freekmurze** [comment]
Thanks for reporting this!

Could you send a PR to correct this? There a button on top of every page at https://spatie.be/docs/ray
