### ISSUE TITLE
Array dropdowns not working

### ISSUE THREAD

**Issue by RyanNutt** [spatie/ray#233]
**Describe the bug**
Duplicate arrows show up to drop down array contents. When there are more than one, it's not able to toggle visibility by clicking on the arrows. 

It only seems to happen when set to show the most recent calls on the top of the ray window instead of the bottom. 

If I send several calls to ray like `ray(request()->all())` the last one, the one on top, works correctly. The second to last has two arrows and will not toggle. The third from last has 3 arrows and the fourth has 4 arrows. Only the one with one arrow works. 

![image](https://user-images.githubusercontent.com/7416974/105394761-99bdf900-5be3-11eb-9e3a-700578cc3aa7.png)
This is the first call to `ray(request()->all())` but the bottom on the interface since it's set to display new calls on top.  

**Versions**
Ray version: 1.7.0.0
spatie/ray: 1.14.0
spatie/laravel-ray: 1.8.0
laravel/framework: 8.22.0
PHP version: 7.4.3

**To Reproduce**
1. Add multiple calls to `ray()`. that would output something with a toggle like an array or model. Doesn't seem to matter what it's outputting or whether there's code in between the calls. 

**Expected behavior**
Able to toggle view on arrays

**Screenshots**
See above. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 
 **Additional context**
I'm using a Docker container with Apache and PHP to hold and run the project I'm working on.

**Comment by freekmurze** [comment]
I' can't seem to reproduce this one. Could you create a minimal app where you see the error?

<img width="812" alt="image" src="https://user-images.githubusercontent.com/483853/105461039-f2959c00-5c8c-11eb-8429-f93c911a359f.png">

**Comment by RyanNutt** [comment]
This is on a clean version of Laravel 8.24.0. Only thing added with composer other than what Laravel installed was `spatie/laravel-ray`  1.9.0 and whatever dependencies it added. 

Created an artisan command with the following.
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class DoSomething extends Command
{
    protected $signature = 'do:something';
    protected $description = 'Command description';
    public function __construct()
    {
        parent::__construct();
    }
    public function handle()
    {
        $ray = [1, 2, 3, 4, 5];
        ray($ray);
        ray($ray);
        ray($ray);
    }
}
```

Gives me the following in Ray. It's set for the most recent calls to go to the top.
![image](https://user-images.githubusercontent.com/7416974/105520010-bfa8d380-5c9f-11eb-93da-429ac3111875.png)

The top and bottom calls are collapsable even though the bottom, first one called, has 3 arrow indicators. The middle call is not collapsable. 

After running `artisan do:something` again it puts the 3 calls at the top, and like last time the top and third are collapsable, but the middle is not.

The 3 previous calls are all now showing with 3 arrows and all 3 are collapsable, even the one that wasn't before. 

Changing the option in the Ray app so that new calls go to the bottom of the window instead of on top causes the arrows and collapsing to be correct. 

![image](https://user-images.githubusercontent.com/7416974/105520606-84f36b00-5ca0-11eb-90fe-03768b25d610.png)

**Comment by RyanNutt** [comment]
Tried something else. Ran 10 lines of `ray($ray)` in the same artisan command. It put the 10 calls into Ray, reverse stacked with the most recent on top. Each call going down the window got one more arrow up to 10 for the bottom call.

The lines with an odd number of arrows were clickable and collapsable. The lines with an even number of arrows were not.

**Comment by voidgraphics** [comment]
Same problem here. Seems to only happen with new items = on top.

**Comment by sinnbeck** [comment]
Does the same thing happen if you use `dump()` instead of ray, to dump to the browser?

**Comment by AdrianMrn** [comment]
Thanks for the help in debugging this one everyone, a fix for this will be included in 1.10.1, which will be released later today or tomorrow!

**Comment by freekmurze** [comment]
Closing this, release is incoming (will be available in 10 minutes or so)

**Comment by jjjrmy** [comment]
I'm on ray 2.0.1 and this still happens ALL THE TIME.
