### ISSUE TITLE
Ray add <br\> instead of first \n

### ISSUE THREAD

**Issue by Aigleblanc** [spatie/ray#234]
**Describe the bug**

Ray add `<br\>` instead of first `\n`

1. Insert 3 lines in textarea,

```html
line1\n
line2\n
line3 
```

2. Send this line with ajax on my script.
3. Show data in POST

```php
var_dump( $this->input->post('mess', true) );
echo '<br>';
var_dump( nl2br(trim($this->input->post('mess', true) )));

Ray( $profil_id, $this->input->post('mess', true) );
Ray( $profil_id, nl2br(trim($this->input->post('mess', true) ) ) );
```

Ray add `<br/>`  for the first `\n` all time even when I don't do `nl2br()`

Compare return `var_dump()` and `ray()` in my screen.

**Versions**
 spatie/ray 1.14.0

PHP version:
7.4

**Screenshots**

![Capture d’écran 2021-01-21 192514](https://user-images.githubusercontent.com/1475705/105395390-f4287b00-5c1e-11eb-89e2-05ff74a6260a.png)

**Comment by freekmurze** [comment]
I don't understand this issue. Could you clarify with a more simple example? Or maybe create an example app for us to look at?

**Comment by Aigleblanc** [comment]
### 1. The Request Ajax

This is Post Request send with ajax :

```
mess=Line1%0Aline2%0Aline3
```

Line1 **\n** Line2 **\n** line3

One \n inner every line.

### 2. The Ajax result 

```json
{"success":true,"data":{"mess":"line1\nline2\nline3","date":"00:10"}}
```
One \n inner every line in json return

### 3. The var_dump result

```
string(17) "line1 line2 line3"
```

var_dump return my content without `<br/>` and `\n` is not interpreted

### 4. The Ray result in app

But in same time, In ray application ( win 10 ) last maj, 

```
line1<br />line2 line3
```

5. Expected result in Ray app

```
line1 line2 line3
```

Why see : line1 **`<br />`** line2 line3

_I think, Ray app parse result and convert the first `\n` in <br/>_

**Comment by freekmurze** [comment]
Closing this as all latest versions or the app / packages seem to behave well.

<img width="836" alt="image" src="https://user-images.githubusercontent.com/483853/105460770-92065f00-5c8c-11eb-9d7b-a69c0ba44042.png">
