### ISSUE TITLE
Need help with WSL2

### ISSUE THREAD

**Issue by deanhouseholder** [spatie/ray#235]
I am having trouble getting a CLI-based php app to run under Windows 10 WSL2.

Versions:
Ray Desktop App 1.7.0.0.
spatie/ray 1.14.0

I did the composer require to my project and added my `ray();` statements, but it didn't display in the Ray desktop app. It is a generic PHP app.

In reading through the docs, I read this page:
https://spatie.be/docs/ray/v1/environment-specific-configuration/windows-10

And was confused on where this configuration should be configured. I assumed it should be in the install folder, but I couldn't find a config file there. I finally found this page:
https://spatie.be/docs/ray/v1/using-a-config-file/framework-agnostic-php

Which said at the top to put it in a `ray.php` file. This was hard to piece together, so I propose that the Window 10 documentation page be updated to explain this more clearly.

So I created a ray.php file in my project directory and configured it in the following way:

```php
<?php

return [
    // Windows 10 Host OS IP (Where Ray is)
    'host' => '192.168.7.55',

    // Absolute base path for your sites or projects in Homestead, Vagrant, Docker, or another remote development server.
    'remote_path' => '/home/dean/code/tts',

    // Absolute base path for your sites or projects on your local computer where your IDE or code editor is running on.
    'local_path' => '\\wsl$\Ubuntu-20.04\home\dean\code\tts',
];
```

But when I executed the project under the WSL2 environment (running it from the terminal), it didn't log to the Ray desktop app.

I searched through my Event Viewer logs and couldn't find any errors there. I restarted the desktop app multiple times. I am on a Work VPN so I tried all the IP addresses associated with my machine (running `ipconfig` from a command prompt).

I tried running it from a command prompt itself (tricky with command prompt not liking `\\wsl$\` paths (a symlink did the trick), and it did work. Meaning, it logged to the Ray desktop app. But this command prompt environment is not configured right, and caused several errors in the code.

Ultimately, I'd like help getting it to work in my WSL2 environment as the docs aren't getting me there.

Finally, props on a fantastic-looking product!!! 🥳

**Comment by oliverhermanni** [comment]
I just tested it with latest version of `Ray app` (1.9.0) and `spatie/ray`  (1.16). Works fine for me. 

My test setup:

test.php:
```php
<?php
require('vendor/autoload.php');
ray('test');
```` 

ray.php
```php
<?php
return [
    'host' => '192.168.178.20' // IP of my Windows, not WSL2
];
```
(I left `local_path` and `remote_path` out, because I'm using PhpStorm which doesn't properly support `\\$wsl\...`)

I ran `php test.php` and this is the result:

![image](https://user-images.githubusercontent.com/1240179/105556907-4fd03280-5d0b-11eb-8ff0-0d03aef95c30.png)

**Comment by deanhouseholder** [comment]
Upgrading to the latest versions fixed it. Thanks for the help. Also nice to know I don't have to hard-code the project code paths!

I do suggest updating the documentation here when you get some time:
 https://spatie.be/docs/ray/v1/environment-specific-configuration/windows-10

Thanks!
