### ISSUE TITLE
ray.php file not found

### ISSUE THREAD

**Issue by barchard** [spatie/ray#236]
Each call to `ray()` returns a new Ray object. This then calls into the SettingsFactory and causes a directory search for `ray.php`. The first time this is called, this finds the `ray.php` file as `getcwd` returns the correct path. Subsequent calls to `ray()` and thus `getcwd()` returns `/` and doesn't find the `ray.php` file.

**Versions**
1.7.0

You can use `composer show` to get the version numbers of:
spatie/ray                           1.14.0    Debug with Ray to fix problems faster

PHP version:
7.4.12 (MAMP)

**To Reproduce**

**Expected behavior**
I expect ray.php to be honored no matter how many times I call ray()

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS MAMP6
 
 **Additional context**

code changes made to debug `SettingsFactory.php`:

```
    protected function searchConfigFiles(string $configDirectory = null): string
    {
        $configNames = [
            'ray.php',
        ];
error_log('config dir before: '.print_r($configDirectory, true));

        $configDirectory = $configDirectory ?? getcwd();
error_log('config dir after: '.print_r($configDirectory, true));
...
```

Error log output:

```
[22-Jan-2021 02:35:55 UTC] config dir before: 
[22-Jan-2021 02:35:55 UTC] config dir after: /Users/username/Sites/path/files
[22-Jan-2021 02:35:55 UTC] Array
(
    [enable] => 
    [send_log_calls_to_ray] => 
    [send_dumps_to_ray] => 
    [host] => localhost
    [port] => 23517
)

[22-Jan-2021 02:35:55 UTC] config dir before: 
[22-Jan-2021 02:35:55 UTC] config dir after: /
[22-Jan-2021 02:35:55 UTC] config dir before: 
[22-Jan-2021 02:35:55 UTC] config dir after: /
```

code calling ray:

```
	require_once('../path/to/autoload/vendor/autoload.php');

		// Set an error_log file if none is set.
		//if (empty(ini_get('error_log'))) {
			@ini_set('error_log', __DIR__.'/error_log');
		//}

		// Initialize error reporting

		
		// Ray tracing
		//ray(getcwd());
        ray()->measure();


		ob_start(function($content) use ($obj) {        		
        		ray()->notify('processing complete!');
            
            //
            	ray()->measure();
        		return $content;
    		});
```

**Comment by freekmurze** [comment]
I've done a quick test and `getcwd` always seems to return the right result.

Do you have an idea why the function would produce a different result for subsequent calls for you?

I'd accept a PR that fixes this problem for you.

**Comment by barchard** [comment]
I thought about this some more, I think it's related to the closure. Need to test some more tonight. Thanks

**Comment by barchard** [comment]
To update this, I can confirm the behavior of `getcwd()` in the closure is what is causing the issue. Code:

```
// Set an error_log file if none is set.
		//if (empty(ini_get('error_log'))) {
			@ini_set('error_log', __DIR__.'/error_log');
		//}

		// Ray tracing
        ray()->measure();


		ray()->measure();
error_log('before closure cwd '.getcwd());
		ob_start(function($content) use ($formsPlus_stacks_in_2) {
		
			error_log('in closure cwd '.getcwd());

        		ray()->notify('FormsPlus stacks_in_2 processing complete!');
            
            //
            ray()->measure();
        		return $content;
    		});
```

Modified `SettingsFactory.php`:

```
    protected function searchConfigFiles(string $configDirectory = null): string
    {
        $configNames = [
            'ray.php',
        ];
error_log('config before: '.print_r($configDirectory, true));
        $configDirectory = $configDirectory ?? getcwd();
error_log('config after: '.print_r($configDirectory, true));
...
```

Error log:

```
[22-Jan-2021 22:42:28 UTC] config before: 
[22-Jan-2021 22:42:28 UTC] config after:  /path/to/src/files
[22-Jan-2021 22:42:28 UTC] config before: 
[22-Jan-2021 22:42:28 UTC] config after:  /path/to/src/files
[22-Jan-2021 22:42:28 UTC] before closure cwd /path/to/src/files
[22-Jan-2021 22:42:28 UTC] in closure cwd /
[22-Jan-2021 22:42:28 UTC] config before: 
[22-Jan-2021 22:42:28 UTC] config after: /
[22-Jan-2021 22:42:28 UTC] config before: 
[22-Jan-2021 22:42:28 UTC] config after: /
```

**Comment by barchard** [comment]
@freekmurze I can think of two ways to possibly tackle this.

1. add a global in `helper.php` so there is only 1 Ray object initialized or
2. add functionality to make a static instance of the Ray object to some base class

I can't think of a way to preserve or switch context from a closure or thread. Unless you have any thoughts here, which would you prefer? Easiest is global but, obviously, pollutes the global namespace. 

Thanks

**Comment by freekmurze** [comment]
We'll continue this in #238
