### ISSUE TITLE
`Package "spatie/laravel-ray" is not installed` in production

### ISSUE THREAD

**Issue by MatanYadaev** [spatie/ray#245]
**Describe the bug**
Every incoming HTTP request in production throws this exception (Also when executing `ray('test')`):
```
OutOfBoundsException with message 'Package "spatie/laravel-ray" is not installed'
```

**Versions**
- spatie/ray package version: 1.16.0
- spatie/laravel-ray package version: 1.9.0

PHP version:
Laravel version: 7.4.13

**To Reproduce**
1. `composer require spatie/laravel-ray --dev`
2. Add `composer.lock` to the repo
3. `composer install --no-interaction --prefer-dist --optimize-autoloader`

**Expected behavior**
Ray shouldn't throw any exceptions on production.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04
 
 **Additional context**
The issue is with `Composer\InstalledVersions` class. It doesn't work on my production environment at all, probably because of the flag `--optimize-autoload`.
Even this fails:
```php
Composer\InstalledVersions::getVersion('laravel/framework')
// >>> OutOfBoundsException with message 'Package "laravel/framework" is not installed'
```

**Comment by MatanYadaev** [comment]
Fixed by updating to Composer 2. Maybe it's worth mentioning it in the documentation.

**Comment by Daronspence** [comment]
I had this same error but not with the dev flag. Composer 2 seemed to fix it as well. I have to go back and forth for legacy projects. Maybe there would be some way to acknowledge that within the composer.json for the package?
