### ISSUE TITLE
Ray'ing \r\n displays as <br /> in the app

### ISSUE THREAD

**Issue by Tarpsvo** [spatie/ray#249]
**Describe the bug**
When logging a line break (`\r\n`), the string is turned into a HTML line break `<br />`.

**Versions**
Ray version (you can see this in "About Ray"): 1.10.1
- spatie/ray package version: 1.13
- spatie/laravel-ray package version (if applicable): 1.9.1

PHP version:
Laravel version (if applicable): 7.4.14

**To Reproduce**
1. `ray('\r\n')`
2. Check app

**Expected behavior**
I expect the app to show the string as it is: `\r\n`

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6

**Comment by freekmurze** [comment]
Seems to work here.

Make sure you use the latest versions.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/483853/105996691-fcfbcf80-60aa-11eb-9160-d62490e1288f.png">

**Comment by freekmurze** [comment]
Other slashes work as well 🙂 

<img width="545" alt="image" src="https://user-images.githubusercontent.com/483853/105996883-37656c80-60ab-11eb-8415-f05a4dcc65aa.png">

**Comment by Tarpsvo** [comment]
Oops, `composer update` did the trick. 🙄 

Thanks!
