### ISSUE TITLE
Unable to send events from Laravel to Ray App via Homestead using Virtualbox or Parallels providers.

### ISSUE THREAD

**Issue by svpernova09** [spatie/ray#258]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
Unable to send events from Laravel to Ray App via Homestead using Virtualbox or Parallels providers.

**Versions**
Ray version: Version 1.12.0 (1.12.0)

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable):

```
└── composer show | grep ray
spatie/laravel-ray                 1.10.1  Easily debug Laravel apps
spatie/ray                         1.17.1  Debug with Ray to fix problems faster
```

PHP version: 7.4.13
Laravel version (if applicable): Laravel Framework 8.25.0

**To Reproduce**
1. Create a [Homestead v10.17.0 environment](https://github.com/laravel/homestead/releases/tag/v10.17.0) (See `Homestead.yaml` below)
2. Configure Ray in Project's root `ray.php`:
```php
<?php

return [
/*
* This settings controls whether data should be sent to Ray.
*
* By default, `ray()` will only transmit data in non-production environments.
*/
'enable' => env('RAY_ENABLED', true),

    /*
    * When enabled, all things logged to the application log
    * will be sent to Ray as well.
    */
    'send_log_calls_to_ray' => env('SEND_LOG_CALLS_TO_RAY', true),

    /*
    * When enabled, all things passed to `dump` or `dd`
    * will be sent to Ray as well.
    */
    'send_dumps_to_ray' => env('SEND_DUMPS_TO_RAY', true),

    /*
    * The host used to communicate with the Ray app.
    * For usage in Docker on Mac or Windows, you can replace host with 'host.docker.internal'
    * For usage in Homestead on Mac or Windows, you can replace host with '10.0.2.2'
    */
    'host' => env('RAY_HOST', '10.0.2.15'),

    /*
    * The port number used to communicate with the Ray app.
    */
    'port' => env('RAY_PORT', 2200),

    /*
     * Absolute base path for your sites or projects in Homestead,
     * Vagrant, Docker, or another remote development server.
     */
    'remote_path' => env('RAY_REMOTE_PATH', null),

    /*
     * Absolute base path for your sites or projects on your local
     * computer where your IDE or code editor is running on.
     */
    'local_path' => env('RAY_LOCAL_PATH', null),
];
```
3. Using the following code to `routes/web.php`:
```php
Route::get('/', function () {
    ray('My first ray call');
    dd(ray('My first ray call'));
    return view('welcome');
});
```
4. Configure Ray macOS Communication Port: `2200`
5. Load http://192.168.20.20 in a web Browser and see:
```
Spatie\LaravelRay\Ray {#344 ▼
  +settings: Spatie\Ray\Settings\Settings {#57 ▼
    #settings: array:8 [▼
      "enable" => true
      "send_log_calls_to_ray" => true
      "send_dumps_to_ray" => true
      "host" => "10.0.2.15"
      "port" => 2200
      "remote_path" => null
      "local_path" => null
      "always_send_raw_values" => false
    ]
    #defaultSettings: array:5 [▼
      "host" => "localhost"
      "port" => 23517
      "remote_path" => null
      "local_path" => null
      "always_send_raw_values" => false
    ]
  }
  +uuid: "0bb4e9a1-3dac-4283-b6b0-4cf28cbbf310"
}
```

**Expected behavior**
"My first ray call" to appear in the Ray app window.

**Screenshots**

**Desktop (please complete the following information):**
- OS: [e.g. macOS] macOS
- Version [e.g. 22] 11.1 (20C69)

**Additional context**

`ifconfig` from inside Homestead using Virtualbox:

```bash
vagrant@homestead:~$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:feaa:c912  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:aa:c9:12  txqueuelen 1000  (Ethernet)
        RX packets 5773  bytes 1954614 (1.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3547  bytes 611146 (611.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.20.20  netmask 255.255.255.0  broadcast 192.168.20.255
        inet6 fe80::a00:27ff:fe6d:6ca8  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:6d:6c:a8  txqueuelen 1000  (Ethernet)
        RX packets 83  bytes 11218 (11.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 84  bytes 90095 (90.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 193  bytes 58540 (58.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 193  bytes 58540 (58.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Homestead Configuration (`Homestead.yaml`):

```yaml
---
ip: "192.168.20.20"
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa

folders:
    -   map: ~/Code/fresh-laravel
        to: /home/vagrant/laravel
sites:
    - map: laravel.test
      to: /home/vagrant/laravel/public

services:
    - enabled:
          - "mysql"
features:
    - mysql: true

databases:
    - homestead

ports:
    - send: 23517
      to: 23517

```

Here's a gist of the `vagrant destroy -f && vagrant up` command: https://gist.github.com/svpernova09/7bdc907eb21f39ab9932ad4ed62c171d

Notes: I'm mapping ports from host `23517` to Homestead `23517` however [Virtualbox is overriding this](https://gist.github.com/svpernova09/7bdc907eb21f39ab9932ad4ed62c171d#file-vagrantup-log-log-L23) to `2200` on the Host side, but still using `23517` in Homestead. I'm attempting to help a Homestead user however I've been unable to get Ray working myself.

**Comment by LukeTowers** [comment]
> Notes: I'm mapping ports from host 23517 to Homestead 23517 however Virtualbox is overriding this to 2200 on the Host side, but still using 23517 in Homestead

I could be wrong because I'm not an expert on this, but it seems to me like the port mapping in Homestead is just from the VM to the Host and not the other way around. That would explain the host port being switch to 2200, since 23517 is already in use by the Ray app.

**Comment by LukeTowers** [comment]
@svpernova09 any luck with this? @freekmurze were you able to test this at all? Ray is unusable for me if it doesn't work for projects within Homestead.

**Comment by svpernova09** [comment]
> @svpernova09 any luck with this? @freekmurze were you able to test this at all? Ray is unusable for me if it doesn't work for projects within Homestead.

I've attempted to get Ray and Homestead working again this morning. I'm still unable to figure out what I'm doing wrong.

![image](https://user-images.githubusercontent.com/967362/107152917-57f5b800-6930-11eb-8a9b-57755142c390.png)

Virtualbox is mapping the default `23517` in the guest to `2201` on the host. I've tried the public IP `192.168.30.10` and host network `10.0.2.15` and every port combination between the two. The [Ray docs](https://spatie.be/docs/ray/v1/environment-specific-configuration/homestead) mention using `10.0.2.2` which is likely the default host for the default Homstead `192.168.10.10`, but incorrect for my situation because of the different IP. Also the docs mention using "IP you are using for your Homestead environment." which also did not work for me.

I'm not able to continue debugging (or willing to put any more time into this) without further insight into what I'm doing wrong with Ray.

An alternative to Ray which I know Homestead supports would be Xdebug: https://laravel.com/docs/8.x/homestead#debugging-web-requests

**Comment by LukeTowers** [comment]
> Virtualbox is mapping the default 23517 in the guest to 2201 on the host.

@svpernova09 I feel like this is a red herring and not actually helping anything tbh. Am I incorrect in my assumption that the port mapping being done by vagrant is only in one direction, from the guest to the host? Ray would require port mapping from the host to the guest.

**Comment by LukeTowers** [comment]
See https://kb.parallels.com/en/124718, 

> The connection to a specific port on your Mac will be redirected to a specific port of your virtual machine according to the port-forwarding rule.

**Comment by svpernova09** [comment]
> 
> 
> > Virtualbox is mapping the default 23517 in the guest to 2201 on the host.
> 
> @svpernova09 I feel like this is a red herring and not actually helping anything tbh. Am I incorrect in my assumption that the port mapping being done by vagrant is only in one direction, from the guest to the host? Ray would require port mapping from the host to the guest.

The port forwarding is working as expected. (Because I can connect all of the other services via the same shared ports). I've included these notes so to explain my Ray configuration. Based on what I'm seeing, Ray isn't communicating out of the VM at all.

**Comment by LukeTowers** [comment]
@svpernova09 it looks like 10.0.2.2 is the loopback address used by VirtualBox, so if you're using VirtualBox then 10.0.2.2 with the 23517 port WITHOUT port forwarding setup then it should work. I haven't tested it yet though because I use Parallels as a provider.

> Even though the NAT engine separates the VM from the host, the VM has access to the host's loopback interface and the network services running on it. The host's loopback interface is accessible as IP address 10.0.2.2. This access to the host's loopback interface can be extremely useful in some cases, for example when running a web application under development in the VM and the database server on the loopback interface on the host.

https://docs.oracle.com/en/virtualization/virtualbox/6.1/user/networkingdetails.html#network_nat

**Comment by svpernova09** [comment]
> @svpernova09 it looks like 10.0.2.2 is the loopback address used by VirtualBox, so if you're using VirtualBox then 10.0.2.2 with the 23517 port WITHOUT port forwarding setup then it should work. I haven't tested it yet though because I use Parallels as a provider.
> 
> > Even though the NAT engine separates the VM from the host, the VM has access to the host's loopback interface and the network services running on it. The host's loopback interface is accessible as IP address 10.0.2.2. This access to the host's loopback interface can be extremely useful in some cases, for example when running a web application under development in the VM and the database server on the loopback interface on the host.
> 
> https://docs.oracle.com/en/virtualization/virtualbox/6.1/user/networkingdetails.html#network_nat

I understand how it *should* work. This issue is raising the concern that it isn't. 

<img width="1678" alt="Screen Shot 2021-02-07 at 11 28 52" src="https://user-images.githubusercontent.com/967362/107154285-bd00dc00-6937-11eb-842c-0d2b6fffe51b.png">

**Comment by LukeTowers** [comment]
@svpernova09 @freekmurze I think I've found the issue: https://forum.parallels.com/threads/accessing-localhost.258362/#post-828246

Parallel's default host IP address is 10.211.55.2, but it doesn't do any sort of localhost spoofing which means that the requests sent to 10.211.55.2:23517 probably have the Host header set as such, which means that the ray app is probably ignoring the requests since it's technically a request to 10.211.55.2; whereas Virtualbox does do localhost spoofing so the request looks like it's coming from 127.0.0.1 (probably so that they don't run into these sorts of issues). 

I'm not sure what the ray app is using to bind itself to the network, but I believe the **solution is to also have Ray setup to respond to requests on 10.211.55.2 as well as 127.0.0.1 (or perhaps make that configurable for more flexibility).**

**Comment by svpernova09** [comment]
@LukeTowers I'm not using Parallels in the context of this issue. If you've found something that may be causing your issues in Homestead & Parallels that's probably best in its own Ray Issue instead of here. I wanted to see Ray work with Virtualbox before complicating things with a different Provider.

**Comment by LukeTowers** [comment]
@svpernova09 I just tried `10.211.55.2` as the host on my parallels box and it's working fine now. Looks like that was the issue!

**Comment by freekmurze** [comment]
Closing this, as a solution seems to have been found.
