### ISSUE TITLE
<code>null</code> when you do $variable ?? 0;

### ISSUE THREAD

**Issue by Ihabafia** [spatie/ray#262]
I have a statment:
```php```
$var = $xyz ?? 0;
ray($var);

if the var has a value of 400 for example then the result on the ray app is 400, but if the $var is null, then the $var should be equal 0, but when I do ray($var); the result is <code>null</code>.

**Versions**
Ray version: 1.11.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.17.1
- spatie/laravel-ray package version (if applicable): 1.11.1

PHP version:
Laravel version (if applicable): php 7.4.13

**To Reproduce**
1. have a var like: $var = $xyz ?? 0;
2. if $var = 'value' then no problem to ray($var);
3. if the $var = null which will be $var = 0;
4. then the ray($var) will show <code>null</code>

**Expected behavior**
The result of the ray should show 0 if the $var = null;

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 11.1
 
 **Additional context**
That's it, thank you.

**Comment by freekmurze** [comment]
I don't understand the code snippets.

Try ray(null) and ray(0). Does that display the expected results?

**Comment by Ihabafia** [comment]
Hi,

 

I tried:

 

ray(null);
ray(0);

 

the result was 

 

19:23:58

<code>null</code>

web.php:258

19:23:58

Null

null

web.php:257

 

So, the null came as null

And the 0 comes as <code>null</code>.

**Comment by freekmurze** [comment]
Closing this as the latest versions seem to already do the right thing.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/483853/106566064-116b1c80-6530-11eb-9d6d-5008894b6659.png">


Please upgrade to the latest versions.
