### ISSUE TITLE
Windows: cannot open Ray app window

### ISSUE THREAD

**Issue by morvy** [spatie/ray#264]
**Describe the bug**
When I work on one monitor I can use the Ray app normally. If I work on external monitor and forget to move the window back to primary/laptop screen before disconnection the external monitor, I cannot open the Ray window anymore.

**Versions**
Ray version (you can see this in "About Ray"): 1.12

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.17.1
- spatie/laravel-ray package version (if applicable): 1.9.3

PHP version:
Laravel version: 8.25

**To Reproduce**
1. Run the app with external monitor connected and move the app to external monitor
2. Optionally, exit the Ray app
3. Put the computer to sleep/hibernation and then disconnect the external monitor
4. Wake the computer and start the app or use context menu to Show the app window
4. See error / try to find the window anywhere on the current monitor or move it to the current monitor with Win + arrows

**Expected behavior**
A Ray window should be visible at least when starting the app.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2 / 19042.746

**Comment by aurelien31** [comment]
Hi, I have the same issue today. You can resolve this issue by following these steps:
- Mouse over the Ray icon in the taskbar without clicking on it
- Once the app preview appears above the icon, right click on it
- Then click on Maximize and the application will reappear on the screen

Hope this solves your problem 👍

**Comment by morvy** [comment]
Hi,
I noticed this behaviour too, but I had Ray in tray only, so I was unable to maximize it like when you have it in taskbar..

**Comment by freekmurze** [comment]
We've made some changes in Ray 1.4.0 around this. Please open up a new issue if this still an issue for you.

**Comment by aurelien31** [comment]
Hi,

The problem is apparently still present but sporadically.  

I will continue to test in the days to come to be sure.

Regards,
Aurelien

**Comment by AdrianMrn** [comment]
I suppose this is related to https://github.com/spatie/ray/issues/359

I'll try to reproduce this and see if I can find a suitable fix.

**Comment by AdrianMrn** [comment]
A fix will be included in the next release of Ray, likely 1.14.1 🙂

**Comment by aurelien31** [comment]
Cool, I will try as soon as it is available. Thanks.

**Comment by savage-eagle** [comment]
> A fix will be included in the next release of Ray, likely 1.14.1 🙂

Any preview when 1.14.1 will be released?

**Comment by AdrianMrn** [comment]
@savage-eagle I'm releasing 1.14.1 now, I was hoping to get some more performance fixes in, but those took longer than expected and will have to wait until the next patch :)

**Comment by aurelien31** [comment]
Hi,

Thanks @AdrianMrn, this release fixes issues and... what performance improvements too 💯. So cool !!!

Regards,
Aurelien
