### ISSUE TITLE
Mailable styles not being updated in desktop app

### ISSUE THREAD

**Issue by calkeo** [spatie/ray#265]
**Describe the bug**
If you display a mailable in the desktop app, update the stylesheet for the mailable and output the same mailable again, the styles do not update to reflect the updated stylesheet.  This happens when using the default Laravel mailable template and updating default.css.

**Versions**
1.11.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.17.1
- spatie/laravel-ray package version (if applicable): 1.9.1

PHP version: 7.4.13
Laravel version: 8.25.0

**To Reproduce**
1. Display a mailable using `ray()->mailable(new MyMailable());`
2. Update the theme for `MyMailable.php` (in my case I'm using the default mailable template, so updating `default.css`)
3. Display the mailable again using `ray()->mailable(new MyMailable());`

**Expected behavior**
The displayed mailable should use the updated styles from `default.css`, but it is still using the styles from before the updates to `default.css`

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.1
 
 **Additional context**
If you actually send the mailable as an email then the correct styles are output, whilst Ray still displays the old styles.

**Comment by AdrianMrn** [comment]
This has been fixed, and will be released soon in 1.14.7
