### ISSUE TITLE
Windows: Subsequent launching of Ray not working if 'On system tray' is chosen

### ISSUE THREAD

**Issue by erdiegoant** [spatie/ray#27]
**Describe the bug**
The moment I set the "Show App" setting to "On system tray" nothing happened, but next time I launched it didn't work at all.
Had to completely remove all files related to Ray manually because reinstalling didn't help either (From `\AppData\Local\ray-updater` and `\AppData\Roaming\Ray`) and installing fresh again. Using the normal unistaller from the app doesn't resolve the issue.

**Versions**
Ray version: 1.0.2.0
spatie/ray package version:
spatie/laravel-ray package version (if applicable): 
Laravel version (if applicable):
Media Library Pro version:

**To Reproduce**
1. Go to `Preferences`
2. Click on `Show App`
3. Choose `On system tray`
4. Close Ray
5. Open again

**Expected behavior**
The app should have opened just fine, but got stuck in a default Electron window.

**Screenshots**
No screenshot available because I already managed to do a full reinstall and got it working again.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 20H2
 
 **Additional context**

**Comment by AdrianMrn** [comment]
This one should be fixed in the latest build!
