### ISSUE TITLE
Website bug: Price bug

### ISSUE THREAD

**Issue by tyler36** [spatie/ray#28]
**Describe the bug**
Price displays incorrectly in Yen.

**Versions**
Ray version: n/a
Website: https://myray.app/

**To Reproduce**
1. Visit website
2. Check display. Occurs in both places, top and bottom, in both desktop and mobile sized browser.

**Expected behavior**
Could it be prettier? It looks kinda awkward 😥.

**Screenshots**
![Price-page_bottom](https://user-images.githubusercontent.com/7234392/103959738-d6c1ce80-5193-11eb-9d82-abebdd335d3a.png)

**Desktop (please complete the following information):**
Chrome: 87.0.4280.88 (Official Build) (64-bit)
OS: Win10
 
 **Additional context**
I know it's not major and theres no way you for reasonable check every i18n currency. Just thought I'd point it out. 😀

**Comment by freekmurze** [comment]
@willemvb can you look at this?

**Comment by willemvb** [comment]
Thanks @tyler36, should be better now!

**Comment by tyler36** [comment]
Thank you. It looks much better now. 

![Price-page_fixed](https://user-images.githubusercontent.com/7234392/104251824-ea32a980-54b3-11eb-9969-fd312416256c.png)
