### ISSUE TITLE
Windows: slow unit tests when having ray installed 

### ISSUE THREAD

**Issue by Algeneralo** [spatie/ray#285]
**Describe the bug**
Unit Tests are running very slow when having a ray library installed with composer

**Versions**
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 1.11

PHP version: 7.4
Laravel version (if applicable): 8.22

**To Reproduce**
1. Install `spatie/laravel-ray` package on windows for Laravel project
2. run tests using phpStorm

**Expected behavior**
Tests should be done within 2 minutes

**Screenshots**
![image](https://user-images.githubusercontent.com/32073999/107192377-95287b80-69fe-11eb-9c0d-71d76d64ede8.png)

**Desktop :**
 - OS:  Windows 
 - Version: 10
 
 **Additional context**
After removing the package from the composer, tests back to normal speed

**Comment by freekmurze** [comment]
It seems that we cannot reproduce this problem. Our own test suite run very fast on Windows, and we haven't gotten any reports by other users.

Could you create a minimal app that allows up to recreate the problem?

**Comment by freekmurze** [comment]
What happens when you comment the code in this function?

https://github.com/spatie/ray/blob/master/src/Client.php#L23-L43

**Comment by Algeneralo** [comment]
> What happens when you comment the code in this function?
> 
> https://github.com/spatie/ray/blob/master/src/Client.php#L23-L43

Yeah, that's work!
when I removed the code inside this function, everything return as it is

**Comment by freekmurze** [comment]
What happens if you change this value to `1` or `0`?

https://github.com/spatie/ray/blob/master/src/Client.php#L101

**Comment by Algeneralo** [comment]
ok so I got the following thing, I restart the Laptop to be sure that Ray is not working in the background.
I tried to run the tests. tests are slow.
I opened the ray app, run the tests again, now it back to be normal.

So the issue as I guess that the `send` function tries to detect the Ray app in the background, but the app is not working yet since I didn't open it when I started the windows. but if I opened the Ray for one time, everything works even if I closed it after that.

**Comment by Algeneralo** [comment]
> What happens if you change this value to `1` or `0`?
> 
> https://github.com/spatie/ray/blob/master/src/Client.php#L101

Nothing

**Comment by freekmurze** [comment]
Nothing as you don't see anything anymore in Ray? Or as in, the results stay slow? Or do the results stay fast?

**Comment by Algeneralo** [comment]
> Nothing as you don't see anything anymore in Ray? Or as in, the results stay slow? Or do the results stay fast?

Sorry for not clearing the things, I meant nothing for the slow, it's still slow as it's.
For the result, I'm not sure because I told you, the issue will disappear after opening the Ray app

**Comment by Algeneralo** [comment]
@freekmurze 
The issue is fixed now, Thanks!
