### ISSUE TITLE
After Big Sur OS upgrade ray doesn't work anymore

### ISSUE THREAD

**Issue by ronnievisser** [spatie/ray#288]
I was previously running this app without any problems on Homestead. I update my OS to macOS Big Sur, With that also virtual box needed an update. After that has been completed the ray app is not showing any information anymore. Before the upgrade all worked fine.

Ray version: 1.12.0
spatie/ray package version: 1.19.2
spatie/laravel-ray: 1.12.3
Laravel version (if applicable): v8.26.1

**To Reproduce**
1. Upgrade to MacOS Big Sur
2. Upgrade virtualbox
3. Reboot
4. Start Homestead

Is there anything I can do to debug what's going on?

Thanks

**Comment by freekmurze** [comment]
Could you test if the previously tagged version works for you?

**Comment by ronnievisser** [comment]
No differences. still not working. tried to go down to laravel-ray 1.9.3

**Comment by ronnievisser** [comment]
re-provisioned homestead again and not all works fine again.
