### ISSUE TITLE
Client.php cache fingerprint not initialised correctly

### ISSUE THREAD

**Issue by Polfo** [spatie/ray#290]
**Describe the bug**
In https://github.com/spatie/ray/blob/c29066b/src/Client.php#L23, we see 
```php
public function __construct(int $portNumber = 23517, string $host = 'localhost')
{
    $this->fingerprint = md5($this->host . ':' . $this->portNumber);

    $this->portNumber = $portNumber;

    $this->host = $host;
}
```
This is probably an error, as `$this->host` is `null` in the constructor. I suppose it should be
```php
$this->fingerprint = md5($host . ':' . $portNumber);
```
**Versions**
Ray version 1.19.2

**Comment by Polfo** [comment]
There is no need for a hash here. 
`$this->fingerprint = $host . ':' . $portNumber;`
would also work and not obfuscate the bug.

**Comment by patinthehat** [comment]
Good catch, I'll submit a fix.  Thanks!
