### ISSUE TITLE
Generic Questions and Issues Documentation page referring to laravel-ray issues 

### ISSUE THREAD

**Issue by Polfo** [spatie/ray#291]
**Describe the bug**
Page https://spatie.be/docs/ray/v1/questions-issues has a "Feel free to create an issue on GitHub" text linking to https://github.com/spatie/laravel-ray/issues

**Expected behavior**
Only link to `spatie/laravel-ray/issues` for laravel-ray related issues, not for all issues.

See
https://raw.githubusercontent.com/spatie/ray/master/docs/questions-issues.md

**Comment by morvy** [comment]
well, yeah .. that's why I've created an issue for Ray app in laravel-ray repo :\

**Comment by freekmurze** [comment]
I'll correct this. If you see other things that are off, feel free to submit a PR.
