### ISSUE TITLE
[Linux] Trial mode does not reset after restarting Ray

### ISSUE THREAD

**Issue by bolovdor** [spatie/ray#293]
**Describe the bug**
Trial mode does not reset after restarting Ray.

**Versions**
Ray version (you can see this in "About Ray"): `1.12.0`

You can use `composer show` to get the version numbers of:
- spatie/ray package version: `1.19.3`
- spatie/laravel-ray package version (if applicable): `1.12.3`

PHP version:7.4.14
Laravel version (if applicable): `8.26.1`

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55972209/107368812-ae5a2680-6ae9-11eb-9fb5-a38f196983bb.png)
![CV2qSpAZ13](https://user-images.githubusercontent.com/55972209/107369925-004f7c00-6aeb-11eb-97e0-937c30c84a50.gif)

**Desktop (please complete the following information):**
 - Ubuntu 18.04.5
 
 **Additional context**
Not sure if this is related:

- In issue https://github.com/spatie/ray/issues/36#issuecomment-756728864 it was commented that "Continue in trial mode" button will be removed, where it was used to continue in "trial mode"
- Toggle "Always on Top" cause some sort of issue and prevent button or some sort of clearing the console/data
- Im .gif file you can see that even after restart it show the same data as before, acting as cache

**Comment by freekmurze** [comment]
Do you still see the trial mode after rebooting your system?

**Comment by bolovdor** [comment]
Rebooting the system helped. When open after reboot, "Continue in trial mode" button/text was shown and I manage to click it. This result in resetting the 0/10 session count.

**Comment by AdrianMrn** [comment]
@bolovdor You need to make sure to quit the app completely. Simply pressing the `X` button won't quit it. Right clicking the tray icon and pressing `quit` should do the job!
