### ISSUE TITLE
Table output

### ISSUE THREAD

**Issue by edmarriner** [spatie/ray#3]
The project looks great! 

It might be nice to have the ability to output multi-dimension arrays as a table view.

```php
ray()->table([
   [
        'name' => 'John Doe',
        'age' => 25,
        'height' => 178
   ],
   [
        'name' => 'Zoe Smith',
        'age' => 46,
        'height' => 188
   ],
   [
        'name' => 'Jessica Jones',
        'age' => 21,
        'height' => 163
   ],
])
```

|Name|Age|Height|
|---|---|---|
|John Doe|25|178|
|Zoe Smith|46|188|
|Jessica Jones|21|163|

I would be happy to take a look at implementing something if you like the idea?
_Edit: I see the ray client is not itself open source so not sure I could implement it but would love to see it anyway! :)_ 

Ed

**Comment by freekmurze** [comment]
I like the idea, and will add it in the coming weeks.

**Comment by freekmurze** [comment]
Closing this, I'll keep it in mind, and might add it in the near future.
