### ISSUE TITLE
My ray app can not connect php project

### ISSUE THREAD

**Issue by webstar1027** [spatie/ray#310]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**

**Versions**
Ray version (you can see this in "About Ray"):

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version:
Laravel version (if applicable):

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 
 **Additional context**

**Comment by freekmurze** [comment]
Closing as there isn't enough info. Please open up a new issue and fill in the template.
