### ISSUE TITLE
Show Ray from anywhere command double press

### ISSUE THREAD

**Issue by S-R0** [spatie/ray#317]
**Describe the Bug**
When pressing the shortcut command to 'show Ray from anywhere', I have to press the shortcut twice for it to navigate to Ray. I have tested to see if this is an issue with Workspaces, but it seems to happen even when i'm not using them.

**Versions**
Ray - 1.12.0
MacOS - Big Sur 11.2

**Edit**
Noticed that when you have ray open and press your shortcut, the screen just goes black. If you press your shortcut again, it comes back. Also, if you press your shortcut once (so the screen is black), then navigate away from Ray and press your shortcut again, you only need to press it once to show.

**Comment by freekmurze** [comment]
We have made some changes around this in a new release that will be available shortly.

**Comment by S-R0** [comment]
Any idea on when this fix will be released? Still happening for me (Ray 1.14.7)
