### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by craigpotter** [spatie/ray#324]
I was going to open an PR but I don't know what you were trying to say.

https://github.com/spatie/ray/blob/master/docs/configuration/general.md 

It starts talking about Ruby then just cuts off with a typo! 

Maybe a Copy and paste error ?  

Thought I would make you aware as @freekmurze did it like 14 days ago ....

**Comment by freekmurze** [comment]
Whoops, removed that broken sentence
