### ISSUE TITLE
[macOS] Standard keyboard shortcut to hide window is `cmd + H` but Ray uses `cmd + W`

### ISSUE THREAD

**Issue by miclf** [spatie/ray#33]
Every macOS application I can think of uses `cmd + H` to let users hide the current window.
When wondering why this was not working in Ray, I discovered that it uses `cmd + W` instead.

This is not only surprising but also a bit ‘frightening’ when considering muscle memory, because `cmd + W` is the standard shortcut to close tabs or windows in macOS applications.

**Versions**
Ray version: 1.0.2
spatie/ray package version: 1.1.0

**Desktop:**
 - OS: macOS
 - Version 10.14

**Comment by AdrianMrn** [comment]
Fixed. This will be included in 1.0.5
