### ISSUE TITLE
The Ray app image doesn't have an icon - Ubuntu 20.04

### ISSUE THREAD

**Issue by nmirceac** [spatie/ray#334]
The Ray app image doesn't have an icon - Ubuntu 20.04

![image](https://user-images.githubusercontent.com/475346/109772797-1bec0500-7c07-11eb-84ed-e6e416638104.png)

**Comment by leopoletto** [comment]
I am facing the same issue. 
Tinkerwell as an example displays the icon, therefore I think it must be something related with Ray.

![image](https://user-images.githubusercontent.com/1036401/112687308-107ea900-8e56-11eb-8558-ac5b508c4f97.png)

The last one is Ray.

**Comment by leopoletto** [comment]
If it helps, now after I defined the Icon for the desktop file `/home/leonardo/.local/share/applications/Ray (1.14.6)` which has a type of `Text (application/x-desktop)` and was generated by [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) it is showing. 

![image](https://user-images.githubusercontent.com/1036401/112689724-6dc82980-8e59-11eb-941e-cf02060130be.png)

**Comment by AdrianMrn** [comment]
Hm, I thought I fixed this a couple of weeks ago. I'll take another look at it!

**Comment by cbaconnier** [comment]
Having the same issue I noticed the icon was located under a `0x0` directory but as far I understand how it works I would expect to be under `16x16`,  `24x24`  ...  `512x512` and `1024x1024`

```
▶ find ~/.local/share/icons -name "*_ray.*"
/home/clement/.local/share/icons/hicolor/0x0/apps/appimagekit_3d59809d6517c4c6b19da6a5280639ab_ray.png
```

For reference:

```
▶ ls ~/.local/share/icons/hicolor 
0x0  1024x1024  128x128  16x16  24x24  256x256  32x32  48x48  512x512  64x64  96x96  icon-theme.cache
```
I copied the icon with the correct resolution under each folder using this (then change the resolution and the folder name)

```
convert -resize 512x512 ~/.local/share/icons/hicolor/0x0/apps/appimagekit_3d59809d6517c4c6b19da6a5280639ab_ray.png ~/.local/share/icons/hicolor/512x512/apps/appimagekit_3d59809d6517c4c6b19da6a5280639ab_ray.png
```

And finally I have updated the icon cache with 

```
sudo update-icon-caches ~/.local/share/icons/hicolor
```

And now the icon is correctly displayed

**Comment by scrlkx** [comment]
@cbaconnier answer works nicely, but updates broken it again. Can we have a permanent solution?
