### ISSUE TITLE
Too few arguments to function Spatie\Ray\Origin\Origin

### ISSUE THREAD

**Issue by tjhunkin** [spatie/ray#337]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
Error when trying to use ray($args);
[2021-03-03 14:22:25] local.ERROR: Too few arguments to function Spatie\Ray\Origin\Origin::__construct(), 2 passed in K:\laragon\www\mykollection\vendor\spatie\laravel-ray\src\OriginFactory.php on line 30 and exactly 3 expected

**Versions**
Ray version 1.13.0.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.13.0
- spatie/laravel-ray package version (if applicable):  1.13.0

PHP version:
Laravel version (if applicable): PHP 7.4.7

**To Reproduce**
1. ray($args);
2. error 500 thrown

**Expected behavior**
Error 500 not to be thrown and ray should output to the desktop app running

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 
 **Additional context**

**Comment by patinthehat** [comment]
@tjhunkin @freekmurze I've submitted a [PR](https://github.com/spatie/laravel-ray/pull/170) to `spatie/laravel-ray` that should resolve this issue.

**Comment by tjhunkin** [comment]
Thanks

**Comment by tjhunkin** [comment]
Latest update fixed it
