### ISSUE TITLE
On Windows Ray -- there is no SERVERS icon to connect to remote server

### ISSUE THREAD

**Issue by markusyesloop** [spatie/ray#339]
https://spatie.be/docs/ray/v1/the-ray-desktop-app/discovering-the-ray-app#connecting-to-remote-server

**Comment by freekmurze** [comment]
We'll release this build in the next few hours. Fixing the last issues now.

**Comment by kaitwalla** [comment]
Any update on this? The last version I see on the site is 1.13, and unfortunately the app is nonfunctional for me without remote server access.

**Comment by AdrianMrn** [comment]
@kaitwalla We ran into some issues getting the app to build for all platforms, so we've delayed the release for a couple of days. 1.14.0 should be up on Monday at the latest :)
