### ISSUE TITLE
Ray app opens multiple times on Linux

### ISSUE THREAD

**Issue by freekmurze** [spatie/ray#34]
**Describe the bug**
1. If I double-click the AppImage file multiple times, it opens multiple instances (not sure if you can change that)

2. If I have one instance running, and press the close button, it stays open in the system tray. If I click the system tray icon, it opens a *new* instance with a second tray icon, while the existing instance is still running somewhere but is no longer reachable. Both try icons show/hide the new instance, unless I close the Ray window, at which point the tray icon(s) now spawn another new instance and icon.

By the way, all the subsequent instances don't receive Ray calls, presumably because the port is already in use by the first (lost) instance.

Also, this is happening with the "Show app" setting set to "On both task bar and system tray". I will try the other options and see if they behave better.

If I change the "Show app" setting to "On task bar", it's basically the same behaviour without the tray icon. If I close the app (either via the X or via Menu > Quit Ray) it still stays running in the background but there is no tray icon or task bar icon to get it back.

What I have just discovered is that Ctrl+Shift+L always seems to bring back the first instance (the lost one that receives all the ray calls)

**Versions**
Ray version: 1.0.2
spatie/ray package version: 1.0.0
spatie/laravel-ray package version (if applicable): 

**Desktop (please complete the following information):**
 - OS: Linux
 
 **Additional context**
Originally reported by Jess Archer

**Comment by freekmurze** [comment]
This might be related with the app sometimes having stray processes on Windows too.

**Comment by patinthehat** [comment]
I am unable to reproduce this bug on Ubuntu 20.04, XFCE window manager v4.14, and Ray app v1.0.2.  I can confirm that multiple processes can be started, and only the first process started receives the Ray messages (due to the port being used by the first instance, as mentioned).

**Comment by jessarcher** [comment]
@patinthehat if you close the window or quit from the menu, does the process exit?

And if not, are you able to get the first instance window back from the system tray or does it spawn a new instance?

**Comment by patinthehat** [comment]
@jessarcher The process exits when I quit from the menu.  Closing the window causes it to minimize back to the system tray and does not exit the process.  When I start multiple instances, I can access each instance as expected from the related system tray icon and no new instances are spawned.

**Comment by freekmurze** [comment]
This has been fixed in Ray 1.0.4

Just restart Ray to pull in updates.
