### ISSUE TITLE
HTML Layout issues for logs

### ISSUE THREAD

**Issue by bilfeldt** [spatie/ray#340]
**Describe the bug**
When Ray displays Laravel log entries that contains html the layout of the Ray app breaks - while it works if the same HTML is send manually using the `ray()` method.

**Versions**
- spatie/ray package version: 1.19.4
- spatie/laravel-ray package version (if applicable): 1.12.6

PHP version: 7.4.3
Laravel version: 8.27.0

**To Reproduce**
Sending HTML to ray manually works perfect:

```
ray(Http::get('http://example.com')->body());
```
<img width="1904" alt="Screenshot 2021-02-15 at 13 30 02" src="https://user-images.githubusercontent.com/30228807/107947103-34ff7f80-6f92-11eb-9310-5c91d62a07f7.png">

But logging the same html and sending logs to ray causes the layout to break:
```
Log::debug(Http::get('http://example.com')->body());
```

<img width="1904" alt="Screenshot 2021-02-15 at 13 30 17" src="https://user-images.githubusercontent.com/30228807/107947146-46e12280-6f92-11eb-927a-5c0859f50b13.png">

**Expected behavior**
The layout from normal log entries would be expected:

```
Log::debug('non-html-string')
```
<img width="1904" alt="Screenshot 2021-02-15 at 13 37 25" src="https://user-images.githubusercontent.com/30228807/107947656-f74f2680-6f92-11eb-8937-56c84950807c.png">

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.2.1
 
 **Additional context**
--

**Comment by AdrianMrn** [comment]
Thanks for the detailed report and reproducible example! A fix for this will be included in the upcoming 1.14.7 release.
