### ISSUE TITLE
Rate limit new events

### ISSUE THREAD

**Issue by jonorozcoc** [spatie/ray#343]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
When you have a loop with a lot of ray calls the interface becomes frozen or laggy. I think that happens due to the high speed sending events to Ray app

**Versions**
Ray version (you can see this in "About Ray"): 1.13.0

**To Reproduce**
1. Send 1000 events in a second

**Expected behavior**
Rate limit the amount of events to be displayed, add a delay in order to avoid freezing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Windows
 - Version [e.g. 22] 10
 
 **Additional context**

**Comment by patinthehat** [comment]
I can confirm that this issue exists when sending a large number of payloads to the Linux app, sometimes to the point of it becoming unusable.  It also results in a persistently high CPU usage once the payloads have been sent, even after they've all been displayed.

**Comment by jonorozcoc** [comment]
This also happens with a small amount of events but with each event has a huge payload aka classes with large property list

**Comment by patinthehat** [comment]
@jonorozcoc can you define "classes with a large property list" more specifically?  How many properties? What types _(strings, resources, etc.)_?

**Comment by jonorozcoc** [comment]
@patinthehat sure, can be applied with large array properties or instance properties. I think this is due to the expand collapse feature

For example I tested with a Laravel exception. Sending 100 events of this type affect the desktop app experience

**Comment by jonorozcoc** [comment]
@patinthehat at the end has to be the amount of data. because if I send a large amount of event with small payload has the same effect as sending a few events with huge payload

Something I noticed as you mentioned the app is more likely to freeze if the event type is more complex
