### ISSUE TITLE
Docs folder size

### ISSUE THREAD

**Issue by philipmclifton** [spatie/ray#352]
Hi, sorry to bother with what seams like such a minor point but...

The repository has 9mb of assets in the docs folder. Mostly images. 

I would love to keep ray in my production codebase (incase I deploy a ray()) but I'm deploying via Laravel Vapor and have a really strict file size limit. 

Ray becomes one of the biggest packages in my vendor folder.  

I'm trying to avoid having to ship with docker.

**Comment by patinthehat** [comment]
@philipmclifton I'll run `optipng` on the images to shrink them down and submit a PR with the compressed images *IF* there's no loss in quality; ultimately, it'll be up to @freekmurze whether or not to accept it. Stand by.

Side note: Couldn't you just remove the images folder before deploying?

**Comment by patinthehat** [comment]
@philipmclifton I was able to compress the images folder down to under 6 MB in my PR #353  - anything beyond that may require modifying the images more than I'm comfortable with without talking to Freek first.

**Comment by AdrianMrn** [comment]
Would https://github.com/spatie/ray/pull/354 cause any issues?

**Comment by philipmclifton** [comment]
> @philipmclifton I'll run `optipng` on the images to shrink them down and submit a PR with the compressed images _IF_ there's no loss in quality; ultimately, it'll be up to @freekmurze whether or not to accept it. Stand by.
> 
> Side note: Couldn't you just remove the images folder before deploying?

I don't know why I didn't think about that, I will just run a build command to ditch the assets if this isn't changed. 🤦

**Comment by freekmurze** [comment]
@philipmclifton Here's a semi related idea: if you're building assets on the server, let your build command delete `node_modules` too to save some disk space.

**Comment by philipmclifton** [comment]
Node modules gets nuked by default in Vapor's suggested build steps.

For anyone else wanting to achieve the same thing:

```
    build:
            - "COMPOSER_MIRROR_PATH_REPOS=1 composer install --no-dev"
            - "php artisan event:cache"
            - "yarn install --frozen-lockfile && yarn prod && rm -rf node_modules"
            - "rm -rf vendor/spatie/ray/docs"
```
