### ISSUE TITLE
ray 1.14.0.0 - open files with vscode-ssh does not work

### ISSUE THREAD

**Issue by camiant** [spatie/ray#357]
ray version 1.14.0.0

with vscode logged using ssh, when you click on filename, vscode tries to open another instance using filepath as it were on local pc. obviously it doesn't work. ray should instead search for that path in the already-opened instance of remotely connected vscode.

![2021-03-11 12_06_31-](https://user-images.githubusercontent.com/7567420/110778739-07d98080-8263-11eb-843e-3e331e9652dd.png)

thanks in advance for your support

**Comment by freekmurze** [comment]
You can solve this, but adding a Ray config file on your remote server. You an use this to translate the remote path to the local path.

https://spatie.be/docs/ray/v1/configuration/framework-agnostic-php
