### ISSUE TITLE
Windows requires SSH key for remote server when "Password" selected

### ISSUE THREAD

**Issue by kaitwalla** [spatie/ray#358]
**Describe the bug**
When trying to create a remote server in the Windows version, selecting "Password" as the authentication method does not work. The application still requires an SSH key file, though it does not use it. I do not have a default SSH key on this computer, so upon trying to connect to the server I got a "no file found" for the default location of the SSH key. This error persisted until I copied an actual SSH key (not one that would authenticate that server, but it did have to parse as real) into the default SSH key location.

**Versions**
Ray version (you can see this in "About Ray"): 1.14.0.0

**To Reproduce**
1. Create a remote server. Select "Password" for authentication
2. Enter your password, save the server.
3. Try to connect.

**Expected behavior**
The SSH connection does not attempt to use an SSH key when I select "Password."

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Windows
 - Version [e.g. 22] 1.14.0.0

**Comment by kaitwalla** [comment]
Also had the same issue on the Mac version.

**Comment by Omegatcu** [comment]
Still a problem in 1.14.5

**Comment by patinthehat** [comment]
This is an issue with the Linux App as of version `v1.14.7`.

**Comment by mateuszBedzinski** [comment]
Related error image here
![image](https://user-images.githubusercontent.com/49586747/113260322-6af08d00-92ce-11eb-8283-835fb4509056.png)

**Comment by mateuszBedzinski** [comment]
Related error image 
![image](https://user-images.githubusercontent.com/49586747/113261276-8dcf7100-92cf-11eb-9ede-ec43f14ad3d7.png)

**Comment by michaelslobodskih** [comment]
same problem in windows 1.14.7.0 version

**Comment by Omegatcu** [comment]
Just to make this case:
I know some will think this is not a big deal, just use a cert.
I get you from a security standpoint, but I do work on servers where I only get the username/password and the client doesn't want cert auth. In these cases I would really appreciate if we can get the possibility to use the password option.

I do understand that it might have a low priority, but I would really appreciate a fix for this.

**Comment by michaelslobodskih** [comment]
As far as i can see , ray is made with Electron js. For transfering data between client & app used post requests to internal ExpressJS web server. Ray is connecting to servers using ssh tunnel. So i cant understand why they can't fix this issue. If this issue will not be fixed , probably i will create my own free ray client :)

**Comment by kaitwalla** [comment]
@Omegatcu A workaround is putting ANY valid cert path before choosing "password." It doesn't need to be for that server, it just needs to be a valid certificate. It will look at it on connecting, but then use the password auth.

**Comment by Omegatcu** [comment]
> @Omegatcu A workaround is putting ANY valid cert path before choosing "password." It doesn't need to be for that server, it just needs to be a valid certificate. It will look at it on connecting, but then use the password auth.

Wow - I didn't know that.
Fix for me was copy "known_hosts" file and renaming it to "id_rsa" in ~/.ssh dir. - Done!

**Comment by phasotron** [comment]
> > @Omegatcu A workaround is putting ANY valid cert path before choosing "password." It doesn't need to be for that server, it just needs to be a valid certificate. It will look at it on connecting, but then use the password auth.
> 
> Wow - I didn't know that.
> Fix for me was copy "known_hosts" file and renaming it to "id_rsa" in ~/.ssh dir. - Done!

tnx

**Comment by AdrianMrn** [comment]
A fix for this will be included in the next release!
