### ISSUE TITLE
Display not on screen

### ISSUE THREAD

**Issue by savage-eagle** [spatie/ray#359]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
It is not possible to see Ray on screen after you plug the HDMI and move Rays outside the normal device display (1366x768) and removes the HDMI plug.

**Versions**
Latest version v1.40

- spatie/ray package version: 1.17.3
- spatie/laravel-ray package version (if applicable): 1.11.2

PHP version: 7.4.13
Laravel version (if applicable): 8.3

**To Reproduce**
1. Plug the HDMI (to increment the screen size to 1920x1080)
2. Move the Ray outside the normal display area
3. Close Ray.
4. Remove the HDMI.
5. See error

**Expected behavior**
It should display Ray on some size on normal display as well and not stick to the previous area.

**Screenshots**
Ray is opened but can't see in the image
![image](https://user-images.githubusercontent.com/72709807/110859931-ee542b00-829a-11eb-8718-cb027e3c8463.png)

Trying minimize the ray. You can see it is outside the display.
![image](https://user-images.githubusercontent.com/72709807/110859994-0035ce00-829b-11eb-928e-228f37fe46b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 18363
 - Notebook normal display (1366x768)
 
 **Additional context**
-

**Comment by AdrianMrn** [comment]
A fix for ths will be included in the next release of Ray, likely 1.14.1 🙂

**Comment by savage-eagle** [comment]
The problem still persists.

Don't know how to reproduce. Sometimes it resize to screen and sometimes it goes outside the screen.

**Comment by AdrianMrn** [comment]
Ray now checks whether it's inside of the viewport of any screens whenever your monitor setup changes, and adjusts itself accordingly.

If you can figure out how to reproduce this bug, please open a new issue with the updated information & the reproduction steps.
