### ISSUE TITLE
Trial mode status is not clear

### ISSUE THREAD

**Issue by Polfo** [spatie/ray#36]
**Describe the bug**
When running trial mode and nothing appears in the app, it is not clear if this is due to the 10 log items limit.

**Versions**
Ray version: 1.0.2
spatie/ray version: 1.1.3
spatie/laravel-ray: 1.1.0
Laravel version: 8.21.0

**To Reproduce**
Run my php code with ray() statements
Look at ray app window.
Window displays:
Trial mode allows for up to 10 lig items. Learn more...
Click 'Learn more...'
Click 'continue in trial mode' 
Nothing happens while running php code with ray() statements.
It is not clear if this is due to the 10 log items limit.

**Expected behavior**
Debug information appears or app tells me that the trial license is over its 10 log items limit, then I am not proposed to continue in trial mode.

I could see something after auto upgrading the app from 1.0.1 to 1.0.2 though, so I suspect nothing appears because the 10 log items limit has been reached, but how do I know for shure this is the reason Freek?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2004 build 19041.685

**Comment by freekmurze** [comment]
I think we should add an extra message when we hit this limit @AdrianMrn

**Comment by AdrianMrn** [comment]
@freekmurze We're already showing the license overlay as a blocking modal when users run into the log limit. I'll add a counter to the notification bar while in trial mode.

**Comment by AdrianMrn** [comment]
See bottom bar in the screenshot

![image](https://user-images.githubusercontent.com/12762044/104001080-6c169000-519f-11eb-9d10-cc8a3a6ee67e.png)

**Comment by slaFFik** [comment]
@AdrianMrn But this popup is NOT blocking. We can freely close it using  "Continue in trial mode" link, and after that no indication that the data won't be received/processed/displayed.

**Comment by AdrianMrn** [comment]
Right, thanks for the heads up! I'll remove the `Continue in trial mode` button when the application has received 10 logs.
