### ISSUE TITLE
Ray crash after output of large array

### ISSUE THREAD

**Issue by Trompetenhut** [spatie/ray#360]
**Describe the bug**
If you output a large array, for example Wordpress WP_Query, the APP is not responding anymore. You cannot clear the history or something else. If I restart the app, the output is still there.

**Versions**
1.14.0.0

**To Reproduce**
1. Output large arrays

**Expected behavior**
I can still use Ray

**Screenshots**
![image](https://user-images.githubusercontent.com/15231733/110905282-86d5c400-830a-11eb-8000-9ec782c75937.png)

**Desktop (please complete the following information):**
 - Windows 10

**Comment by adevade** [comment]
I don't think you're restarting the app, but just closing the window. The app is probably still running in the taskbar. Try selecting *Menu > Quit Ray* and then starting it again.

But I can confirm. The app does get reeeeeeeally slow when there's a lot of data loaded in the window. I usually have to restart the app multiple times a day.

**Comment by AdrianMrn** [comment]
We're continuing work on performance improvements for the app, this issue is somewhat related (or should be solved by the same fix) to https://github.com/spatie/ray/issues/325, so I'm closing this one. I'll update once I've found a solid solution.
