### ISSUE TITLE
Cannot investigate bug in trial mode

### ISSUE THREAD

**Issue by Polfo** [spatie/ray#37]
**Describe the bug**
I want to evaluate the product but run into #18.
I'd like to reproduce and provide more info but run into #36

**Expected behaviour**
Provide a way to get out of this deadlock. 

**Note**
I license purchase is ongoing for me, but that takes time.

**Versions**
Ray version: 1.0.2
spatie/ray version: 1.1.3
spatie/laravel-ray: 1.1.0
Laravel version: 8.21.0
OS: Windows 10 version 2004 build 19041.685

**Comment by freekmurze** [comment]
Without a license, you can send 10 items per session. Just restart your app to be able to use it again.

**Comment by Polfo** [comment]
OK, dank je Freek. It did not seem to work that way, but now I have a license key, I cannot test that anymore ;-)
#36 will make that more clear anyway.

**Comment by AdrianMrn** [comment]
Thanks for your purchase! 😊
