### ISSUE TITLE
Update window says latest version first (Mac)

### ISSUE THREAD

**Issue by nessor** [spatie/ray#372]
**Describe the bug**
When you check the app for an update (on the Mac), the first window that appears is that you already have the latest version installed. If you confirm this, a window appears that an update has been found.

**Versions**
Ray version: 1.14.0

**To Reproduce**
1. An update must be available
2. Ray > Check for updates...
3. confirm first window

**Expected behavior**
Immediately indicate that there is an update.

**Screenshots**
<img width="358" alt="image" src="https://user-images.githubusercontent.com/3463261/111339134-cfc5a980-8677-11eb-9749-abf7767edd03.png">

<img width="340" alt="image" src="https://user-images.githubusercontent.com/3463261/111339184-d94f1180-8677-11eb-9435-28699b5af03d.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.2.3

**Comment by AdrianMrn** [comment]
Thanks for the report, I'll have a look into this. If you press `restart`, does the app update and restart, and are you on the latest version (1.14.3)?

**Comment by nessor** [comment]
Hi @AdrianMrn

thanks for your reply. I'm pressing on `restart` but the app just closes and does not restart again. When I open it again manually, the old version (1.14.0) is still installed and I am asked again if I want to update.

No. I'm not at the latest version. Otherwise the update window would not appear 😅

**Comment by AdrianMrn** [comment]
All right, we're also seeing this error in isolated cases, and finding it very difficult to debug, it seems to be happening on every newly released update :/

As a temp fix, you can either press `later` on the update dialog, or download the latest version here: https://spatie.be/products/ray/download/macos/latest

**Comment by nessor** [comment]
Okay. I updated now the version manually to 1.14.3. Not the "You are running the latest version" window does not appear at all when I'm checking update with Ray > Check for updates... 😄

**Comment by AdrianMrn** [comment]
@nessor Thanks for the report, both the update issue and the popup have been fixed in 1.14.4 (releasing now, should be available in about 10 minutes).
