### ISSUE TITLE
Ray wont open after last update.

### ISSUE THREAD

**Issue by OurBG** [spatie/ray#373]
**Describe the bug**
After the last update that happened today for me (March 16th 2021) Ray stopped opening. It starts 4 processes in my task manager called Ray, but won't open.

**Tried**
Uninstall and install again;
Restarting the PC;

**Versions**
Ray version (you can see this in "About Ray"): Not sure, the latest one that installed itself today.

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.12.2
- spatie/laravel-ray package version (if applicable): 1.14.0

PHP version:
Laravel version:

**To Reproduce**
1. Update the app
2. Start the app
 
**Expected behavior**
The app starting as usual.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]: Windows 10
 
 **Additional context**

**Comment by AdrianMrn** [comment]
Hi @OurBG, I've just released a fix that should hopefully address your issue: https://github.com/spatie/ray/issues/371

Could you please reinstall the app from here, and see if it works? https://spatie.be/products/ray/download/windows/latest

**Comment by OurBG** [comment]
Perfect! All working now!
