### ISSUE TITLE
When ray is docked with another application when you swipe to a different desktop it swipes back automatically to where ever ray is

### ISSUE THREAD

**Issue by midnite81** [spatie/ray#376]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

✅  Couldn't see this issue in issues or discussions.

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**

When you have a couple of windows docked into a desktop on a mac, when you swipe left or right to another desktop it automatically swipes back to where ray is. If ray is not pinned to a desktop it works as expected. 

**Versions**
Ray version (you can see this in "About Ray"):

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.21.2
- spatie/laravel-ray package version (if applicable): 1.17.1   

PHP version:
Laravel version (if applicable): 7.4

**To Reproduce**
1. Open Chrome and Ray
2. 'Maximize' chrome to be on it's own desktop
3. 'Maximize' ray but group it to the chrome desktop
4. Swipe to a different desktop
5. Watch it scroll back to where ray is. 

**Expected behavior**
When swiping to a different desktop, it should stay on that desktop and not scroll back to the desktop the ray is on.

**Screenshots**
Video of issue: https://user-images.githubusercontent.com/254850/111597205-dbbf8180-87c5-11eb-9540-edaf9fb79ad8.mov

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 22] 11.2.3

 **Additional context**

**Comment by AdrianMrn** [comment]
I can reproduce this and I'm working on a fix.

**Comment by AdrianMrn** [comment]
I'm releasing 1.14.5 which should fix this issue. Let me know if you run into any other issues or have any suggestions how we could make Ray more fun to use!

**Comment by midnite81** [comment]
Thank you. I have installed 1.14.5 which seems to have resolved the issue. Many thanks.
