### ISSUE TITLE
syntax error, unexpected '->' (T_OBJECT_OPERATOR)

### ISSUE THREAD

**Issue by jkque** [spatie/ray#377]
**Describe the bug**
Just starting with ray but it spams error log in my end. 
And FYI I did not use the ray helper yet.
```
syntax error, unexpected '->' (T_OBJECT_OPERATOR)
ExceptionHandler.php:46
```

It came from ExceptionHandler class of Collision Package

**Versions**
Ray version: 1.14.4.0

You can use `composer show` to get the version numbers of:
- spatie/laravel-ray package version: 1.17

PHP version: 8.0.0
Laravel version: 8.33.1 using Sail and WSL 2

**Expected behavior**
It should not spam an error log that user did not intentionally debugs.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - 21H1

**Comment by freekmurze** [comment]
By default, all exceptions will get sent to Ray automatically. Take a look at the configuration section in our docs to learn how to turn that off.

**Comment by jkque** [comment]
Ohh this is the problem of people not reading docs 😂

Sorry about that. Thanks @freekmurze 

I ❤ Ray

**Comment by jkque** [comment]
@freekmurze 

updated the config file but no luck it still spamming the log 

`'send_exceptions_to_ray' => env('SEND_EXCEPTIONS_TO_RAY', false),`

**Comment by freekmurze** [comment]
I can't seem to reproduce this, could you create a minimal app in which you recreate the issue?

**Comment by jkque** [comment]
I can add you to the repo, is that okay ?

**Comment by freekmurze** [comment]
No, I'd rather you creating a new minimal public app, than working in an existing app that I don't know (and where there could be many unrelated things causing havoc)

**Comment by jkque** [comment]
Cool, will replicate my repo to minimal public app. 

Thanks buddy.

**Comment by jkque** [comment]
can't replicate it to a fresh laravel app :( 

But the log says it came from the Collision Package I stated above.

It annoys me cause my app is perfectly running but an exception is always throwing.

Configuring the ray.php does nothing
