### ISSUE TITLE
Ignoring vars in ray.php

### ISSUE THREAD

**Issue by rst630** [spatie/ray#382]
https://github.com/rst630/ray-test

![image](https://user-images.githubusercontent.com/644549/111904344-1270f280-8a79-11eb-809a-10b1a477c3d0.png)

**Comment by freekmurze** [comment]
Could you please use the issue template, so we know your version numbers? Thanks!

**Comment by rst630** [comment]
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )

other you can see in test repository

**Comment by rst630** [comment]
ray is 1.14.5

**Comment by 4nik3t** [comment]
@rst630 Did you find a solution for this?

**Comment by 4nik3t** [comment]
@freekmurze I can confirm this happening even in the latest build

**Comment by rst630** [comment]
no, they won't resolve this. I even wrote to email, but they just close this issue. 
Very good position "Buy our software & make bug reports only with template" - no thanks.
