### ISSUE TITLE
Latest ray version 1.14.6, nothing gets logged to the app

### ISSUE THREAD

**Issue by rkmaier** [spatie/ray#404]
**Describe the bug**
No debug is logged inside the windows app, previous version seemed to work just fine 

**Versions**
Ray Windows 1.14.6
ray/spatie 1.21.2

PHP version:
7.4.16

**To Reproduce**
1. Install latest ray version
2. Log something using the ray command
3. Nothing is logged inside the ray app

**Expected behavior**
Logs should show up in the ray app

**Desktop (please complete the following information):**
 - Windows
 - Version  20H2 - 19042.867
 
 **Additional context**
Using ray with docker v20.10.5

**Comment by patinthehat** [comment]
@rkmaier Have you followed the documentation [on using Ray with docker](https://spatie.be/docs/ray/v1/environment-specific-configuration/docker)?

**Comment by rkmaier** [comment]
> @rkmaier Have you followed the documentation [on using Ray with docker](https://spatie.be/docs/ray/v1/environment-specific-configuration/docker)?

@patinthehat 
yes it was working with the previous version. Where can I download the previous version to confirm my issues ?

**Comment by patinthehat** [comment]
> Where can I download the previous version to confirm my issues?

I'm not sure on that one.  You'd have to ask @freekmurze.

**Comment by rkmaier** [comment]
> > Where can I download the previous version to confirm my issues?
> 
> I'm not sure on that one. You'd have to ask @freekmurze.
> 
> In the mean time: are you able to create a test php script to see if you're able to communicate with the Ray app outside of your project?

The same issue, outside my app too.   However it does work  when not using docker

**Comment by rkmaier** [comment]
@freekmurze can I download the older versions somewhere  ?

**Comment by zynth17** [comment]
i got the same problem
even after 1.14.7 it does not work on my local
it doesn't log anything

**Comment by rkmaier** [comment]
> i got the same problem
> even after 1.14.7 it does not work on my local
> it doesn't log anything

Same here, even after 1.14.7

**Comment by zynth17** [comment]
and btw i didnt use docker and it does not work also

**Comment by zynth17** [comment]
any update on this?

**Comment by DamianKausitz** [comment]
Same issue. Uninstalled latest version.
Installed 1.24.0 --- does not work, 
Automatically downloaded and installed 1.14.7.0.
PHP v7.4.10 from XAMPP, 
No communication between php files and Ray console. 
McAfee firewall -- ports are open.

**Comment by mariuscirstea** [comment]
Same issue.
Version 1.14.7 (1.14.7)
MacOs Catalina
Local dev with Valet

**Comment by freekmurze** [comment]
I'll inestigate this soon. Could you try if it works using an older version of the PHP package?

**Comment by mariuscirstea** [comment]
It is now working with new laravel project but with old one doesn't. I should investigate forward...

**Comment by mariuscirstea** [comment]
Some collegue changed config and set 'host' to docker. I changet back to localhost and all it is working now. Sorry for my hasty post!
