### ISSUE TITLE
Multiline text shows on a single line

### ISSUE THREAD

**Issue by shalvah** [spatie/ray#417]
**Describe the bug**
Multiline text shows on a single line.

**Versions**
Ray version (you can see this in "About Ray"): 1.14.7.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.21.2

PHP version: 7.4

**To Reproduce**
1. Dump any text with newlines (`\n` or `\r\n`)

**Expected behavior**
Text should be properly displayed

**Screenshots**
Text shows on a single line.

![image](https://user-images.githubusercontent.com/14361073/114454041-12749600-9bd2-11eb-864b-10cc89981cac.png)

When I dump to console (with Symfony `dump()`), it shows correctly:

```
"""
<?php\n
\n
    public function show(BadWord $badword)\n
    {\n
        return $badword;\n
    }\n
"""
```
**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by AdrianMrn** [comment]
The standard `ray();` log will not attempt to display HTML anymore, unless a Symfony dump script is present in the payload.


`ray('hi<br />\n \r\n foobar');` will display
![image](https://user-images.githubusercontent.com/12762044/125762118-552a5825-4c72-4886-869f-8eadd6847e65.png)

**Comment by deligoez** [comment]
I just needed the same behavior and the answer is `text()` function of Ray

```php
ray()->text($contents)
```
