### ISSUE TITLE
A new version (1.14.17) has been downloaded. Restart Ray to apply the updates. 

### ISSUE THREAD

**Issue by smccoy78** [spatie/ray#419]
**Describe the bug**
Every time I open Ray, I get a popup that says "A new version (1.14.7) has been downloaded. Restart Ray to apply the updates." I hit the restart button and when Ray opens back up I get the same popup again.

**Versions**
Ray version (you can see this in "About Ray"): 1.14.3

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.21.2
- spatie/laravel-ray package version (if applicable):  1.14.0

PHP version: 7.4
Laravel version (if applicable): 8.31.0

**To Reproduce**
1. Open Ray
2. Click on Restart button in popup

**Expected behavior**
Application update to new version

**Screenshots**
![Screen Shot 2021-04-13 at 8 29 29 AM](https://user-images.githubusercontent.com/2486409/114552331-7b8bf600-9c32-11eb-95af-7f609f98dfb2.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.2.3

**Comment by freekmurze** [comment]
That's strange. 

It's by no means, meant as a permanent fix, but you could download the latest version from https://myray.app. That will probably fix you having that dialog.

**Comment by smccoy78** [comment]
Thank you for the quick reply @freekmurze. That is what I ended up doing, I just figured I would let someone know just in case it wasn't some sort of fluke on my end. I appreciate everything you all do!

**Comment by AdrianMrn** [comment]
This was an issue with 1.14.3 or so, and has since been resolved. Thanks for the report, and let us know if you encounter any other issues!
