### ISSUE TITLE
Link broken in https://github.com/spatie/ray/blob/master/docs/introduction.md

### ISSUE THREAD

**Issue by ConorAAG** [spatie/ray#42]
The link to "[Configure Ray](https://github.com/spatie/ray/blob/master/docs/ray/v1/getting-started/configuring-ray) if needed" under the [Getting Started](https://github.com/spatie/ray/blob/master/docs/introduction.md#getting-started) section returns a 404

**Comment by freekmurze** [comment]
You should view the docs here: https://spatie.be/docs/ray/v1/introduction
