### ISSUE TITLE
Calling showQueries() fails

### ISSUE THREAD

**Issue by stefgosselin** [spatie/ray#427]
Called as follows:

```
    public function tearDown(): void
    {
        parent::tearDown();
        ray()->showQueries();
        Product::destroy($this->products);
    }

```

**Return:** 

/usr/local/bin/php /Users/stephanegosselin/dev/some-api/vendor/phpunit/phpunit/phpunit --configuration /Users/stephanegosselin/dev/some-api/phpunit.xml --filter "/(Tests\\Unit\\Routes\\PeoductsTest::testGetProductListingsAuthenticatedShouldReturnProductList)( .*)?$/" --test-suffix FavoritesTest.php /Users/stephanegosselin/dev/some-api/tests/Unit/Routes --teamcity
Testing started at 3:15 p.m. ...
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

BadMethodCallException : Method showQueries does not exist.
 /Users/stephanegosselin/dev/some-api/vendor/spatie/macroable/src/Macroable.php:66
 /Users/stephanegosselin/dev/some-api/tests/Unit/Routes/FavoritesTest.php:55

**Comment by freekmurze** [comment]
Did you install spatie/laravel-ray?

**Comment by stefgosselin** [comment]
Yes.  I have not retried the function call but it is most probably an issue
on my end. I was calling in the context of a test-case, which was missing
the call createApllication().

So.. no bootstrap, no ray().  No lots of other things too.

Thanks for the quick response,  will try again tomorrow and if all is well
will update the ticket with above details.

👍 have an awesome day.

Stef

**Comment by molnarjg** [comment]
I have the same error, calling `ray()->showQueries();`.
Like 2 versions before it worked fine in the same places.

**Comment by molnarjg** [comment]
Hi,

Any updates re this issue?

Cheers.

**Comment by snapey** [comment]
@molnarjg `composer require spatie/laravel-ray`  NOT `spatie/ray`
