### ISSUE TITLE
Manjaro: reporting a bug from Ray sometimes results in a error dialog box

### ISSUE THREAD

**Issue by bartbrinkman** [spatie/ray#433]
**Describe the bug**
When reporting a bug from Ray, after a few seconds an alert box pops saying Firefox is already running and it should be first closed. 

**Versions**
Ray version (you can see this in "About Ray"): 1.14.7

**To Reproduce**
1. Go to Help menu
2. Click on 'Report a Bug...'
3. After a few seconds, see error (also see screenshot)

It doesn't not always reproduce, but closing Firefox while Ray is running seems to be the most straight-forward method to trigger the issue.

**Expected behavior**
No error, open up the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/8309358/115409485-161ba480-a1f2-11eb-926a-8920bd0acc2b.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Gnome
 - Version: latest rolling, Gnome 40, Firefox 87

**Comment by AdrianMrn** [comment]
I can't seem to reproduce this, it seems like a very isolated issue. Let me know if it is still bothering you and I'll take a closer look at it.
