### ISSUE TITLE
unable to install laravel ray due to faker version

### ISSUE THREAD

**Issue by ThinkDevStudios** [spatie/ray#446]
**Describe the bug**
Unable to install laravel ray due to incompatibility with faker version

**Versions**
Ray version (you can see this in "About Ray"):

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.22.1
- spatie/laravel-ray package version (if applicable): 1.17.4

PHP version:
Laravel 8 PHP 7.4.2

**To Reproduce**
when requiring via composer, installation fails due to incompatibility with faker

**Desktop (please complete the following information):**
MacOS 10.15.2
 
 **Additional context**
  Problem 1
    - fzaninotto/faker v1.9.2 conflicts with fakerphp/faker v1.14.1.
    - fzaninotto/faker v1.9.2 conflicts with fakerphp/faker v1.14.0.
    - fzaninotto/faker v1.9.2 conflicts with fakerphp/faker v1.13.0.
    - fzaninotto/faker v1.9.2 conflicts with fakerphp/faker 1.15.x-dev.
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - Root composer.json requires fakerphp/faker ^1.13 -> satisfiable by fakerphp/faker[v1.13.0, v1.14.0, v1.14.1, 1.15.x-dev (alias of dev-main)].

**Comment by freekmurze** [comment]
Use the phpfaker package in your composer.json instead of the fzaninotto one
