### ISSUE TITLE
Keep Ray on top missing for Windows

### ISSUE THREAD

**Issue by Morgy93** [spatie/ray#448]
**Describe the bug**
It seems that https://spatie.be/docs/ray/v1/the-ray-desktop-app/discovering-the-ray-app#keep-ray-on-top is missing for the Windows app.

It clearly seems like a bug to me if you advertise a feature (without mentioning exceptions) and not having the functionality available.

I have no option to disable the window being always on top which can be frustrating.

**Versions**
Ray version (you can see this in "About Ray"): 1.14.7.0

**Expected behavior**
I'd expect the toggle feature on the view menu like shown in the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/7961978/117016047-9a8e1d00-acf2-11eb-8c8b-62c5a0c5bc66.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Windows 10 20H2 (Build 19042.928)

**Comment by AdrianMrn** [comment]
Hey @Morgy93, you can toggle the float-on-top using the second button from the right in the menubar (screenshot is on Mac, but it should be the same on Windows).

![image](https://user-images.githubusercontent.com/12762044/117113953-7df1f380-ad8b-11eb-8ad2-358ad740e462.png)

Great idea to also have it in the View menu, we'll consider adding this!

**Comment by Morgy93** [comment]
Holy... I'd never ever thought that the icon would be responsible for that.

@AdrianMrn You should also update the docs, because then it's not well documented + other screenshots show way different functionality / ui elements. 

![image](https://user-images.githubusercontent.com/7961978/117114392-17210a00-ad8c-11eb-9631-470861af0717.png)

Thanks for clarification anyway!

**Comment by AdrianMrn** [comment]
Yeah, the app went through some UI changes since those were made 😅

I've written it down and will improve this!
