### ISSUE TITLE
Feature request - limit use in loops

### ISSUE THREAD

**Issue by tarraq** [spatie/ray#456]
Hi there.

I would really love to have a limiter for when Ray is used in loops.
For instance:
`for($i=0;$i<10000;$i++) {
ray($someVariable)->take(10);
}`
would only take the first ten items in the loop and avoid spamming the desktop app with 10 items. 
Would make debugging loops much nicer.

**Comment by freekmurze** [comment]
I like the idea, and we could implement this in the package.

I'm thinking of an API like this:

```
Ray::rateLimit()->max(10); //after 10 messages, a message saying rate limiting is enable is disabled.
Ray::rateLimit()->perSecond(10) // only 10 per second are allowed
Ray::rateLimit()->clear(); // revert to as many items as you want again
```

I would accept a PR including tests that adds this to the package.

**Comment by tarraq** [comment]
Sounds good!

**Comment by freekmurze** [comment]
The rate limiter has been released.
