### ISSUE TITLE
Linux: "About Ray" Menu Item doesn't work in App

### ISSUE THREAD

**Issue by patinthehat** [spatie/ray#46]
_If this should be filed in a different repository (it's not specifically related to the `spatie/ray` package) please direct me to the correct location._

In the linux version of the Ray app, clicking the "Menu->About Ray" menu item does not do anything.

Versions:
- Ray app: 1.0.3

1. Open the Ray app
2. Click the "Menu" menu item
3. Click the "About Ray" menu item
4. Nothing happens

Expected behavior:
- The expected behavior is the display of version information for the app, such as in a dialog.

Other Information:
 - OS: Ubuntu 20.04

**Comment by pascalchevrel** [comment]
Confirmed on Ubuntu 20.10

**Comment by ClementN** [comment]
Confirmed in Ray App: 1.0.8

**Comment by AdrianMrn** [comment]
I'll have a look at this this week.

**Comment by AdrianMrn** [comment]
This should be fixed in 1.2.2 (will release later today). Please let me know if it still doesn't work!

**Comment by pascalchevrel** [comment]
This is not fixed in 1.2.2, did you mean maybe an upcoming 1.2.3 coming later today?

**Comment by AdrianMrn** [comment]
Yup!
