### ISSUE TITLE
Long Messages are trimmed

### ISSUE THREAD

**Issue by developman-akl** [spatie/ray#461]
**Describe the bug**
Long Messages are trimmed.

**Versions**
- Ray: 1.14.7.0
- spatie/ray package version: 1.22.1
- spatie/laravel-ray package version (if applicable):  1.18.0

**To Reproduce**
1. Get anything shown in Ray where the **Message** is longer than the window with.

**Expected behavior**
Wrap the Message text into multiple lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/48017129/120057226-91942f80-c095-11eb-8316-94a8eb113d8b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version [e.g. 22] 20H2

**Comment by AdrianMrn** [comment]
A fix for this will be included in the next release!

**Comment by quantumwebco** [comment]
I have a similar issue where strings aren't truncated but also aren't wrapped so just go off the edge of the screen. Shall I open a new issue?
