### ISSUE TITLE
Online doc goes to 404

### ISSUE THREAD

**Issue by lesaff** [spatie/ray#462]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
The link to Ray's documentation goes to 404

https://user-images.githubusercontent.com/1151181/120229059-bf5aaf00-c222-11eb-9768-ec9f0ac6cf7d.mp4

**Comment by freekmurze** [comment]
Thanks for reporting. We've fixed this.
