### ISSUE TITLE
Limit sending payloads in loops

### ISSUE THREAD

**Issue by patinthehat** [spatie/ray#463]
@freekmurze I've created a `limit()` method with the idea that it can be used to limit the number of payloads sent when in a loop (related to #457).  It works in the same way that `count()` works _(based on the file/line number the method is called from)_.  This allows it to be limited within a loop for debugging without having limits everywhere.

Would you accept a PR that adds this method/feature?

```php
for($i = 1; $i <= 10; $i++) {
    ray()->limit(5)->text("A counter: $i"); // counts to 5
    ray()->limit(2)->text("B counter: $i"); // counts to 2 
}
```

![image](https://user-images.githubusercontent.com/5508707/120250231-5dfb0600-c24b-11eb-826e-84b6b9140679.png)

_Originally posted by @patinthehat in https://github.com/spatie/ray/issues/457#issuecomment-851513326_

**Comment by freekmurze** [comment]
Sound good! Send a PR for that. It might be good to inform the user that rate limiting has been triggered. Let's also display a message in that case. We could add a method `sendRateLimitingActive()` to the `Ray` class that your `limit` and @Nielsvanpach's rate limiting could call.

Closing this now, as I'm sure you'll send a PR for this soon 🙂
