### ISSUE TITLE
Adding a when() method

### ISSUE THREAD

**Issue by patinthehat** [spatie/ray#470]
Hey @freekmurze - would you accept a PR for a `when()` method? 

The idea for this method is related to working within loops _(although it has use cases beyond loops)_ - it allows for more dynamic debugging of large arrays, making the developer experience more pleasant.

Here's my first attempt at the API for `when()`:

```php
for($i = 0; $i < 7; $i++) {
    ray()->when($i % 2 === 0, fn($ray) => $ray->text("even value: $i"));    
}
```

![image](https://user-images.githubusercontent.com/5508707/120665781-14ccd100-c45a-11eb-9e1a-b42ccab59875.png)

or a more complex fluent call:

```php
for($i = 0; $i < 6; $i++) {
    ray()->text("value $i")
        ->when($i % 2 === 0, fn($ray) => $ray->small()->blue())
        ->when($i === 1, fn($ray) => $ray->text('one'))
        ->when($i === 5, fn($ray) => $ray->html('<strong>five</strong>'))
        ->hide();
}
```

![image](https://user-images.githubusercontent.com/5508707/120666877-f2878300-c45a-11eb-990f-db594f0b9ef8.png)

I could also do something like the following to keep the API a bit more simple if you prefer it:

```php
for($i = 0; $i < 10; $i++) {
    ray()->when($i > 5)->text("value: $i");
}
```

Thoughts?

**Comment by freekmurze** [comment]
Thanks for this idea.

I'm thinking the functionality is very close to if
https://spatie.be/docs/ray/v1/usage/framework-agnostic-php-project#conditionally-showing-items

Would that already work in the use cases mentioned above?

**Comment by patinthehat** [comment]
I'm not sure that it would, because those methods send payloads first and then send another payload to remove them if the conditional is met. 

`when()` only sends payloads if the conditional is met, which is important when working with large loops due to the lag issues with large numbers of payloads being sent to Ray.  I also feel that it provides more options when debugging loop, such as easily changing the color based on a conditional.

Without it, to conditionally change the color, I'd have to do something like:

```php
for($i = 0; $I < 10; $i++) {
    $ray = ray()->text("value: $i");

    if ($i > 5) {
        $ray->blue();
    }
}
```

I feel that a more fluent approach provides a more pleasant experience for the developer while providing code that's easier to read and reason about.

**Comment by freekmurze** [comment]
Thanks for explaining. If the code to achieve this is simple enough, I'd accept a PR that adds this to the package. 👍

**Comment by freekmurze** [comment]
Closing this for now as I'm sure a PR will come in soon 🙂
