### ISSUE TITLE
Ray Mac client recieves messages; Windows does not

### ISSUE THREAD

**Issue by kaitwalla** [spatie/ray#474]
**Describe the bug**
I have a Laravel app running under WSL on my Windows machine. I have Ray set up on both my Mac and the Windows machine (the Ray client is running on Windows, not the WSL instance). On both machines, I can connect to the remote server using the connect button. On the Mac, I can see the messages being received. When I connect the Windows machine, though it says it is connected, it does not receive any messages despite doing the same actions that caused the messages to show up on the Mac.

**Versions**
PC: 1.14.7.0
Mac: 1.14.7

- spatie/ray package version: 1.26.0
- spatie/laravel-ray package version (if applicable): 1.17

PHP version: 8.0
Laravel version (if applicable): 8.40.0

**Desktop (please complete the following information):**
 - OS: MacOS 11.4; Windows 10 21H1

**Comment by AdrianMrn** [comment]
@kaitwalla Can you still reproduce this bug? If so, please share the steps with me and I'll take a look!
