### ISSUE TITLE
Windows 10 - can't edit server details without reopening the app

### ISSUE THREAD

**Issue by vyskoczilova** [spatie/ray#480]
**Describe the bug**

If I can edit the server setting just once if I want to refine it I can't click into the input fields and I need to close & reopen the app.

**Versions**
Ray version (you can see this in "About Ray"): 1.15.0.0

**Expected behavior**
1. Be able to re-edit added server details

**Screenshots**
https://www.loom.com/share/549152c6e354474ca61b25853c146abc

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO
 - Version: 21H1(build 19043.1052)

**Comment by AdrianMrn** [comment]
A fix for this will be included in the next release!
