### ISSUE TITLE
mailable chain another mailable

### ISSUE THREAD

**Issue by lloricode** [spatie/ray#483]
**Describe the bug**
when try
```php
ray()->mailable(new ClassOne($this))
     ->mailable(new ClassTwo($this));
```
only result of `ClassTwo` will appear on ray app

**Versions**
Ray version (you can see this in "About Ray"): 1.15.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.27.1
- spatie/laravel-ray package version (if applicable): 1.22.0

PHP version:
Laravel version (if applicable): 8.48.1

**To Reproduce**
dispatch mail using `ray()->mailable()` in chain call

**Expected behavior**
this must be same result in none chaining call, like sample below
```php
ray()->mailable(new ClassOne($this));
ray()->mailable(new ClassTwo($this));
```

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]: Linuxmint
 - Version [e.g. 22] 20.1

**Comment by Nielsvanpach** [comment]
You should use 

```php
ray()->mailable(new ClassOne($this));
ray()->mailable(new ClassTwo($this));
```

In the meantime, I'll look into allowing multiple mailable arguments

**Comment by lloricode** [comment]
> You should use
> 
> ```
> ray()->mailable(new ClassOne($this));
> ray()->mailable(new ClassTwo($this));
> ```
> 
> In the meantime, I'll look into allowing multiple mailable arguments

yes ill use that way, I just notice this and maybe it could help

**Comment by lloricode** [comment]
I did not notice, i crated issue in different repository,

anyways this to https://github.com/spatie/laravel-ray/pull/204, now has a nicer way
