### ISSUE TITLE
Wordpress setup instructions errors / unclear remarks

### ISSUE THREAD

**Issue by benjamin74** [spatie/ray#484]
Hello guys,

Love the App but had a few problems getting the setup right with Wordpress, here are a few things that should be emphasized / explained in the docs:

- Installing in the mu-plugins **should be the rule when debugging plugins**... it's not emphasized enough in the docs (as in : **made bold**), else (with a simple installation from the WP plugin repository) if the plugin being debugged appears in a higher position in the plugin list, calls to ray() will return an error since ray() functions won't be available at this point. BTW I'm wondering if I could just use a regular WP plugin installed **if the plugin had another name** (e.g. named "aaa-Ray" would push it at the top of the list without having to use the mu-plugins installation, right ?).

- the docs [says](https://spatie.be/docs/ray/v1/installation-in-your-project/wordpress) that: _When developing locally you should have WP_ENVIRONMENT_TYPE set as local in your wp-config.php otherwise Ray won't work._ well I haven't set this variable as "local" but Ray does work... not sure how it's supposed to be working (?)

- Whereas most users will correct that by themself, the code to put in the ray-loader.php is this:

`<?php
require WPMU_PLUGIN_DIR.'/wordpress-ray/wp-ray.php';`

not just

`require WPMU_PLUGIN_DIR.'/wordpress-ray/wp-ray.php';
`
isn't it?

- it's not clear what the role of the ray.php configuration file is (on [this page](https://spatie.be/docs/ray/v1/configuration/wordpress)). e.g. for the setting **enable' => true** described as _This settings controls whether data should be sent to Ray._ do you mean that we could leave all the calls to Ray inside our source code and just put this setting to false when using in production ?

- more generally speaking (related to previous remark) : what do you recommend to do with all calls made to ray() inside the source code once done debugging ?  Same with the created mu-plugins loader and subfolder ? (I'm speaking of in-house development, not plugins that will be made public / distributed)

Thanks

**Comment by AdrianMrn** [comment]
Thanks for the detailed report! Could you create a PR for this, so you get the proper attribution for your input?

You can find the WordPress installation docs here: https://github.com/spatie/ray/blob/main/docs/installation-in-your-project/wordpress.md
