### ISSUE TITLE
Ray Client doesn't open in Windows 10

### ISSUE THREAD

**Issue by kevindaus** [spatie/ray#491]
**Describe the bug**
Ray client doesn't open no matter what I do. 

**Versions**
1.14.7

You can use `composer show` to get the version numbers of:
- spatie/ray package version:  1.27.1
- spatie/laravel-ray package version (if applicable):  1.23.0

PHP version: 7.4.14
Laravel version (if applicable): 

**To Reproduce**
1. Install Ray client 1.14.7
2. Open Ray Client
3. Ray client doent show up

**Expected behavior**
Ray client should open

**Screenshots**
https://www.youtube.com/watch?v=wDIt6-haMPI

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version/OS Build 19042.1052
 - Experience Windows Feature Experience Pack 120.2212.2020.0
 
 **Additional context**
https://www.youtube.com/watch?v=wDIt6-haMPI

**Comment by AdrianMrn** [comment]
This is probably related to this one: https://github.com/spatie/ray/issues/429

I'm publishing a new version of the app today with a menu option to reset the app to the center of the screen.

**Comment by AdrianMrn** [comment]
I've added a shortcut to reset the app to the center of the screen to the "window" menu and the right-click-on-tray menu. Pressing cmd/ctrl+shift+R when the app is active will also do this.

**Comment by kevindaus** [comment]
nah , its still not working . 

https://youtu.be/4_Rn7rp8CrU

It used to work perfectly when It was first released. 
Is there anyway to download the old version ? :(

**Comment by AdrianMrn** [comment]
We're still test running 1.16.0, and will release it in the coming days!

**Comment by kevindaus** [comment]
Issue solved! 

![image](https://user-images.githubusercontent.com/10745021/127618662-0091485a-845d-4280-9ba6-a1a101185b0b.png)

**Comment by AdrianMrn** [comment]
yay!
