### ISSUE TITLE
Arrays in requesr should be expandable

### ISSUE THREAD

**Issue by freekmurze** [spatie/ray#495]
https://twitter.com/LukeDowning19/status/1410188127583539204

**Comment by AdrianMrn** [comment]
@freekmurze What PHP code should I run to easily get an array in the app?

**Comment by lukeraymonddowning** [comment]
If you want it to work today @AdrianMrn you can do

```php
Event::listen(RequestReceived::class, fn($event) => ray($event->request, $event->response));
```

**Comment by lukeraymonddowning** [comment]
@AdrianMrn to replicate the issue, I think you can do:

```php
ray()->table(['foo' => ['bar' => 'baz']], 'example');
```

**Comment by AdrianMrn** [comment]
Thanks!

I've fixed this on our development branch, this fix will be included in next week's release.

![image](https://user-images.githubusercontent.com/12762044/124112520-a7b55700-da6a-11eb-90c7-c7d719a6bb08.png)
