### ISSUE TITLE
Unable to connect to local server

### ISSUE THREAD

**Issue by kornatzky** [spatie/ray#497]
**Describe the bug**

Unable to connect to local Homestead server - get this error

Error: Error invoking remote
method 'connectSsh': Error:
Timed out while waiting for
handshake

**Versions**
Ray version (you can see this in "About Ray"):1.15.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.27.1
- spatie/laravel-ray package version (if applicable): 1.23.0

PHP version: 8.0.5
Laravel version (if applicable): v8.48.2 

**To Reproduce**

Set connection to Homestead:

![CleanShot 2021-07-02 at 10 08 41@2x](https://user-images.githubusercontent.com/1812561/124235286-b7da3e80-db1d-11eb-9ea5-b80f67459dda.png)

**Expected behavior**
Connect to server

**Screenshots**

<img width="367" alt="CleanShot 2021-07-02 at 10 02 01@2x" src="https://user-images.githubusercontent.com/1812561/124234950-5d40e280-db1d-11eb-8000-dd5cb54ec093.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] MacOSX
 - Version [e.g. 22] 11.4
 
 **Additional context**

**Comment by AdrianMrn** [comment]
Can you ssh to your server using your terminal?
