### ISSUE TITLE
Ray app shows blank screen and does not work on windows 10 after updating to 1.15

### ISSUE THREAD

**Issue by janis-inzpire** [spatie/ray#500]
**Describe the bug**
After updating to this version, ray does not work on Windows 10 Pro, build 19042.
Just shows a blank window with missing UI elements and new items are not being shown in it. See screenshot below.
Preferences page does not open as well (nothing happens when going to File -> Preferences)
Nothing happens when creating new screen (View -> New Blank screen OR View -> New Blank screen and Clear history)

**Versions**
Ray version 1.15.0.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version:
Does not matter

**To Reproduce**
1. Install Ray (or update in my case)
2. Launch the app

**Expected behavior**
The app should work :)

**Screenshots**
![image](https://user-images.githubusercontent.com/72384062/124347866-6e5a2400-dbef-11eb-8621-6631c4a12ccf.png)

**Desktop (please complete the following information):**
Windows 10 Pro, build 19042.
 
 **Additional context**
Started to happen after updating yesterday.

**Comment by AdrianMrn** [comment]
Hi @janis-inzpire, could you please follow the steps in this comment and share the output? https://github.com/spatie/ray/issues/371#issuecomment-800293711

I'll see if we can handle these kinds of errors a bit better. For a better chance to get it working straight away, you could try uninstalling it and downloading it again.

**Comment by janis-inzpire** [comment]
Treed uninstalling and installing it again and that worked, so right now I have it working just fine. But over the weekend it randomly died like that again. Will get the output if it happens again, but for now it is sort of working.

**Comment by AdrianMrn** [comment]
No problem, and sorry for the inconvenience! Feel free to reopen this issue when you encounter the problem again.
