### ISSUE TITLE
Composer fails to install on Laravel 8.49.2 PHP 8.0.8

### ISSUE THREAD

**Issue by nathandaly** [spatie/ray#503]
Hey guys, 

Apologies if I am doing something glaringly incorrect but `spatie/laravel-ray` fails to install on the aforementioned. Please find below an output from my terminal with all relevant information (OS and versions e.t.c.).

![debug information](https://i.imgur.com/vhJPwG1.png)

**Comment by nam-co** [comment]
Hi Spatie, I can confirm this, something similar is also happening for example in crawler

**Comment by Nielsvanpach** [comment]
This has been fixed in the meantime, can you verify if it works?
