### ISSUE TITLE
Clear screen shortcut ignored if hide and show shortcut is empty

### ISSUE THREAD

**Issue by benjamin74** [spatie/ray#504]
**Describe the bug**
If you clear BOTH shortcuts and only set a shortcut for the "clear" function, the clear shortcut won't be working. After that if you set a shortcut for the hide/show shortcut, the clear shortcut will work

**Versions**
Ray version (you can see this in "About Ray"): 1.15

**Expected behavior**
We should be able to set the "clear" shortcut with the hide/show shortcut being empty / not set

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7

**Comment by AdrianMrn** [comment]
Thanks for the report, a fix for this will be included in the next version of Ray!
