### ISSUE TITLE
Windows: tray icon right click options don't work

### ISSUE THREAD

**Issue by slaFFik** [spatie/ray#51]
**Describe the bug**

When the app is set to be displayed in Tray and you close the app (using the default Windows close button in app window) - it goes to the tray.

When you right click the tray icon to see the options, I see these: Preferences, Hide Ray, Exit Ray.

Only Exit Ray works fine. 
Preferences option doesn't open app preferences, and for some reason, I have Hide Ray while Ray is already hidden for me.

It works only if Ray is opened and displayed to a user.

"Show app" option is set to "On both task bar and system tray".

**Versions**
Ray: 1.0.4.0

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/282234/104016115-4b116780-51be-11eb-94b9-b7af20adfd4e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 20H2

**Comment by slaFFik** [comment]
In Ray 1.0.5 the new "Show/Hide Ray" now works as expected.

Preferences still don't work when Ray is hidden. 
Expectation: open Ray and its settings.

**Comment by freekmurze** [comment]
The fix will be released in 1.0.7
