### ISSUE TITLE
Feature request: Option to totally exit the app

### ISSUE THREAD

**Issue by shalvah** [spatie/ray#513]
Could we get an option to totally close the app when we click X? Right now, the server remains running in the background, and I have to go to my system tray and exit that too.

It doesn't fit my workflow, because I need to conserve system resources, so I only open Ray when I need to debug something, and I don't need it running in the background.

**Comment by AdrianMrn** [comment]
I understand you issue, but I don't think we'll add a preference option for this anytime soon, as you're the first to ask for it. As with many other modern apps, right click > quit is the only way to completely close the app, without keeping it running in the background.
