### ISSUE TITLE
Not able to collect Ray data from remote server

### ISSUE THREAD

**Issue by labomatik** [spatie/ray#518]
**Describe the bug**
After connection to a remote server, i'm not able to get any data from ray()
The server was installed with forge and deployed with envoyer.io

**Versions**
Ray version: 1.14.7 

- spatie/ray package version: 1.28.0
- spatie/laravel-ray package version (if applicable):   1.23.0

PHP version:
Laravel version (if applicable): 7.4

**To Reproduce**
1. Connect to a remote server
2. execute remote code that is triggering ray() data to be displayed
3. nothing available in ray console

All is fine with local data

**Expected behavior**
Data is available

**Desktop (please complete the following information):**
 - OS: macOs
 - Version 11.4

**Comment by AdrianMrn** [comment]
Could you upgrade your app to 1.16.0 and try this again, please? If it still doesn't work, please make sure all your configuration is set to the default, most importantly check that your port matches.

If it still doesn't work, please open a new issue with detailed reproduction steps, or a screen recording.

**Comment by labomatik** [comment]
The solution for me was to create the ray.php file and make it available on the remote server.

**Comment by lukebouch** [comment]
@labomatik Could you explain in more detail what you did? Where did you put the ray.php file? I'm having the same issue.

**Comment by labomatik** [comment]
At the root of the laravel project i've a ray.php file

with 

`
<?php

return [
    /*
    * This settings controls whether data should be sent to Ray.
    *
    * By default, `ray()` will only transmit data in non-production environments.
    */
    'enable' => env('RAY_ENABLED', true),

    /*
    * When enabled, all cache events  will automatically be sent to Ray.
    */
    'send_cache_to_ray' => env('SEND_CACHE_TO_RAY', false),

    /*
    * When enabled, all things passed to `dump` or `dd`
    * will be sent to Ray as well.
    */
    'send_dumps_to_ray' => env('SEND_DUMPS_TO_RAY', true),

    /*
    * When enabled all job events will automatically be sent to Ray.
    */
    'send_jobs_to_ray' => env('SEND_JOBS_TO_RAY', false),

    /*
    * When enabled, all things logged to the application log
    * will be sent to Ray as well.
    */
    'send_log_calls_to_ray' => env('SEND_LOG_CALLS_TO_RAY', true),

    /*
    * When enabled, all queries will automatically be sent to Ray.
    */
    'send_queries_to_ray' => env('SEND_QUERIES_TO_RAY', false),

    /**
     * When enabled, all duplicate queries will automatically be sent to Ray.
     */
    'send_duplicate_queries_to_ray' => env('SEND_DUPLICATE_QUERIES_TO_RAY', false),

    /*
    * When enabled, all requests made to this app will automatically be sent to Ray.
    */
    'send_requests_to_ray' => env('SEND_REQUESTS_TO_RAY', false),

    /**
     * When enabled, all Http Client requests made by this app will be automatically sent to Ray.
     */
    'send_http_client_requests_to_ray' => env('SEND_HTTP_CLIENT_REQUESTS_TO_RAY', false),

    /*
    * When enabled, all views that are rendered automatically be sent to Ray.
    */
    'send_views_to_ray' => env('SEND_VIEWS_TO_RAY', false),

    /*
     * When enabled, all exceptions will be automatically sent to Ray.
     */
    'send_exceptions_to_ray' => env('SEND_EXCEPTIONS_TO_RAY', true),

    /*
    * The host used to communicate with the Ray app.
    * When using Docker on Mac or Windows, you can replace localhost with 'host.docker.internal'
    * When using Homestead with the VirtualBox provider, you can replace localhost with '10.0.2.2'
    * When using Homestead with the Parallels provider, you can replace localhost with '10.211.55.2'
    */
    'host' => env('RAY_HOST', 'localhost'),

    /*
    * The port number used to communicate with the Ray app.
    */
    'port' => env('RAY_PORT', 23517),

    /*
     * Absolute base path for your sites or projects in Homestead,
     * Vagrant, Docker, or another remote development server.
     */
    'remote_path' => env('RAY_REMOTE_PATH', null),

    /*
     * Absolute base path for your sites or projects on your local
     * computer where your IDE or code editor is running on.
     */
    'local_path' => env('RAY_LOCAL_PATH', null),

    /*
     * When this setting is enabled, the package will not try to format values sent to Ray.
     */
    'always_send_raw_values' => false,
];

`
