### ISSUE TITLE
Ray window resets to centre of screen after app restart

### ISSUE THREAD

**Issue by aryehraber** [spatie/ray#523]
**Describe the bug**
Since the latest Ray update the window resets to the centre of my screen upon opening the app (window size correctly remains the same). I always have Ray sitting on the right edge of my screen, and it used to stay there but now it resets to the centre.

**Versions**
1.16.0

**To Reproduce**
1. Open Ray
2. Move window away from centre
3. Close Ray
4. Re-open Ray

**Expected behavior**
I expect Ray to open in the exact same position as when I closed it last.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.7
 
 **Additional context**
I'm not using an external monitor, just my MacBook Pro screen.

**Comment by AdrianMrn** [comment]
This was added because for some people, the app rendered out of the main screen after disconnecting a secondary monitor.

Could you check if this still happens for you if you place the app just shy of the edge of your screen? I'll see if I can build in a safety margin.

**Comment by aryehraber** [comment]
Ok great, thanks! 

Your suggestion of keeping the window just shy of the edge works for now 👍

**Comment by AdrianMrn** [comment]
I've fixed this in 1.17.0, which will be released today!
