### ISSUE TITLE
Scrolling up and down doesn't remember the expanded array blocks 

### ISSUE THREAD

**Issue by genesiscz** [spatie/ray#525]
**Describe the bug**
With the new version, the performance changed dramatically, which I am grateful for. Thank you guys!
However, in my case, there are a lot of things going on in logs & so on. If I expand the array block & the app (or I do) scroll somewhere else, the block that was expanded probably gets removed from the DOM, which then renders in its default state after I scroll back. (+ One annoying thing is that the bgcolor of these blocks that are loading are white, which hurts at night :-))

**Versions**
Ray version (you can see this in "About Ray"): 1.16

**Screenshots**
I can attach a video if you aren't able to replicate that, but it shouldn't be an issue.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by AdrianMrn** [comment]
Thanks for reporting this issue.

This is sadly a known issue in the latest release, it's on our roadmap to fix asap!

![image](https://user-images.githubusercontent.com/12762044/127513385-c11b7d07-64ee-4f09-8794-b108f27a1f72.png)


>One annoying thing is that the bgcolor of these blocks that are loading are white, which hurts at night

Great suggestion, I always forget to test the app in darkmode 😛 in the next release,  I'll make sure the loading blocks take into account whether dark mode is enabled!

**Comment by AdrianMrn** [comment]
The collapsed state of the symfony dumps are properly saved in the next version of Ray 🎉
