### ISSUE TITLE
[1.16 app] Consume all memory

### ISSUE THREAD

**Issue by lloricode** [spatie/ray#527]
**Describe the bug**

almost consume all memory that become my laptop suddenly not responding

**Versions**
Ray version (you can see this in "About Ray"): 1.16.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.28.0
- spatie/laravel-ray package version (if applicable):  1.24.2 

PHP version: 7.4
Laravel version (if applicable): 8.52.0

**To Reproduce**
1. Open Ray
2. Wait it, it will suddenly stop my laptop if all memory consume

**Expected behavior**
work as normal, and not consume much memory

**Screenshots**

![Screenshot from 2021-07-29 11-47-04](https://user-images.githubusercontent.com/8251344/127428747-0bc40801-e386-4bd4-9289-dfe7b2570cb6.png)

**Desktop (please complete the following information):**
 - OS: Linuxmint
 - Version [e.g. 22] 20.2 Cninamon
 
 **Additional context**

related #210, but i recreate issue it said here https://github.com/spatie/ray/issues/210#issuecomment-884702768

**Comment by freekmurze** [comment]
> Wait it, it will suddenly stop my laptop if all memory consume

It's hard to reproduce this, how long did you have to wait? Is there any way to let Ray use that many memory faster?

**Comment by lloricode** [comment]
Hi @freekmurze 

> Is there any way to let Ray use that many memory faster?

sorry i do not know about this,

while reading this suddenly happen issue again
I used this 
```php
 ray()->showQueries();
```
then after that this will happen
![Screenshot from 2021-07-29 16-00-43](https://user-images.githubusercontent.com/8251344/127455119-9281abef-bfd0-499f-a756-23ec64cba0e0.png)

then later, it become blank
![Screenshot from 2021-07-29 16-01-21](https://user-images.githubusercontent.com/8251344/127455202-28225b4c-762f-41ad-981e-08bf0c534b1d.png)

including consume my left memory

**Comment by ramytamer** [comment]
It started to happen with me after updating to 1.16.0, whenever I execute `ray()->showQueries()` ray would crash; I can't switch between colors or click any button in the app, and after a couple of seconds, it becomes blank like this:
![image](https://user-images.githubusercontent.com/7445123/127733547-72b16b2c-3641-44bb-a52b-df64d2dc7646.png)

Also noticed before crash that ray may consume over 4GB of RAM.

**Versions:**
laravel/framework: 8.31.0
spatie/laravel-ray: 1.14.0

PHP: 8.0.8

OS: MacOS
Version: 10.15.4

**Comment by dessimoni** [comment]
I can confirm that after the 1.16.0 update Ray freezes every time it gets a QueryException showing a blank screen.

spatie/laravel-ray                 1.24.2
laravel/framework                  v8.52.0

PHP 8.0.8

MacOS 11.4 on M1

**Comment by freekmurze** [comment]
@AdrianMrn I could reproduce this by running `php artisan query` in the demo app
https://github.com/spatie/laravel-ray-demo-app/blob/d664896afd4b60c09c5df28be2d6a830fe574915/app/Console/Commands/QueryCommand.php#L11

**Comment by AdrianMrn** [comment]
I'll take a look at this today.

**Comment by AdrianMrn** [comment]
I've fixed the issue with queries in 1.17.0. I'm not entirely sure whether it's related to the memory issue, so if the memory issues persist, please open a new issue with reproduction steps!
