### ISSUE TITLE
No padding around tips at small widths?

### ISSUE THREAD

**Issue by jesseleite** [spatie/ray#528]
Not sure I'd consider this a bug per se, but I like to have the Ray app on the left side of my monitor resized down to a fairly narrow width. The tips text that is centered in the window looks a bit funky without padding around the edges of the window. Pretty subjective I guess, but thought I'd mention ❤️

![image](https://user-images.githubusercontent.com/5187394/127536029-6282bb05-6d66-4a8c-907e-98f71289f1cc.png)

PS. Everybody loves Ray.

![](https://media.giphy.com/media/3o7TKnQ7eAN9mbraVO/giphy.gif)

**Comment by willemvb** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1336390/128869248-14dc72e8-bd58-4cfc-804b-9cda3328c0f9.png">

Hey @jesseleite, will be fixed in next release!
