### ISSUE TITLE
Always on top / Keep this window floating not working

### ISSUE THREAD

**Issue by tonyrumans** [spatie/ray#537]
Ray 1.17.0.0
PHP 7.4
Windows 10

The application window no longer stays on top of other windows. Also, clicking on the task bar icon does not bring the window to the front. You can see it flash on top of another app for a split second but it does not stay on top

**Comment by AdrianMrn** [comment]
I just tested this on my Windows machine and it seems to work just fine. Could you please try removing the app from your system, and reinstalling it?

If it still doesn't work, make sure no other apps are interfering with the float-on-top behaviour, and create a new issue with reproduction steps.

**Comment by tonyrumans** [comment]
Just wanted to provide an update from my end. A reboot didn't fix it but there were some Windows updates that I went ahead and installed, rebooted, and now everything is fine again. I haven't seen the issue happen since I originally posted so not sure what was going on. I have seen other apps act funny like this and after a Windows update things return to normal so...

**Comment by AdrianMrn** [comment]
Thanks for the update and glad to hear you got it working!
