### ISSUE TITLE
Laravel Mailable displayed on Ray not viewable

### ISSUE THREAD

**Issue by qwertynik** [spatie/ray#543]
**Describe the bug**
Using `ray()->mailable(...)` to log the mailable. However, the mailable logged on the ray screen is not easily viewable.

**Versions**
Ray version: 1.17

You can use `composer show` to get the version numbers of:
- spatie/ray: 1.26.0
- spatie/laravel-ray: 1.19.1

PHP version: 7.4
Laravel version (if applicable): 8.46

**To Reproduce**
1. Log a mailable using ray()->mailable(..)
2. Check ray app

**Expected behavior**
Mailable shown in the ray app should be easily viewable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6836536/129166901-6658ede8-d51e-44e9-83f6-bee65141931a.png)

**Desktop:**
 - OS: Windows 10
 - Version: 2004

**Comment by AdrianMrn** [comment]
This seems to work properly on our demo app, could you compare your mailable to the one we have in the demo app, please?

https://github.com/spatie/laravel-ray-demo-app/blob/64d95a54ed8a6bd66c0a26ebcfa7e826e9069a4c/app/Mail/TestMailable.php

![image](https://user-images.githubusercontent.com/12762044/129168982-3dd1e464-bc8f-432c-bcf5-f7dc497ac6f1.png)

**Comment by qwertynik** [comment]
Thanks for your response @AdrianMrn. Turns out that having HTML and body tag in the  view was causing the issue.

**Comment by qwertynik** [comment]
But you might want to add the Mail component in the demo app to make it easier to reproduce.

**Comment by AdrianMrn** [comment]
@qwertynik How do you mean? You can run `php artisan mail` to run the command that displays the Mailable in the app.

**Comment by qwertynik** [comment]
@AdrianMrn 
The demo app you linked [linked](https://github.com/spatie/laravel-ray-demo-app/tree/64d95a54ed8a6bd66c0a26ebcfa7e826e9069a4c) to does not have the mail component due to which the email sending fails. 

Resolving that should improve the demo quality of Ray.

**Comment by freekmurze** [comment]
@qwertynik I don't know what you mean, `php artisan mail` does send a mail.

Could you send a PR to our demo app with the case that fails for you?
