### ISSUE TITLE
Ray not working on some projects

### ISSUE THREAD

**Issue by Thotsuya** [spatie/ray#547]
**Describe the bug**
I followed the steps to install ray, it worked just fine, but when I installed it in another project. It is not sending anything to to ray 
anymore, I'm using phpstorm, it just worked out of the box at first, but then it didn't. I even followed the enviroment specific configurations. but nothing is being sent to ray. I'm using laragon.

After digging a bit deeper, I realized that the project ray was running just fine, had Laravel 8.29.0, I updated it to version 8.54.0 and ray stopped sending information.

**Versions**
Ray version (you can see this in "About Ray"): 1.17.0.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.29.1
- spatie/laravel-ray package version (if applicable): 1.24.2

PHP version: 8.0.8
Laravel version (if applicable): v8.54.0 

**To Reproduce**
1. Updated to laravel 8.54.0

**Expected behavior**
I expected it to work on any project, on any laravel version

**Screenshots**
Working project
![image](https://user-images.githubusercontent.com/55269430/129467366-12f0dbdd-3b2b-4971-822a-814a84cfdfef.png)
![image](https://user-images.githubusercontent.com/55269430/129467394-1ba78b5d-2102-4355-bf05-a397a2c111b2.png)
![image](https://user-images.githubusercontent.com/55269430/129467390-abaa779f-2335-4d85-9213-49a0ee54d9a7.png)

Not working
![image](https://user-images.githubusercontent.com/55269430/129467381-3858a755-807f-431a-a216-a77ee6674e0d.png)
![image](https://user-images.githubusercontent.com/55269430/129467416-7a640f68-e368-4c5a-9916-264d07f784cf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 21H1
 
 **Additional context**
The project where ray is working fine has:

spatie/ray 1.29.0
spatie/laravel-ray 1.24.2

**Comment by Thotsuya** [comment]
Update, It seems that spatie/ray version 1.29.1 is not working on my projects, so I downgraded it to 1.29.0 and worked.
Not sure why this is happening. Can anyone from the spatie team or anyone that had experienced this issue give me some insights?

**Comment by freekmurze** [comment]
This has been fixed in 1.29.2

**Comment by Thotsuya** [comment]
Can confirm, thanks
