### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by keizah7** [spatie/ray#553]
**Describe the bug**
Found some issue with scroll. Restart doesn't help
If i try scroll fast, this happens.

**Versions**
Version 1.17.0 (1.17.0)
spatie/laravel-ray 1.25.0
PHP 8.0.8 
Laravel 8.12

```
/**
 * Execute the console command.
 *
 * @return int
 */
public function handle()
{
    ray(
        Apartment::query()->pluck('room_type_id')
    );
}
```

https://user-images.githubusercontent.com/49227202/132179810-a8d28904-b38e-425e-bd66-c639538667f5.mov

**Comment by AdrianMrn** [comment]
Thanks for the detailed report!

This is a [known issue](https://github.com/spatie/ray/issues/525) with the virtualized list I implemented in 1.16.0 and the debug logs. I'll be doing some QoL improvements after my holiday, so you can definitely expect a **fix for this in the next month**!

Please let me know if there's anything else that's bothering you about the app, or if you have any other suggestions for improvement 🙂

**Comment by voidgraphics** [comment]
@AdrianMrn aside from the scroll bug mentioned above, focusing on performance would be very nice. Changing between pages is pretty slow right now, even between pages that do not have many logs in them.

**Comment by AdrianMrn** [comment]
The collapsed state of the symfony dumps are properly saved in the next version of Ray, performance should already be much better since the big state refactors in 1.18.0.
