### ISSUE TITLE
Copy to clipboard is not working on Linux

### ISSUE THREAD

**Issue by sowrensen** [spatie/ray#555]
**Describe the bug**

Just as the title says. A screencast is attached for further clarification.

**Versions**

v1.17.0 (Didn't work on earlier versions either)

**To Reproduce**

I am using `ray()->toJson($something)` method in this case. Just try to copy and paste the output somewhere else.

**Expected behavior**

Content should get copied to the clipboard.

**Screenshots**

https://user-images.githubusercontent.com/80112748/132488267-1e395269-3cb3-4abc-85ae-572de5c132c5.mp4

**Desktop (please complete the following information):**
 - Manjaro Linux (Gnome Edition)
 - Pahvo 21.1.2

**Comment by nemoitis** [comment]
This is not fixed. Please re-open the issue. Is there something I can do to solve this?

**Comment by jcordingley** [comment]
This is also an issue for me, im running pop-os linux.

**Comment by jcordingley** [comment]
Still not resolved, please re-open

**Comment by rybber78** [comment]
Same here on Pop OS, Brave Browser

**Comment by mbaric** [comment]
Still not resolved on

![image](https://github.com/spatie/ray/assets/2319358/7d5f2f13-8f2b-43de-a820-cf6df1edfc8f)

**Comment by mbaric** [comment]
@Sam-Apostel @freekmurze Any updates on this guys please. It's really annoying to copy paste it manually.

**Comment by mbaric** [comment]
Today I needed that copy/paste badly on my Linux machine but still it's not working, could the Spatie team please let us know if this is getting resolved?

@freekmurze @Sam-Apostel
