### ISSUE TITLE
Clicking on a file logged in Ray doesn't open my text editor (Sublime)

### ISSUE THREAD

**Issue by pascalchevrel** [spatie/ray#57]
**Describe the bug**
Clicking on a file logged in Ray doesn't open the text editor (in my case Sublime)

**Versions**
Ray version (you can see this in "About Ray"): 1.0.3

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.2.0
- spatie/laravel-ray package version (if applicable): 

PHP version: 7.4.9
Laravel version (if applicable):

**To Reproduce**
1. Log someting
2. Click on the file name logged in the application

**Expected behavior**
The file is opened at the line indicated by Ray in the text editor I chose in preferences (Sublime)

**Actual behavior**
Nothing happens

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version [e.g. 22] 20.10
 
 **Additional context**
Tested in the trial version.

**Comment by AdrianMrn** [comment]
I assume this is similar to https://github.com/spatie/ray/issues/21, and will have something to do with how we're building the path. I'll try to fix this issue today.

**Comment by freekmurze** [comment]
On Mac it seem that you need to manually register the sub protocol: https://github.com/saetia/sublime-url-protocol-mac
After that it works.

Maybe you need to do something similar in other OS'es

**Comment by pascalchevrel** [comment]
I did  install the subl protocol extension, I tested it with a local webpage and a link of the form subl:///home/foo/path/to/file.php:10 does work from a web page.

Now that this package is installed, Ray opens a blank file in Sublime with this path /home/foo/path/to/open?url so it still doesn't work.

**Comment by AdrianMrn** [comment]
I'll have a look into this!

**Comment by AdrianMrn** [comment]
This should be fixed in 1.2.2 (will release later today). Please let me know if it still doesn't work!

**Comment by pascalchevrel** [comment]
This is not fixed in 1.2.2, did you mean maybe an upcoming 1.2.3 coming later today?

**Comment by AdrianMrn** [comment]
Yup!

**Comment by pascalchevrel** [comment]
I confirm that it works in 1.2.3
