### ISSUE TITLE
Failed to connect ssh without password [app v1.18.0]

### ISSUE THREAD

**Issue by lloricode** [spatie/ray#582]
**Describe the bug**
Connection to ssh `~/.ssh/id_rsa` failed

**Versions**
Ray version (you can see this in "About Ray"): 1.18.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: not related
- spatie/laravel-ray package version (if applicable): not related

PHP version:
Laravel version (if applicable): not related

**To Reproduce**
1. Go to Ray app servers
2. Click one server or create one
3. select `SSH` with value `~/.ssh/id_rsa` then hit `save`
4. Then click `connect` button

**Expected behavior**
Should connect to server using ssh without password

**Screenshots**

![Screenshot from 2021-10-25 12-02-33](https://user-images.githubusercontent.com/8251344/138633170-965ce097-70a9-4b04-b655-669c2eab7fac.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - Version 20.2 Cinnamon
 

 **Additional context**

running `ssh vagrant@192.168.10.10` is working fine

![Screenshot from 2021-10-25 12-10-32](https://user-images.githubusercontent.com/8251344/138633444-09011c73-c3a1-4b61-92da-cf9dc01ccfd1.png)

**Comment by rkmaier** [comment]
Same issue in the latest version on Windows con't connect using ssh

**Comment by AdrianMrn** [comment]
@lloricode Am I correct in assuming you are no longer encountering this issue?

@rkmaier Could you please create a new issue, detailing exactly what error you're getting and how to reproduce it? Thanks!

**Comment by lloricode** [comment]
> @lloricode Am I correct in assuming you are no longer encountering this issue?
> 
> @rkmaier Could you please create a new issue, detailing exactly what error you're getting and how to reproduce it? Thanks!

thanks will check this later 💯

**Comment by rkmaier** [comment]
@lloricode Latest version 1.18.3 solved it
