### ISSUE TITLE
Ray not receiving events on Windows with WSL2

### ISSUE THREAD

**Issue by ryanmortier** [spatie/ray#590]
**Before creating a new bug report**
Ref #559

**Describe the bug**
I'm a first time Ray user and I've installed the Windows app and followed the WSL2 instructions. I've set a static IP for my PC and other electron apps are receiving events from WSL2 using this static IP, namely HELO from BeyondCode.

**Versions**
v1.18.1 (Windows)

You can use `composer show` to get the version numbers of:
- spatie/ray package version: v1.30.3
- spatie/laravel-ray package version (if applicable): v1.26.1

PHP version: v7.4.3
Laravel version (if applicable): v8.69.0

**To Reproduce**

Inside WSL2

1. `php artisan tinker`
2. `ray('test');`

**Expected behavior**
Expect to see debug info in the Windows app.

**Screenshots**
My .env file:
![image](https://user-images.githubusercontent.com/2053960/140390530-34cf94a9-a717-444b-a2a1-ea34f2799ed9.png)

Nothing shows up:
![image](https://user-images.githubusercontent.com/2053960/140390562-3fd7140e-0a63-4887-a8aa-eaf09b2feb1a.png)

Not a firewall issue:
![image](https://user-images.githubusercontent.com/2053960/140390646-5a992604-7df6-4bbe-a03b-78506c1ed3b8.png)

LAN IP Address:
![image](https://user-images.githubusercontent.com/2053960/140390717-7957ace8-2faf-4ece-9f03-4bfe7a5461af.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1
 
 **Additional context**

**Comment by ryanmortier** [comment]
Wow, nevermind. I forgot to publish the config so the .env variable must not have been working.

**Comment by AdrianMrn** [comment]
Great to hear you got it working! 😁
