### ISSUE TITLE
Don't work connect to server button

### ISSUE THREAD

**Issue by futureclient** [spatie/ray#591]
**Describe the bug**
After upgrading to 1.18.1.0, I can't connect to the server. When you click the connect button, a popup appears with an error
Error: An object could not be cloned.
The server was deleted after being added again. The error is repeated. The connection to the server is used via a password.

**Versions**
1.18.1.0

PHP version: 7.4

![image](https://user-images.githubusercontent.com/29013160/140467256-2a6d4c8c-956d-418f-a357-0c708d0a0ffc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 19043.906

**Comment by nnerijuss** [comment]
Same here - macos monterey

**Comment by gkimpson** [comment]
Same on MacOS BigSur using Intel iMac - I am trying to find a way to download an older version of Ray but having no success so far

**Comment by patjun** [comment]
Same here - macos Catalina - Intel Mac

**Comment by AdrianMrn** [comment]
My bad, releasing a fix now. 1.18.2 should be live in about 10-15 minutes 😁

**Comment by patjun** [comment]
Works for me. Thanks for the quick fix.
