### ISSUE TITLE
Window version freezes and CPU spikes after dumping a specific object

### ISSUE THREAD

**Issue by sunscreem** [spatie/ray#593]
**Describe the bug**
Super keen to start using ray but found a problem straight out of the gate. It works great until I dump a particular object then it freezes (some function still work but mostly its frozen) and CPU usage jumps to 100% for about 2 minutes.

**Versions**

1.18.3

PHP version: 8.0.10
Laravel version (if applicable): 8.62.0

**To Reproduce**
I can dump most things into Ray no problem but this specific object makes the central screen freeze for about 1-2 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/7523595/141105138-8a2fa880-c6b0-4e28-bc2a-66c9c5ab5730.png)

**Desktop (please complete the following information):**
 - OS: Window
 - Version: 10

Let me know if there's anything I can provide to help diagnose this.

**Comment by sunscreem** [comment]
I'm not sure if this helpful but when I dump the same object to the console instead I notice it's HUGE. 

(I'm using Statamic which seems to have a lot of routes coming up in the dump)

**Comment by sunscreem** [comment]
Okay - further investigation and I found that dumping any object that contains an instance of the laravel `url()` helper causes Ray to crash.

**Comment by freekmurze** [comment]
I tried this code

```php
ray(url());
ray('Ray still works');
```

And using all the latest releases, that seems to be working.

<img width="841" alt="CleanShot 2021-11-11 at 10 47 47@2x" src="https://user-images.githubusercontent.com/483853/141276495-f67b9070-05f4-402d-8cd6-db205e6e219f.png">

**Comment by sunscreem** [comment]
Thanks @freekmurze. When I'm trying the same it crashes. I'm now fairly convinced that the payload being sent to ray is absolutely huge. 

![image](https://user-images.githubusercontent.com/7523595/141285066-1ec22f1b-5329-4e95-9198-2e879715d052.png)

The problem is I can't prove it as I can't work out how to see the payload being sent.

If I `dd()` or `Log::info` in both cases they just return the string url.

Could you point me to where I could dump the payload?

**Comment by AdrianMrn** [comment]
I can reproduce this on my intel Mac, however I don't think this is something we can reliably deal with as the url() helper is over 0.5MB in size and needs to be evaluated by the symfony dump script to get the collapsibles to work.

I've loosened the rules by which the log table decides whether to rerender items, this might help your case a bit, but I think it won't solve it 100% :(

@freekmurze is there anything we can do in the laravel package to prevent huge logs from reaching the app?

**Comment by freekmurze** [comment]
I'm afraid we can't solve this easily...

**Comment by AdrianMrn** [comment]
@sunscreem if this is a critical issue that you cannot work around, I'll consider adding a "low-performance" option (no offence implied 🙈) in the app, which stops huge logs from being evaluated. This isn't a perfect solution, as it would stop you from being able to collapse the items in the dumps, but it would at least stop the app from freezing.

**Comment by sunscreem** [comment]
@AdrianMrn I reworked my application to just use a string instead of the url() helper in the end. It sort of messes with my brain as when I `dd(url('whatver'))` you just get a string, yet with ray it's trying to send the huge payload as you suggested. Weird one!
