### ISSUE TITLE
Ray won't dump if a string value of `value` is passed

### ISSUE THREAD

**Issue by jesseleite** [spatie/ray#594]
**Describe the bug**

Ray doesn't seem to want to dump if a string of `value` is passed as one of the args...

**Versions**

- spatie/ray package version: 1.30.3
- spatie/laravel-ray package version (if applicable): 1.26.1
- PHP version: 8.0.12
- Laravel version (if applicable): 8.68.0

**To Reproduce**

- Dump to ray with a string of `value`
    - ie. `ray('value')` or `ray('value', $someValue)`

**Expected behavior**

I would expect ray to dump something, but nothing is output in the Ray app window.

**Screenshots**

![image](https://user-images.githubusercontent.com/5187394/141146517-23058820-f5df-49e4-9398-065797bef0ad.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 11.6.1

**Comment by freekmurze** [comment]
Thanks for reporting. This has been now fixed in the latest version of spatie/ray.
