### ISSUE TITLE
Windows: incorrect notification title in Notifications Center

### ISSUE THREAD

**Issue by slaFFik** [spatie/ray#598]
**Describe the bug**
Internal app identifier is used as a notification title: `electron.app.Ray`

**Versions**
Ray version (you can see this in "About Ray"): 1.18.4

**Expected behavior**
The Windows notification should have a proper title, at least something like `Ray`.

**Screenshots**
![image](https://user-images.githubusercontent.com/282234/142834990-6bd363fa-5b9b-40e3-99d3-ba7d91f25ea7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Windows 10 Pro 21H2

**Comment by AdrianMrn** [comment]
I think this is because of a bug in 1.18.4, please let me know if the error persists for the next update (1.18.6 or 1.19.0).
