### ISSUE TITLE
Linux: Font size is smaller than what my OS uses  

### ISSUE THREAD

**Issue by pascalchevrel** [spatie/ray#60]
**Describe the bug**
The font size used by Ray is smaller than what I use on my OS, making it a bit hard to read

**Versions**
Ray version (you can see this in "About Ray"): 1.0.3

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.2.0
- spatie/laravel-ray package version (if applicable): 

PHP version: 7.4.9
Laravel version (if applicable):

**To Reproduce**
1. Launch ray
2. Look at the font size

**Expected behavior**
Same font size than my other gnome applications

**Actual behavior**
The font size is smaller than what most of my applications use (12pt). It looks like the font size in most of Ray UX is like 8/10pt
Generally speaking, the colors are also off compared to my OS

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version [e.g. 22] 20.10
 
 **Additional context**
* Being able to adjust the font size in the preferences if getting it from the OS is hard would be a workaround.
* The menu items seem to have the right font sizes, it's the main Ray pane that has smaller font sizes.

**Screenshots**
![Capture d’écran de 2021-01-08 15-00-00](https://user-images.githubusercontent.com/454375/104023840-89a92100-51c2-11eb-8a30-71aee70f9ed8.png)

**Comment by freekmurze** [comment]
In the view menu there are options to make the UI smaller and bigger.
