### ISSUE TITLE
Ray was unable to bind to the remote server's port

### ISSUE THREAD

**Issue by thelaarn** [spatie/ray#606]
**Describe the bug**
Cannot connect to a remote server and get the error message 'Ray was unable to bind to the remote server's port. Is the port in use or is someone else using ray on this server?'

**Versions**
Ray version (you can see this in "About Ray"): Version 1.19.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version: 7.4
Laravel version (if applicable): n/a

**To Reproduce**
1. Go to 'Servers' tab (top right corner)
2. Click on 'Add server'
3. Setup a remote server with sftp using username/password
4. Click on 'plug icon'
4. See error 'Ray was unable to bind to the
remote server's port. Is the port
in use or is someone else using
ray on this server?' 

**Expected behavior**
make a connection to the remote server

**Screenshots**
![image](https://user-images.githubusercontent.com/20276610/144341299-8e5e4fbe-1d5f-40c3-80d5-59eda0fa3cb0.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 
 - Version 12.0.1
 
 **Additional context**
I made sure there were no other sftp connections to the server and I can confirm that SFTP details are correct as I can log in via FTP client filezilla

**Comment by AdrianMrn** [comment]
Does restarting the server fix this? Have you been able to connect Ray to the server before?

I'm going to close this issue because it's been inactive for a while. Let me know if you still need help with this problem!

**Comment by nlemoine** [comment]
@AdrianMrn I'm having the same issue here. Is there any way to access some logs about what's going wrong in the SSH connection?

**Comment by AdrianMrn** [comment]
@nlemoine I've had this issue myself as well and haven't been able to debug it, sadly we're currently not keeping any logs for errors at this moment, we might add this in the future.

The only reliable solution I've found is to -however unpractical- reboot the remote server.

**Comment by nlemoine** [comment]
Thanks for the prompt reply! :) It's actually impossible because I'm having this issue on a cheap shared hosting... (I don't have any other choice on a particular project) so reboot isn't an option.

But SSH works on that host from my terminal, so I wonder why Ray can't establish connection to it. And besides "ray was unable to bind..." I can't get any valuable information. Let me know when some kinds of logging lands in Ray.

**Comment by benjamin74** [comment]
Having the exact same problem here:

Ray was unable to bind to the remote server's port. Is the port in use or is someone else using ray on this server?

The port is not in use afaik and for sure nobody is using ray on that server.

Rebooting the server is an absolutely aweful solution... why has this been closed?

**Comment by tonkoshkurik** [comment]
Also, looking for a solution here.

**Comment by gixxy22** [comment]
same issue here

**Comment by angorb** [comment]
Solid solution @JoshMoreno - I run into this all the time with my AWS-hosted development server and a flaky VPN connection and this is **so** much easier than rebooting the EC2 instance from the AWS Console and waiting for my box to come back up. 👍🏼

**Comment by Mwalek** [comment]
Same problem here. Is this being worked on?
