### ISSUE TITLE
Ray not open files in PHPStorm, Atom, VScode in Ubuntu 20.04

### ISSUE THREAD

**Issue by abkrim** [spatie/ray#611]
I put same issue in discussion. After some time, put here, because I think is a mistake.

On documentation, not show anything about problems with ray and open with external apps.

I have tried different configurations with different editors, opening the files from the ray itself.

In all cases, the error message is the same: There is no manager for the archive.

I think the command to open files is wrong, and that is why the error occurs.

**Versions**
- app Ray 1.1.9.0
- spatie/laravel-ray                                   1.26.4    Easily debug Laravel apps
- spatie/ray                                           1.32.1    Debug with Ray to fix problems faster
- Laravel Framework 8.76.2
- PHP version: PHP 8.0.13

**To Reproduce**
- Run my tests.
- I like open one file
- Click on file in ray ap.
- Get error 

- Change preferences for other editor
- Kill ray (Ray not close correctly in linux. I needs kill master process on shell)

**Expected behavior**
Open the file when I click on it

**Screenshots**
![Castris_20211221_115336](https://user-images.githubusercontent.com/1238625/146918540-e2e359d0-8d8c-45e6-bb20-131be01c80f8.jpg)
![Castris_20211219_190821](https://user-images.githubusercontent.com/1238625/146918561-247176b1-1928-46f0-a413-405884a81651.jpg)

Translate error: "Could not find any application or driver for ... [phpstorm|vscode|atom]

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04
 
### Working on shell

If I like open in shell any file any of below commands works in my computer.

```
> phpstorm server.php
> atom server.php
> code server.php
```

**Comment by AdrianMrn** [comment]
I think for Linux you need to install URL protocols, eg for code: https://github.com/shengyou/vscode-handler or phpstorm: https://github.com/aik099/PhpStormProtocol

**Comment by abkrim** [comment]
Hi. 
Sorry but that doesn't quite work almost with PHPStorm

Ray send url decode `%2Fhome%2Fuser.... ` instead a normal string '/home/user/...'.

![Castris_20211221_192924](https://user-images.githubusercontent.com/1238625/146980760-b2cf6908-12b8-4dc2-9575-517b7285f1c3.jpg)

README of phpstrom-url-handler

```
## Usage

It can be used to open files at the specified line from within the browser by
placing a link of the following kind in the markup:

    <?php
    $file = "/path/to/filename.php";
    $line = 35;
    print "<a href='phpstorm://open?url=file://$file&line=$line'>Open with PhpStorm</a>";
    // Alternate Syntax to match PhpStorm 8 for the Macintosh
    print "<a href='phpstorm://open?file=$file&line=$line'>Open with PhpStorm</a>";
    ?>
```



Thanks.

**Comment by AdrianMrn** [comment]
I've added this issue to our internal issue tracker and will have a look at it sometime in the next couple of weeks!

**Comment by abkrim** [comment]
A lot of thanks.

**Comment by AdrianMrn** [comment]
In the next version (releasing in a couple of weeks), you can set a custom editor url: 
![image](https://user-images.githubusercontent.com/12762044/149338701-a1a64ede-b93e-4be1-b529-4fceecdbaf80.png)

Please let me know if the URL is still being decoded, and I'll have another look at this.
