### ISSUE TITLE
Cannot change the way links to files are generated for PHPSTORM (Windows)

### ISSUE THREAD

**Issue by blchv** [spatie/ray#621]
**Before creating a new bug report**
I was not able to find any information on this topic

**Describe the bug**
It is not possible to open a file in PHPSTORM by clicking the file link in the Ray Windows app.
`phpstorm://open?file=[path/to/file]` is not working for me even after the steps suggested in the documentation (reg edit and stuff).
That being said, I have another way to open files via link.

I can open files using the built-in server of PHPSTORM by accessing a url like this: `http://localhost:63342/api/file/[path/to/file]`. (Configuration for this is in **Additional Context**.) 

I am looking for a way to instruct Ray to replace `phpstorm://open?file=` with `http://localhost:63342/api/file/` so I don't have to wait for JetBrains to fix the protocol.

Is there a way to change how the file link is generated?

**Versions**
- PHPSTORM: 2021.3 Build #PS-213.5744.279
- Ray Windows app version: 1.19.0.0
- spatie/backtrace: 1.2.1
- spatie/macroable: 1.0.1
- spatie/ray: 1.32.2

**To Reproduce**
1. Generate a message for the Ray Windows app by calling `ray(...args)` in a PHP file.
![image](https://user-images.githubusercontent.com/44664543/148692236-3152c46a-7d49-490e-bf2a-f0cf37daa6cb.png)

2. Execute the file and receive the message in the Windows app.

3. Click the link that is supposed to open the file in the configured code editor
![image](https://user-images.githubusercontent.com/44664543/148692344-312ed401-0897-4b3c-b573-835fa63952bc.png)

4. Observe the error
![image](https://user-images.githubusercontent.com/44664543/148692384-b9f83e0e-f840-4ec8-a57b-8bb8d5618232.png)

**Expected behavior**
Be able to open files in PHPSTORM on Windows 10 successfully.

**Desktop (please complete the following information):**
 - OS: Windows (build 19042.1415)
 - Version: 20H2
 
 **Additional context**
This is my config for the built-in server:
![image](https://user-images.githubusercontent.com/44664543/148692932-395dfb2e-f53c-48b9-af7c-e987b64f6129.png)

**Comment by AdrianMrn** [comment]
I've created an issue for this in our internal issue tracker. I'll probably add a "custom" option to the selectinput, which allows you to enter your own string that accepts `{FILE}` and `{LINE}` placeholders that will be replaced when clicking on a file link.

**Comment by AdrianMrn** [comment]
The above change will be included in the next release (in a few weeks).

**Comment by blchv** [comment]
@AdrianMrn thanks! I'm looking forward to the next version. Take care!
