### ISSUE TITLE
Ray NOT working in php7.4 but working in php8.0

### ISSUE THREAD

**Issue by kiana133** [spatie/ray#622]
**Describe the bug**
When I am on a php 7.4 project, ray stopped working for me (but works for other members of my dev team in the same project), and in php 8.0 it works fine. I have looked through the other issues and none helped. I tried doing
- ray()->enable() but no luck,
- updating dependencies,
- composer install or composer update.

**Versions**
- Ray version: 1.19.0
- spatie/ray package version: 1.32.1
- spatie/laravel-ray package version (if applicable): 1.27.2
- PHP version: 7.4.26
- Laravel version (if applicable): 7.28.4

**To Reproduce**
1. Add a ray call to your codebase (ie: ray('test')).
2. Execute.

**Expected behavior**
The data passed to ray() is sent to the Ray desktop app.

**Desktop:**
 - OS:  macOS
 - Version 11.5.2

**Comment by patinthehat** [comment]
@kiana133 Can you provide a small sample repository that demonstrates the issue you're having? I am unable to replicate locally.
