### ISSUE TITLE
Popups should be on top of the Ray app

### ISSUE THREAD

**Issue by slaFFik** [spatie/ray#623]
**Describe the bug**
Popup which tells whether a new version available is hidden behind the Ray app itself.
Same with the popup about the Ray version.

Those 2 should have a higher "z-index" (if speaking in CSS terms) to be on top of the Ray app because they are triggered manually and user expects them to see. But when the Ray app is placed exactly in the middle of the screen - it covers those small popups.

**Versions**
Ray version (you can see this in "About Ray"): 1.19.0

**To Reproduce**
1. Go to Menu > About Ray
2. Go to Menu > Check for updates
3. observe that Ray app covers those 2 popups (maybe others as well).

**Expected behavior**
Those small informational popups should have higher priority and be rendered on top of Ray even if Ray configured to be rendered on top of all other windows.

**Screenshots**

![image](https://user-images.githubusercontent.com/282234/149287105-4329b652-27af-46ff-a2f6-4de795ef1b4b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2

**Comment by axelitus** [comment]
I can confirm I'm having the same issue:
![image](https://user-images.githubusercontent.com/732441/151700601-9db485bd-5c16-4421-96d0-2ff7beef07f7.png)

**Comment by axelitus** [comment]
This happens only when "Always on top" is set to "Yes":
![image](https://user-images.githubusercontent.com/732441/151701068-c33f6440-3acf-40d0-a567-f504ef7be61f.png)
![image](https://user-images.githubusercontent.com/732441/151701072-4dc00b6e-ce10-4c07-a0bd-36f501a403a3.png)
