### ISSUE TITLE
VScode integration - broken link

### ISSUE THREAD

**Issue by imClement** [spatie/ray#624]
**Describe the bug**
I have on the .env file
`RAY_LOCAL_PATH=/home/username/Projects/MyProject/`

But when I click on the file in Ray the link to the file use an extra 'html' folder so the file is not found. 

 `~/Projects/MyProject/html/app/Models/User.php`

**Versions**
Ray version (you can see this in "About Ray"): 1.19.0
- spatie/ray package version: 1.33.0
- spatie/laravel-ray package version (if applicable):  1.29.0

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]  Ubuntu
 - Version [e.g. 22]  20.04

**Comment by AdrianMrn** [comment]
@freekmurze Any idea where this rogue `html` in the filepath could be coming from?

**Comment by billriess** [comment]
I'm having a similar issue using WSL2. Links in Ray application are defaulting to `/var/www/html/...` but I have `RAY_LOCAL_PATH='\\wsl$\Ubuntu\home\bill\dev\hub'` defined in my `.env`.

**Comment by RhysLees** [comment]
Also having this with WSL2 like @billriess

**Comment by RhysLees** [comment]
> **Describe the bug** I have on the .env file `RAY_LOCAL_PATH=/home/username/Projects/MyProject/`
> 
> But when I click on the file in Ray the link to the file use an extra 'html' folder so the file is not found.
> 
> `~/Projects/MyProject/html/app/Models/User.php`
> 
> **Versions** Ray version (you can see this in "About Ray"): 1.19.0
> 
> * spatie/ray package version: 1.33.0
> * spatie/laravel-ray package version (if applicable):  1.29.0
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. macOS]  Ubuntu
> * Version [e.g. 22]  20.04

Have you found a solution yet? I'm still having this issue

**Comment by Eldair** [comment]
Hi, this issue is still present (for me it is double app dir: '\\app\app...')
