### ISSUE TITLE
Cannot change port in Ray app (MacOS)

### ISSUE THREAD

**Issue by dabernathy89** [spatie/ray#626]
**Describe the bug**
The port inside of Ray's settings page always reverts to `23517` after closing the settings screen.

**Versions**
Ray version: 1.19.0

- spatie/ray package version: 1.33.0 (shouldn't be relevant)

PHP version: 7.4 and 8.0
Laravel version (if applicable): 8.79.0 (shouldn't be relevant)

**To Reproduce**
1. Open Ray
2. In the menubar, open the settings via "Ray -> Preferences"
3. Change the port number under "Communication -> Port"
4. Click "Done"
5. Repeat step #2 (open preferences)
6. See port number is still 23517

**Expected behavior**
The port number should be updated when the settings screen is closed.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur (11.6)

**Comment by AdrianMrn** [comment]
We're releasing a new version of Ray in a couple of weeks where the entire preferences window has been overhauled, so your issue will be fixed.

Let me know if this issue is very pressing, and I'll see if I can make a patch build for you.

**Comment by dabernathy89** [comment]
No rush on my end. Thanks!

**Comment by dabernathy89** [comment]
Hey @AdrianMrn - just wanted to check and see if this fix is still on the release schedule?

**Comment by AdrianMrn** [comment]
Since this release is pretty big, we're taking some extra time to make sure everything works OK. We will definitely publish the release within the next 2 weeks.
