### ISSUE TITLE
Ray should be deactivated if testing

### ISSUE THREAD

**Issue by leganz** [spatie/ray#63]
**Describe the bug**
If you running phpunit/pestphp eg via Github Actions ray might not be installed which will cause the issue that tests will run endless. (happend to me and costs me 2 hours of github action time)

<img width="1071" alt="Bildschirmfoto 2021-01-08 um 12 45 59" src="https://user-images.githubusercontent.com/3373530/104032643-b9f6bc80-51ce-11eb-846b-98ccb0188e4f.png">

**Versions**
Ray version (you can see this in "About Ray"): 1.0.0

- spatie/laravel-ray package version: ^1.1 

PHP version:
Laravel version (if applicable): 8

**To Reproduce**
1. Add ray to a laravel project
2. Add ray.php to project with flag active is true
3. Add github action where you run the tests
=> Test didn't fail but run endless. (if phpunit isn't setup to fail early)

**Expected behavior**
Should not run in testing mode or should not block github actions.

**Comment by freekmurze** [comment]
This has been fixed in the latest release of spatie/ray (that exception won't be thrown anymore).
