### ISSUE TITLE
Dumping the string `date` shows false on app

### ISSUE THREAD

**Issue by elvispt** [spatie/ray#631]
**Describe the bug**
When dumping the string "date" `ray('date')` the ray application shows false.

If I set `exit` right after the ray function call, I also get this error on the page:
`Warning: date() expects parameter 1 to be string, object given in /var/www/html/app/plugins/spatie-ray/vendor/spatie/ray/src/Ray.php on line 455`

It's clear it's attempting to run the date function, but it should just show the "date" string.

**Versions**
Ray version (you can see this in "About Ray"): 1.19.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: Using WordPress plugin 1.5.1 
- spatie/laravel-ray package version (if applicable): 

PHP version: 7.4.26
Laravel version (if applicable):

**To Reproduce**
1. Call `ray('date')`
2. Run the code
3. See the result on the app

**Expected behavior**
Should just dump the string "date" on the application.

**Screenshots**
Example:
![image](https://user-images.githubusercontent.com/988967/151157358-3ff1c89d-808e-47a8-8e31-1ac3c4bdb38e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.1
 
 **Additional context**
The PHP code is running inside a docker container using `alpine:3.13.5` as base image (from which PHP is then installed).

**Comment by kemp** [comment]
That would probably be because of this line:

https://github.com/spatie/ray/blob/fa2b3e64a93717ccf478a701048181a515eef2a3/src/Ray.php#L639

**Comment by elvispt** [comment]
@kemp I do believe this is unexpected behavior. I came across this when I was dumping the value that was on an array: `ray($arr['level1']['level2'])` and was confused when ray was showing false, when I expected the value to be a string from a predefined list. I thought my code had a bug.

**Comment by Nielsvanpach** [comment]
This is already fixed and released: https://github.com/spatie/ray/commit/41412bca9add3374a13310f6e5ceef54633f6bfd
You are using 1.19.0 while the latest release is 1.33.2, the issue should be fixed after upgrading.

Sending 'date' as string and array both seem to work fine on the latest release.

<img width="687" alt="Screenshot 2022-02-09 at 11 32 28" src="https://user-images.githubusercontent.com/10651054/153180399-a20fd27b-ecf4-4430-a2b0-a6b897aab975.png">

**Comment by elvispt** [comment]
Hi @Nielsvanpach 
I checked if I have the latest version on the app, and it says I have the latest v1.19.0.

I went to the purchases page to download, and it gives me the same version. Can you tell me where to get the latest? It's the Apple Intel version.

Thanks
