### ISSUE TITLE
Package looks incompatible with composer v1

### ISSUE THREAD

**Issue by stennkool** [spatie/ray#65]
**Describe the bug**
There are still a lot of projects that are incompatible with composer v2 (e.g. Magento) and the composer-runtime-api:2,0 is unavailable there.
It would be really helpful to be able to use this package with composer v1

**Versions**
`1.2.0`

PHP version:
`7.4.10`

**To Reproduce**
`composer require spatie/ray --dev`

**Expected behavior**
Allow ray to install

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.0.1 Big sur

**Comment by HazJ** [comment]
In the meantime, you can use the `--ignore-platform-reqs` flag. Tested on: Composer version 1.10.19 2020-12-04 09:14:16
 `composer require spatie/ray --dev` --ignore-platform-reqs`

**Comment by HazJ** [comment]
In the meantime, you can use the `--ignore-platform-reqs` flag. Tested on: Composer version 1.10.19 2020-12-04 09:14:16
 `composer require spatie/ray --dev --ignore-platform-reqs`

**Comment by slaFFik** [comment]
@stennkool Check this out: https://github.com/spatie/ray/releases/tag/1.1.2
It looks like they are enforcing composer 2.

**Comment by HazJ** [comment]
> @stennkool Check this out: https://github.com/spatie/ray/releases/tag/1.1.2
> It looks like they are enforcing composer 2.
Good spot! I didn't realise.

**Comment by HazJ** [comment]
> @stennkool Check this out: https://github.com/spatie/ray/releases/tag/1.1.2
> It looks like they are enforcing composer 2.

Good spot! I didn't realise. It's also documentated too. Double miss!
https://spatie.be/docs/ray/v1/requirements
I wonder what possible implications will arise with using v1 with the `--ignore-platform-reqs` flag. I am personally used v2 but roll back to test.

**Comment by HazJ** [comment]
> @stennkool Check this out: https://github.com/spatie/ray/releases/tag/1.1.2
> It looks like they are enforcing composer 2.

Good spot! I didn't realise. It's also documentated too. Double miss!
https://spatie.be/docs/ray/v1/requirements
I wonder what possible implications will arise when using v1 with the `--ignore-platform-reqs` flag. I am personally used v2 but roll back to test.

**Comment by freekmurze** [comment]
I've just removed the requirement.
