### ISSUE TITLE
Can't copy or select queries

### ISSUE THREAD

**Issue by vicenterusso** [spatie/ray#657]
**Describe the bug**
Can't use "copy all" button on select queries, (`ray()->showQueries()`) and can't manually select and copy after update to 2.0.

Before the update, the copy button didn't work but **I was able** to manually select and copy. 

Edit: Can't select any text, not only queries, arrays, object, or pure string. Please fix asap 🙏🏼 

**Versions**
2.0.0

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu 21.04

**Comment by andreifiroiu** [comment]
Same on MacOs Monterey and it's quite annoying :(

**Comment by freekmurze** [comment]
We'll fix this early next week

**Comment by AdrianMrn** [comment]
Will be fixed in 2.0.1 releasing today
