### ISSUE TITLE
Unable to select/copy text from ray app

### ISSUE THREAD

**Issue by nnerijuss** [spatie/ray#660]
**Describe the bug**
Unable to select/copy any output from ray app.

**Versions**
ray app: 2.0.0

PHP version:
7.4

**To Reproduce**
1. Print any output to ray
2. Try to highlight/select output
3. Try to copy(ctrl+c/cmd+c)
4. Nothing hapens

**Expected behavior**
Should allow select and copy any text from output in ray app.

**Macbook:**
 - OS: Macos
 - Version 12.3

**Windows laptop:**
 - OS: Windows
 - Version 10
 
 **Additional context**
This behaviour appeared after upgrading ray app to 2.0 version.

**Comment by xitox97** [comment]
Same, I also having this issue.

**Comment by freekmurze** [comment]
This has been fixed in the newly released 2.0.1
