### ISSUE TITLE
Activating/checking license through a proxy

### ISSUE THREAD

**Issue by B0bbyD0llar** [spatie/ray#666]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
Cannot activate my license after update to 2.x

**Versions**
2.0.1.0

You can use `composer show` to get the version numbers of:
- spatie/ray = 1.34.1

PHP version: 8.0.15
Laravel version (if applicable): -

**To Reproduce**
1. Start Ray
2. License window appears and show "Ray has not been successful in checking your license in 7 days. Please make sure Ray can access the internet to disable demo mode."
3. Enter License key
4. click on activate
5. Error message appears: "The license server gave an unexpected response, please try again"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 
 **Additional context**
- Version 1.x works well

**Comment by freekmurze** [comment]
Could you contact info@spatie.be with this problem, mentioning the email address you are using and license key?
