### ISSUE TITLE
Cannot quit Ray on macOS

### ISSUE THREAD

**Issue by TiiFuchs** [spatie/ray#669]
**Describe the bug**
Ray cannot be closed on macOS. When triggering a shut down of the computer, Ray always stops this.
You always have to Force Quit it (before shutting down the computer).

**Versions**
Ray version: 2.0.1 
PHP version: 8.1.4

**To Reproduce**
1. Start Ray
2. Try to quit Ray

**Expected behavior**
Ray should close. So the icon in the Dock should not have a running indicator beneith it.

**Screenshots**
https://cln.sh/RVaOFu

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.3
 - System: Mac mini (M1, 2020)

**Comment by freekmurze** [comment]
I could not reproduce this on my or any of my colleagues' machines.

Could you let us know which value you're using for this setting?
![CleanShot 2022-03-30 at 09 22 55@2x](https://user-images.githubusercontent.com/483853/160774955-68c52eee-162d-461d-8a8d-23aa4057ecc1.png)

**Comment by TiiFuchs** [comment]
![CleanShot 2022-03-30 at 10 08 15](https://user-images.githubusercontent.com/1958744/160783256-ecae3161-fe12-4846-9880-17a670cd9b1b.png)

Let me know if you need anything else...

**Comment by TiiFuchs** [comment]
I reinstalled Ray now, that did the trick.
