### ISSUE TITLE
After update, server connection not triggering Ray()

### ISSUE THREAD

**Issue by spooksie** [spatie/ray#674]
**Describe the bug**
I connect to my staging and prod servers on Ray. Then trigger a ray() event on the server, nothing pops up. On local it isn't a problem.

To see Ray working, I created a new command called ray:test

```
public function handle()
    {
        ray('Is it working');
        return 0;
    }
```

When I run it locally, it works.
<img width="325" alt="image" src="https://user-images.githubusercontent.com/220888/161776658-cf4db143-a0f8-461d-9c40-f7765ff4ba37.png">

I then push to Git and deploy the exact code to my staging server. In Ray I add the staging server credentials and connect with no issues. When I trigger ray:test on the staging server, nothing appears. It used to work on older releases and seems to be happening after the latest update. 

**Versions**
2.0.1

spatie/backtrace                     1.2.1   A better backtrace
spatie/laravel-ray                   1.29.4  Easily debug Laravel apps
spatie/macroable                     2.0.0   A trait to dynamically add methods to a class
spatie/ray                           1.34.1  Debug with Ray to fix problems faster

PHP version:
8.0.x

**Expected behavior**
Expected to see a new Ray window that is connected to my server when triggering a ray() event

**Desktop (please complete the following information):**
 - MacOS: 12.3.1 
 - Version 21E258
 - Apple M1 Max

**Comment by twdnhfr** [comment]
I have the same problem
