### ISSUE TITLE
Ray steals CTRL+SHIFT+K shortcut from Sublime and Firefox

### ISSUE THREAD

**Issue by pascalchevrel** [spatie/ray#69]
**Describe the bug**
I was puzzled today at why the "delete line" shortcut in Sublime stopped working. I realized that I had installed Ray today and it is stealing this shortcut from all applications. CTRL+SHIFT+K is the standard "delete line" shortcut in Sublime, it is also the shortcut to open the browser console in Firefox. This makes it a poor choice for a shortcut.

**Versions**
Ray version (you can see this in "About Ray"): 1.0.5

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 20.10

**Comment by freekmurze** [comment]
We're going to keep it for now, as
- there are not too many people complaining (you are the first)
- the shortcut can be changed
- my guess is that there is no combination this isn't used by all Ray users
