### ISSUE TITLE
Incorrect lines of code in ray

### ISSUE THREAD

**Issue by abkrim** [spatie/ray#698]
I am working on a project, and at one point, I have noticed that the lines of code in ray do not correspond to the lines of code in the affected class in the debu process with ray.

There is a displacement.

**Versions**
Ray app version:   2.0.1
spatie/laravel-ray  1.29.6
PHP version:         8.1.5
Laravel version:     9.12.2 

**To Reproduce**
1. Work with a Job in mode async.
2. Send jobs to queue
3. On my code there're some point with ray() for get data debug.
4. See error. If ray says "PHP file class line XXX" real number line is XXX-YY 

**Expected behavior**
Let it work as usual showing the correct line

**Screenshots**

```Log::debug('failed enter '.$exception->getMessage());```
![Screenshot_20220518_065848](https://user-images.githubusercontent.com/1238625/168963220-cf61461f-6189-4074-ad7e-c2f0f52a89d6.png)
![Screenshot_20220518_070014](https://user-images.githubusercontent.com/1238625/168963543-ae440e7d-3e9f-4fb6-aa9c-12fdfa80a205.png)
![Screenshot_20220518_070054](https://user-images.githubusercontent.com/1238625/168963561-d793ce99-8b9d-4f5a-a8a1-a62ea2af1301.png)
![Screenshot_20220518_070259](https://user-images.githubusercontent.com/1238625/168963569-a05535ea-a21e-4d19-92a0-c255545aab3f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04

**Comment by freekmurze** [comment]
Could you create a minimal app that reproduces the issue?
