### ISSUE TITLE
Error invoking remote method 'connectSsh': Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by thelaarn** [spatie/ray#699]
**Describe the bug**
Cannot connect to a remote server and get the error message.
`Error: Error invoking remote method 'connectSsh': 
Error: All configured authentication methods failed` 

**Versions**
Ray version (you can see this in "About Ray"):  2.0.1

PHP version: 8.0

**To Reproduce**

1. Go to 'Servers' tab (top right corner)
2. Click on 'Add server'
3. Setup a remote server with sftp using username/password
4. Click on 'plug icon'

**Expected behavior**
make a connection to the remote server

**Screenshots**
<img width="705" alt="image" src="https://user-images.githubusercontent.com/20276610/169422272-f830cb6d-527c-4a0d-bfbf-50ff8c49db74.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.4

**Comment by jordansitbon** [comment]
UP

**Comment by jordansitbon** [comment]
I've the same problem. One of my 3 servers can't connect correctly.

Forge Ubuntu 22.04 server with PHP 8.1
macOS 12.4 - Ray 2.0.1

**Comment by mjmarley** [comment]
I see from the above screenshot you were trying to connect to WPEngine. Did you get ever this working because I have the same error. Thank you.

**Comment by thelaarn** [comment]
@mjmarley No, it still doesn't work and I've tried Digital Ocean droplet as well as Linode VPS server. All get the same error.
Hoping @freekmurze or someone form the dev team can take a look at the issue soon

**Comment by karelkangro** [comment]
I get similar error on localhost connection over SSH
so I am not able to use Ray after the last updates I believe, have not been using it for a while on my Mac OS Monterey

at the same time remote connection works with the key

also noticed some weird behaviour when tried to copy the error message to clipboard - message was changing on click from english into some other weird "language" or just characters

<img width="624" alt="Screenshot 2022-07-07 at 07 03 06" src="https://user-images.githubusercontent.com/6916288/177690972-de1ecbce-729d-436f-b30b-4bddac96024e.png">

after downloading Ray again and reinstalling this wierd language problem did not appear anymore

**Comment by hazeim254** [comment]
+1 the same issue

**Comment by jordansitbon** [comment]
UP

**Comment by ckilb** [comment]
Same here. UP

**Comment by chasewwy** [comment]
https://github.com/liximomo/vscode-sftp/issues/37#issuecomment-1120677928

This worked for me

**Comment by stiknoltz** [comment]
@chasewwy I can confirm that this solved the issue for me as well. 

It seems to be specific to a Ubuntu configuration change for Ubuntu 22.04
