### ISSUE TITLE
Clicking on arrows doesn't collapse output

### ISSUE THREAD

**Issue by slaFFik** [spatie/ray#7]
I'm talking about these arrows 🔻: 
![image](https://user-images.githubusercontent.com/282234/103912804-6aea5200-5110-11eb-8014-598bafef71c1.png)

I'm using Ray 1.0.1 on Windows 10.

**Comment by veryard** [comment]
Am using the same version on Windows 10 and the collapse works fine for me.
![dF3arFErQN](https://user-images.githubusercontent.com/3941758/103914993-8ae83880-5145-11eb-8857-26dfd4edb725.gif)

**Comment by freekmurze** [comment]
Thanks for verify @veryard 

@slaFFik Is there anything specific about your Windows version that you can share with us?

**Comment by slaFFik** [comment]
It's Windows 10 Pro 20H2, Hyper-V enabled. I'm using [OSPanel.io](https://ospanel.io/) as a web-server.

I'm not sure which information is needed. 
I had to uninstall it because it stopped receiving data from my code.

**Comment by AdrianMrn** [comment]
I can't reproduce this issue, collapsing and expanding seems to work for me on Windows.

It's possible that your composer.json requires an older version of the package that creates the Symfony dumps (I don't know which one this is off the top of my head), which could be incompatible with the up-to-date Symfony dump script (which is the one we use in Ray).

If more people run into this issue, I'll have a look into why this is happening and try to find a solution.

**Comment by slaFFik** [comment]
@AdrianMrn I still have this issue, using the latest WordPress plugin, Ray app v1.5.0 on Windows 10 Pro 20H2.

Is there anything I can help you debug this issue?

**Comment by AdrianMrn** [comment]
@slaFFik Could you run the demo app and see if you can reproduce the issue there? https://github.com/spatie/laravel-ray-demo-app

**Comment by roberttolton** [comment]
Sorry to comment on a closed issue, but I am experiencing this too.

Mac OS Catalina 10.15.7 (19H15)
laravel/framework `7.29.3`
spatie/laravel-ray `1.9.1`
spatie/ray `1.17.1`

When I click on the arrows to collapse dumped arrays etc, nothing happens.
