### ISSUE TITLE
Keyboard shortcuts do not work with accented symbols

### ISSUE THREAD

**Issue by HazJ** [spatie/ray#70]
**Describe the bug**
Keyboard shortcuts do not work with accented symbols. Tested using: ö Ö Ä ä
`Toggle visibility from anywhere`
`Clear Ray from anywhere`

**Versions**
- Ray application version: 1.0.5.0
- spatie/ray package version: 1.3.2
- spatie/laravel-ray package version (if applicable): 
PHP version: 7.4
Laravel version (if applicable): 8.20.1

**Steps to Reproduce**
1. Open up Ray application
2. Go to Preferences
3. Set the keyboard shortcuts to accented symbols
4. Close preferences (to apply changes)
5. Try to use the shortcuts

**Expected behavior**
Ray should notify and filter out accented symbols for keyboard shortcuts or support them (preferred).

**Desktop**
Edition: Windows 10 Pro
Version: 20H2
OS build: 19042.685
Experience: Windows Feature Experience Pack 120.2212.551.0

**Comment by AdrianMrn** [comment]
We're planning a complete overhaul of the shortcut input in a future version, so you can use any combination of characters you'd like. This should also solve your problem.
