### ISSUE TITLE
Title of preferances shows as "Webpack App"

### ISSUE THREAD

**Issue by RhysLees** [spatie/ray#707]
**Describe the bug**
The title of the preferences window is incorrect, at least on windows, (don't have Mac or Linux available to test)

**Versions**
2.0.1.0

**To Reproduce**
1. Open Ray
2. Goto Menu
3. Select Preferences
4. Observe the title `Webpack App`

**Expected behavior**
I believe it should either be named `Ray`, `Preferences` or `Ray Preferences`.

**Screenshots**
![image](https://user-images.githubusercontent.com/43909932/172611776-7ba890c9-aeef-42a3-8d8b-eb5a5d2c9a2b.png)

![image](https://user-images.githubusercontent.com/43909932/172612373-6da6dfd3-13ec-434c-a61f-01aebc97a780.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by RhysLees** [comment]
Still an issue

**Comment by freekmurze** [comment]
@Sam-Apostel could you take a look?

**Comment by RhysLees** [comment]
> @Sam-Apostel could you take a look?

2.1.1.0 Image here as to update from the original images :)

![image](https://user-images.githubusercontent.com/43909932/194909529-668af483-1f15-44e4-ac6e-2eb7c333318a.png)
