### ISSUE TITLE
Expanding arrays in bit larger datasets doesn't work properly

### ISSUE THREAD

**Issue by SamuelNitsche** [spatie/ray#709]
**Describe the bug**
When dumping an array with ~60 entries the arrow to expand entries is broken (as visible in the screenshot)

**Versions**
Latest (2.0.1)

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.34.5
- spatie/laravel-ray package version (if applicable): 1.29.7

PHP version:
Laravel version (if applicable): 8.1

**To Reproduce**
1. Create an array with ~60 or more entries
2. Call `ray($items)`
3. View the output and try to expand different entries

**Expected behavior**
All entries should be properly expandable.

**Screenshots**
<img width="383" alt="Bildschirmfoto 2022-06-11 um 22 13 22" src="https://user-images.githubusercontent.com/24483576/173203519-7ce4122f-29bb-4288-b044-de0123018ac0.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.4
 
 **Additional context**
-

**Comment by techno-trace** [comment]
It's same with me as well, also I thought using these on AppServiceProvider would work as it works on `dd()` for larger datasets.
@freekmurze please help on this as it becomes harder debugging large datasets without pin pointing the actual data to be dumped.

```

use Symfony\Component\VarDumper\VarDumper;
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\CliDumper;
use Symfony\Component\VarDumper\Dumper\HtmlDumper;

VarDumper::setHandler(function ($var) {
    $cloner = new VarCloner();
    $cloner->setMaxItems(-1); // Specifying -1 removes the limit
    $dumper = 'cli' === PHP_SAPI ? new CliDumper() : new HtmlDumper();

    $dumper->dump($cloner->cloneVar($var));
});

```

**Comment by techno-trace** [comment]
Hey @freekmurze, can you please help us resolve this or suggest a workaround for this issue, as this becomes harder to look in nested objects properly. This is SUPER IMPORTANT! 🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
cc: @SamuelNitsche
