### ISSUE TITLE
Path to License key 

### ISSUE THREAD

**Issue by Polfo** [spatie/ray#71]
Instructions on where to find license key after purchase could be clearer.

I had someone purchase a license for me. He used his credit card but my email adress.

I received a mail with the invoice, but no instructions on where to find the license key.
The ray app also gave no hint.
I figured out it is here: https://spatie.be/products/ray
It would be nice if the instructions in the app and the purchase mail mentioned where to find the license key.

**Comment by HazJ** [comment]
This is not a bug. Post your feedback/suggestions here: https://github.com/spatie/ray/discussions

**Comment by freekmurze** [comment]
We have some improvements around this in the pipeline. We will also mail installation instructions after purchase.
