### ISSUE TITLE
cmd+w doesn't close the window

### ISSUE THREAD

**Issue by jasonvarga** [spatie/ray#72]
**Describe the bug**
On mac, cmd+w doesn't close the window.

In #33, cmd+h was added to hide the window. Great! But now cmd+w does nothing.

**Versions**
Ray version: 1.0.5

**To Reproduce**
1. Press cmd+w

**Expected behavior**
The window should disappear.

**Desktop:**
 - OS: macOS
 - Version: 11.1
 
 **Additional context**
Ray is rad.

**Comment by freekmurze** [comment]
I just added it back, it will be part of the next release I'll do a little bit later this evening.
