### ISSUE TITLE
Can't renew my license

### ISSUE THREAD

**Issue by Thotsuya** [spatie/ray#727]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

Can't renew my ray license because whenever I hit renew License on the website, it gets stuck in this page.

![image](https://user-images.githubusercontent.com/55269430/186004807-f6e8e202-8cd8-408d-89ea-0add593d34fd.png)

**Comment by WouterBrouwers** [comment]
@Thotsuya Can you try to log out of your Spatie account and logging back in? 
You can retry the license renewal once you're logged in normally.

**Comment by Thotsuya** [comment]
Already tried. Also with different browsers. If it is of some help. here's the console log
![image](https://user-images.githubusercontent.com/55269430/186194749-34c2ca70-5385-4ab0-add8-9524cbc555a8.png)

**Comment by freekmurze** [comment]
We are not getting any similar reports, so we think it's something on your end.

Could you try with another browser, and/or on another network?

**Comment by Thotsuya** [comment]
Tried already on my phone, with a different network, on 3 different browsers and in incognito mode, but still stuck on that screen.

**Comment by freekmurze** [comment]
I've just tried in the three major browsers, and it seems to be working. My guess is that for some reason our payment provider does not accept a connection from your location. 

Unfortunately there's nothing we can do about this. Did you make purchases via Paddle yet?

**Comment by Thotsuya** [comment]
Its odd because I purchased the license a year ago from this location and had no issues.

**Comment by freekmurze** [comment]
There's a 403 in your screenshot, is that a Paddle resource?

Do you see stuff being loaded from the Paddle domain?


<img width="530" alt="CleanShot 2022-08-23 at 21 46 47@2x" src="https://user-images.githubusercontent.com/483853/186252369-d3c507c2-1a4b-4aab-ad1f-5ee38a397a30.png">
?

**Comment by Thotsuya** [comment]
![image](https://user-images.githubusercontent.com/55269430/186252999-c7c0398c-cce7-49ea-aa13-4ad6f579c84c.png)

That's the only resource loading from paddle

**Comment by freekmurze** [comment]
it's 403, so that's being blocked. You'll have to contact Paddle I'm afraid to ask why that resource is being blocked for you.There's nothing we can do at our end to solve this...

**Comment by Thotsuya** [comment]
Yes, thanks, it doesnt work on my location, asked a friend that lives in another country and it works just fine
