### ISSUE TITLE
Add compatibility for Flysystem 3

### ISSUE THREAD

**Issue by BlackbitDevs** [spatie/ray#745]
Flysystem 3 is available since almost 1 year. Currently there is no compatible Dropbox adapter for this. Could you add support for this? Actually it does not look to be that complicated according to [the release blog post](https://blog.frankdejonge.nl/flysystem-3-0-0-is-released/#what-changed) and the [update instructions](https://flysystem.thephpleague.com/docs/what-is-new/)

Actually it says 
> Since V2, V3 has been released which is backwards compatible from a consumption point of view, but it has a BC break for custom adapter implementations.

Don't know how much work this would mean...

**Comment by freekmurze** [comment]
This repo is not related to this issue.

**Comment by BlackbitDevs** [comment]
@freekmurze: Strange, this happened because I clicked "Ask a question" at https://github.com/spatie/flysystem-dropbox/issues/new/choose - probably there is a wrong link (or I do not understand the workflow).

Opened another issue at https://github.com/spatie/flysystem-dropbox/issues/88
