### ISSUE TITLE
Unable to highlight text in free form search box on macOS as window moves instead

### ISSUE THREAD

**Issue by rabrowne85** [spatie/ray#761]
**Describe the bug**
When using the free form text filter it is not possible to highlight the text using the mouse (i.e., click and drag to highlight text), as it causes the window to move instead. You have to use the keyboard only to be able to select the text.

**Versions**
Ray version: Version 2.2.1 (2.2.1)

- spatie/ray package version: NA
- spatie/laravel-ray package version (if applicable): NA

PHP version:
Laravel version (if applicable): NA

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on the magnifying glass
2. Fill in some text
3. Click the cursor at a position in the text and then whilst holding the left mouse key, try and select text to the left/right of the cursor by 'dragging' the cursor.
4. Window moves with mouse.

**Expected behaviour**
Ability to select the text using the mouse without the window moving.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Ventura 13.0.1
 
 **Additional context**
NA

**Comment by Sam-Apostel** [comment]
Fixed in Ray v2.2.2
