### ISSUE TITLE
Not compatible with php 8.0 

### ISSUE THREAD

**Issue by pintend** [spatie/ray#765]
**Describe the bug**
I installed Laravel ray in an old project which is running on php 8.0

ray says its supported by ^7.3|^8.0" but one of its dependancies were updating to require php 8.1 
https://github.com/symfony/stopwatch/commit/77dedae82ce2a26e2e9b481855473fc3b3e4e54d
**Versions**
- spatie/ray package version: 1.36.0
- spatie/laravel-ray package version (if applicable):  1.32.0

PHP version: 8.0.26
Laravel version (if applicable):

**To Reproduce**
1. install Laravel ray
2. visit any url or do something in the console

i get "Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.26."

**To Fix**
```composer require symfony/stopwatch:6.0```

**Comment by freekmurze** [comment]
Can you install one of the older package versions?

**Comment by pintend** [comment]
well after a brew upgrade im now using php 8.2 by default, but this issue technically is still an issue even if its not affecting me at the moment

**Comment by freekmurze** [comment]
I'm thinking there are older version that people can use, so that they will not bump into this issue. Closing for now.
