### ISSUE TITLE
Wrong link in "showing http requests" Tip

### ISSUE THREAD

**Issue by kismonguz** [spatie/ray#766]
In the Tip view, there is a link to the document page, but with wrong anchor.
The wrong link is: https://spatie.be/docs/ray/v1/usage/laravel#content-showing-slow-queries
The correct link is: https://spatie.be/docs/ray/v1/usage/laravel#content-showing-http-client-requests
The application version is 2.2.1

![image](https://user-images.githubusercontent.com/4705017/212339454-ddd242de-3b3b-4bde-ad95-222ad88deb50.png)

BTW: The showHttpClientRequests() function is a super nice feature!

**Comment by Sam-Apostel** [comment]
Thanks for reporting, fixed in Ray 2.2.2
