### ISSUE TITLE
Ray performance - disable hardware acceleration on Manjaro

### ISSUE THREAD

**Issue by jack932** [spatie/ray#783]
**Describe the bug**
Ray is slow. I am using xfce as a desktop environment.
The behaviour is exactly the same when i started to use rambox (based on electron) and chromium.
I was able to fix it in those cases by disabling the hardware acceleration in the settings of rambox and chromium.

For ray, i tried to find such a setting. I also tried opening the developer tools since I assume this is also an electron based application.

**Versions**
2.3.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.36.2
- spatie/laravel-ray package version (if applicable): 1.32.2

PHP version:
8.2.2 
Laravel version (if applicable):
v9.52.0

**To Reproduce**
1. Execute the following code while ray is open:
`$arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
foreach ($arr as $item) {
    ray($item);
}
`
2. Ray shows the entries.
3. The App scrolls slowly, only every 1-2 seconds the scroll position moves when for example. Hovering over the context menu of ray is only slowly expanding the submenu.

**Expected behavior**
Ray is faster.

**Screenshots**
Please see the comment https://github.com/spatie/ray/issues/783#issuecomment-1468042120 where I added a video showing the issue.

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Version 22.0.4

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.0.4
DISTRIB_CODENAME=Sikaris
DISTRIB_DESCRIPTION="Manjaro Linux"

 
 **Additional context**
For example the following commit shows an electron application which looks out for an environment variable and depending on that disables hardware acceleration:
https://github.com/faressoft/terminalizer/pull/134/files

Do you know any way to improve the performance so that i can use your great application?

Regards
Michael

**Comment by jack932** [comment]
Just in case i recorded a short video showing the behaviour:

https://user-images.githubusercontent.com/61231895/225005040-bd153f36-4163-4e60-aca4-c17673cbc85c.mp4

**Comment by turiondolby** [comment]
I'm experiencing this as well. Depending on the size of the dump, it takes more than 1 minute to scroll the app. It's really frustrating.

Windows 11 22621.1631
PHP 8.1.16
Ray 2.4.0.0
