### ISSUE TITLE
[BUG] Node Ray Has Breaking Change with Stopwatch.js

### ISSUE THREAD

**Issue by nathandaly** [spatie/ray#799]
**Describe the bug**
`npm run dev` breaks with a breaking change error:

```bash
ERROR in ./node_modules/node-ray/dist/web.esm.mjs 3904:0-61
Module not found: Error: Can't resolve 'stopwatch-node/dist/stopwatch' in '/Users/nate/Sites/Inties/github/current/tenant-cms/node_modules/node-ray/dist'
Did you mean 'stopwatch.js'?
BREAKING CHANGE: The request 'stopwatch-node/dist/stopwatch' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 1 error
```

**Versions**
Ray app version 2.4.0

Javascript version:
alpinejs-ray: ^2.0.0
node-ray: ^1.20.11

PHP version:
PHP 8.2.5
Laravel Framework 9.52.7

**To Reproduce**
```bash
npm install node-ray
npm run dev
```
Also tried with just installing `alpinejs-ray` but with the same error (maybe it uses `node-ray` under the hood).

**Expected behavior**
`npm run dev` should finish and compile all the front-end assets.

**Screenshots**
![Error Screenshot](https://i.imgur.com/AfromHK.png)

**Desktop:**
 - OS: macOS Ventura 13.3.1

**Comment by patinthehat** [comment]
This issue was resolved in the latest release.  Please upgrade to the latest version of `node-ray`.
