### ISSUE TITLE
My ubuntu server don't send payload to my app

### ISSUE THREAD

**Issue by allanmcarvalho** [spatie/ray#802]
**Describe the bug**
My ray app isn't showing payload from a Laravel app installed at a Ubuntu server on Digital Ocean. It connect with the server (showing a ray icon), but nothing happens. On server I enabled as "yes" the sshd  "GatewayPorts" and restarted it. The documentation about how to configure it (server feature) is very poor and don't have many examples on the internet. So I don't know what is wrong.

**Versions**
APP: 2.5.1

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.37.2
- spatie/laravel-ray package version (if applicable): 1.32.4

PHP version:
8.2.7

**Comment by allanmcarvalho** [comment]
![Captura de Tela 2023-06-12 às 10 31 46](https://github.com/spatie/ray/assets/12012197/be8cee55-2f6a-45a6-afc4-38aa7d40fe68)

**Comment by brandon-9** [comment]
Exact same issue here. Enabled the server sshd setting as mentioned. 

App: 2.5.1
Spatie/ray package: 1.37.2
Laravel-Ray package: 1.32.2

Also on DO server. Ubuntu 20.04

**Comment by allanmcarvalho** [comment]
Sorry about that, but is very sad. We paid for this software, a announced feature doesn't work, the documentation about is very poor and the support is ignoring us... at least a feedback like "sorry, we will fix this soon". But nothing until now! I am very disappointed!

**Comment by brandon-9** [comment]
I was able to get another DO server working a few months back using this as a reference: https://github.com/liximomo/vscode-sftp/issues/37

But unfortunately I don't remember exactly what ended up making it work - and everything I've tried again hasn't been successful. 

To be fair, I'm fairly sure it's a server setting/firewall - but it would be really nice for them to update documentations with common issues on server side. Especially as I'm sure a simple DO droplet run via Forge is very common in this community.

**Comment by allanmcarvalho** [comment]
Works like a charm... But why this isn't mentioned on docs? I think that some improvements are welcome to help others users! Thanks for you help!

**Comment by stephenfeather** [comment]
I wasted SO much time trying to get Ray to run before this finally surfaced in a google search.
Did an 'export RAY_ENABLED=true' before trying to run the cli phar and bingo.

Thanks @brandon-9 !

**Comment by brandon-9** [comment]
> I wasted SO much time trying to get Ray to run before this finally surfaced in a google search.
> 
> Did an 'export RAY_ENABLED=true' before trying to run the cli phar and bingo.
> 
> 
> 
> Thanks @brandon-9 !

Glad it helped!!

**Comment by freekmurze** [comment]
Feel free to send a PR to the docs to make this more clear 👍

**Comment by allanmcarvalho** [comment]
thanks for you late answer @freekmurze. The day that ray become a opensource software, I will send a PR to solve this. But in a paid software, I believe that is the minimum that the seller can do to it's clients. Have a good weekend.
