### ISSUE TITLE
App can not be closed if license expired

### ISSUE THREAD

**Issue by alex-eftimie** [spatie/ray#805]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
If you start the app after your license expired, once the licensing window appears you can no longer quit the app except from the Activity Monitor.

**Versions**
Ray version (you can see this in "About Ray"): 2.5.1

You can use `composer show` to get the version numbers of:
- spatie/ray package version: spatie/ray                                1.37.2
- spatie/laravel-ray package version (if applicable): spatie/laravel-ray                        1.32.4

PHP version: 8.2.7
Laravel version (if applicable): Laravel Framework 10.13.5

**To Reproduce**
1. Open ray with an expired license.
2. Send something to the window until license window appears.
3. Try to exit ray.

**Expected behavior**
Can quit the app.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 22] 13.0.1 (22A400
 
 **Additional context**

**Comment by marijnbent** [comment]
I can second this. Not with an expired license, but with a valid one that I can't activate. #812
