### ISSUE TITLE
adding the remote server didn't save it

### ISSUE THREAD

**Issue by tonkoshkurik** [spatie/ray#818]
When I try to add the remote server and pressing save button, changes didn't apply.  I can connect with the username@host via ssh, and before I was able to debug from this server and ray but from the old computer.

**Versions**
Tried to reinstall the app version 2.3.0 also latest 2.5.1 having the same issue

PHP version:
local 8.2 and 7.4 is working with ray. On the remote is 7.4, but I can't even connect so don't this it's matter that much

**To Reproduce**
1. Go to Serves
2. Click on 'Add server'
3. filling label, host, port, username and ssh key path 
4. Pressing save, and the window closed, but there is nothing in the list,

**Expected behavior**
The server being added and I'm able to connect and debug from the remote. 

**Screenshots**

![Screenshot 2023-08-18 at 15 45 47](https://github.com/spatie/ray/assets/13135755/6d9e8e27-68e8-4463-8197-344b05b2b435)

**Desktop (please complete the following information):**
 - OS: [13.5 (22G74)]
 Apple M1 Pro

**Comment by tonkoshkurik** [comment]
Pls help or suggest the solution

**Comment by Sam-Apostel** [comment]
hi @tonkoshkurik 

I can't seem to reproduce this issue on my end.
Is this issue still persisting the same on the latest version of the Ray app?
Could you verify if the file at `~/Library/Application Support/Ray/preferences.json` contains any items in the `servers` array?

**Comment by tonkoshkurik** [comment]
Hi @Sam-Apostel 
Seems like the issue resolved after recent update. Thank you
