### ISSUE TITLE
Error Debug "Query Something went wrong here. Reload Ray to try again."

### ISSUE THREAD

**Issue by abcprintf** [spatie/ray#820]
**Describe the bug**
I updated the ray and it crashed.
[2.6.2.0] - Error Debug Query "Something went wrong here. Reload Ray to try again."
```sh
$query->ray()->get();
```
The previous version works normally.

**Versions**
Ray version : 2.6.2.0
- spatie/ray package version: 1.37.2
- spatie/laravel-ray package version : 1.32.6

PHP version:
Laravel version: 7.4.33

**Screenshots**
![2023-08-22_10-40-41](https://github.com/spatie/ray/assets/8300694/dd228498-da61-45ce-b994-98a8c51aba20)

**Desktop:**
 - OS: Windows 11

**Comment by Sam-Apostel** [comment]
Hey  @abcprintf 

We updated the version of [sql-formatter](https://github.com/sql-formatter-org/sql-formatter) which is more strict in which SQL dialects it parses by default. What SQL dialect are you using?
