### ISSUE TITLE
After update Ray, stop work click on alert and PhpStorm

### ISSUE THREAD

**Issue by abkrim** [spatie/ray#821]
Today my ray app update to 2.6.2
After this, ray show debug, but click on file and line number not works.

Ra version 2.6.2 (2.6.2)

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.37.2
- spatie/laravel-ray package version 1.32.6 

PHP version 8.2
Laravel version (if applicable): 10.19.0

1. Put a ray in test
2. Show alert in ray app.
3. Click on [BouncerSeeder.php:46](phpstorm://open?file=%2FUsers%2Fabkrim%2FSites%2Fsitelight%2Fdatabase%2Fseeders%2FBouncerSeeder.php&line=46)
4. Ray app not goes to file and line. Any action. 

Restart my Mac for clean memory and start a new day with love.

Well, I expected it to work like yesterday. That when it shows me an alert and I want to see the code of that alert, click and go to the file in phpstomr, whether it is open or closed.

It has worked that way for a couple of years.

macOS X 13.4.1 (c) (22F770820d) M1 Pro
![Sin título](https://github.com/spatie/ray/assets/1238625/78f9450e-be10-49ca-917c-b449a8b15855)

**Comment by Sam-Apostel** [comment]
Hey @abkrim 

The latest Ray release significantly changed how link clicks are handled to adress some security concerns, this change must have broken the “open in IDE”-links.

I will look into releasing a fix asap.

**Comment by abkrim** [comment]
A lot of thanks.
