### ISSUE TITLE
Not logging anything after last update

### ISSUE THREAD

**Issue by alejandrotrevi** [spatie/ray#822]
**Describe the bug**
After updating to the most recent version it just stopped working, talking to my coworkers it seems the issue is not happening just to me

**Versions**
Ray version: 2.6.4.0
- spatie/ray package version: 1.37.2
- spatie/laravel-ray package version (if applicable): 1.32.6

PHP version: 8.2.7
Laravel version (if applicable): 10.14.1

**To Reproduce**
1. Install ray on a Windows machine
2. Install on a fresh new Laravel project
3. Make a `ray` call
4. Nothing should show on the ray app

**Expected behavior**
Something should dump/show on the ray app after calling `ray('something')`

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 
 - Version 22H2
 
 **Additional context**
~~No idea if this is specific to Windows, hapenning to more people, **just tried on an old version of ray (2.5.1)** and in a different project, and it seems it's still not logging anything, the other project is using:~~

- ~~spatie/laravel-ray package version (if applicable): 1.32.6~~
- ~~spatie/ray package version: 1.37.2~~

### Update

Just tried version 2.5.1 but i deleted the ray folder in the AppData/Roaming, that seems to solve the issue meaning **it is related to the latest version** (2.6.4)

**Comment by twocngdagz** [comment]
Had the same issue as well, after doing the update this morning, nothing shows in ray

**Comment by Sam-Apostel** [comment]
hi @twocngdagz 
Assuming you haven't reset your appdata folder yet, can you check inside of the Ray app what port ray is listening on?

**Comment by twocngdagz** [comment]
@Sam-Apostel 

How do I do that?

**Comment by Sam-Apostel** [comment]
> How do I do that?

By going to the Ray settings panel and scrolling to the Communication section at the bottom.

**Comment by Sam-Apostel** [comment]
hey @twocngdagz 

Have you been able to check/reset your port?
Setting the port in the Ray app back to `23517` seems to have been the problem others were having. Let me know if I can assist you in any way.

**Comment by twocngdagz** [comment]
@Sam-Apostel 

Yes my current port is 23517

**Comment by damms005** [comment]
It's sad this issue is not fixed.

Not a happy thing when one pays for a tool and it suddenly stops working and no one prioritizes. @freekmurze I also have similar issue with #892 can you help please?

**Comment by alejandrotrevi** [comment]
> It's sad this issue is not fixed.
> 
> 
> 
> Not a happy thing when one pays for a tool and it suddenly stops working and no one prioritizes. @freekmurze I also have similar issue with #892 can you help please?

This issue is fixed you can read my update for info, please open a new one, because is not related to this.
