### ISSUE TITLE
Ray stopped working after update.

### ISSUE THREAD

**Issue by dean26** [spatie/ray#823]
**Describe the bug**
Ray stopped working after update. e.g. ray()->showQuries() doesn't show anything in ray.

**Versions**
Ray version (you can see this in "About Ray"): 2.6.4

**Desktop (please complete the following information):**
 - OS: Windows (WSL Ubuntu 20)
 - Version 10

**Comment by cbaconnier** [comment]
I had the same issue on (Arch) Linux
I solved it by deleting the folder `~/.config/Ray`

**Comment by Sam-Apostel** [comment]
Hey @dean26 and @cbaconnier 

Could you check if the port in the Ray app settings is still correct?
A bug in v2.6.2 and v2.6.3 might have changed the default port for the app if it failed to start listening on it.

The default port is 23517, if you didn't change this, you can set it back to 23517 manually in the settings.

**Comment by pvullioud** [comment]
Same issue her, the port change to 23518 after the update. I set it back to 23517

**Comment by dean26** [comment]
I changed port from 23518 to 23517 and it works now.

**Comment by Sam-Apostel** [comment]
Glad to hear this indeed resolved your issues.
