### ISSUE TITLE
Ray goes into trial mode every morning and after updates

### ISSUE THREAD

**Issue by jjteong** [spatie/ray#827]
Every morning when I start using Ray and after 10 log items, it will tell me it's used 10/10 log items and that it is in Trial Mode.
The trial message at the bottom doesn't display before I've used 10 log items. I then have to decouple my license, quit Ray, and then reenter my license again for the day's use.

It also goes into trial mode just after updating. This morning I'd already decoupled and recoupled my license to get it working, then there was an update from 2.6.5 to 2.6.7 and now I have to decouple and recouple my license again only this time it displays the message saying I've used 1/10 log items and that it is in Trial Mode.

This started happening after one of the updates (not the latest one).

**Versions**
2.6.5 to 2.6.7

- spatie/ray package version: 1.37.2
- spatie/laravel-ray package version (if applicable): 1.32.5

- PHP version: 7.4.26
- Laravel: 8

 - OS: Windows 11 Pro
 - Version 10.0
 
 **Additional context**
I have tried uninstalling and re-installing Ray to solve the problem and I'm unsure of what else I can do to try and solve the problem myself.

**Comment by jjteong** [comment]
This morning the Trial Mode message displayed after the first log to Ray instead of the 10th. Even though the License information section is filled out. This is slightly different to previous mornings. Does anyone have any ideas about how I might go about solving this myself? Is there anyone out there?

**Comment by jjteong** [comment]
Last night I let my computer run all night to see if that kept my license activated. It didn't. Trial mode again.

**Comment by genesiscz** [comment]
I can't even get it out of the trial unfortunatelly.

![image](https://github.com/spatie/ray/assets/1512353/d6bcf7ac-020b-4769-8353-850a16255fd9)

**Comment by jjteong** [comment]
I left my computer on all weekend. And this morning (Monday 4th September) it's working. I didn't have to decouple my license and reconnect it again. I don't know why. I haven't changed anything on my end other than updating my Adobe software.

So, I rebooted my computer to see if that would break it again. It didn't, it's still working correctly now.

This is probably something related to _my computer_ rather than an issue with Ray. Just a hunch. Still, Ray is the only thing I was having trouble with. I thought it might be a networking issue firewall thing or something else beyond my own ability to diagnose. So I can understand if the Ray team are unable to help with this issue but I really need some direction on how to find the source of the problem if anyone out there has a clue for me. Thanks.

**Comment by genesiscz** [comment]
Well it is back. It even thinks it has a valid licence in the preferences:

![image](https://github.com/spatie/ray/assets/1512353/1157b797-a438-472f-8e04-0367fd2bbe92)

**Comment by jjteong** [comment]
> Well it is back. It even thinks it has a valid licence in the preferences. After clicking "activate licence" again I got the same unexpected server error again. I had to remove the alias in Spatie profile again and clicked "Activate licence" again to make it work.
> 
> ![image](https://user-images.githubusercontent.com/1512353/265526514-1157b797-a438-472f-8e04-0367fd2bbe92.png)

Yes, that is exactly what mine looked like every morning. The license was set, and it said 10/10 log items were used.
It's still working today after leaving my computer on over the weekend. I'm not saying that's the solution, I honestly don't know why it's working now.

**Comment by LlamaDuckGoose** [comment]
I was running into a similar issue and noticed when I did the update it didn't seem to fully uninstall the old version from windows. Under windows Add or Remove programs, it had both listed, ended up removing both and reinstalling it and haven't run into the issue again.

**Comment by jjteong** [comment]
> I was running into a similar issue and noticed when I did the update it didn't seem to fully uninstall the old version from windows. Under windows Add or Remove programs, it had both listed, ended up removing both and reinstalling it and haven't run into the issue again.

Oh yeah! I just checked mine and two are listed there Ray 2.6.4 and Ray 2.6.7 but it won't let me uninstall 2.6.4 "Cannot find Uninstall Ray.exe"

**Comment by LlamaDuckGoose** [comment]
After restarting restarting windows the old one was there again but I haven't run into the trial mode issue again. seems like the uninstaller isn't removing the entries from the registry correctly but I guess doing a reinstall ended up fixing the other issue

**Comment by jjteong** [comment]
My issue has returned today but this time it was working all morning then out of the blue just now it went back to trial mode. I don't know how to get rid of the 2.6.4 installation that is listed. The crickets 🦗 from the Ray team have me worried and I don't see any other avenues for support other than GitHub issues.

**Comment by Sam-Apostel** [comment]
I just published a fix for the license issues. v2.6.8 should not go into trial mode anymore.
On top of that, going to https://spatie.be/profile/purchases and removing the activations from a specific ray license should also resolve the issues you are experiencing.

What happened was, the 'activate on this device' button was creating a new activation, when you ran out of seats (max 2 activations) the error that was returned was swallowed because Ray didn't send the correct headers.

If you run into this issue again, feel free to tag me in your ticket for a faster response.

@jjteong @LlamaDuckGoose @genesiscz
