### ISSUE TITLE
Ray stopped working, showing just a black window

### ISSUE THREAD

**Issue by giovanniledda** [spatie/ray#840]
After an OS update, Ray stopped working.

It displays a black screen (screenshot below). 

There is no way to close it (I've to force quit).

I tried to uninstall and complete a fresh installation without success.

I've also rebooted the OS.

**Versions**
Ray version::  2.6.7 (2.6.7)

With composer:
spatie/laravel-ray                     1.33.0
spatie/ray                                  1.37.6

PHP version: 8.1.22
Laravel version: 10.22.0

**Screenshots**

<img width="1422" alt="ray" src="https://github.com/spatie/ray/assets/1835395/34a9b9ae-2218-47bc-9645-a43212d517f9">

**Desktop:**
 - OS:  macOS
 - Version: mac OS Ventura 13.5.1

**Comment by agnonym** [comment]
Same here on macOS Ventura 13.5 (after standard update and fresh install)

**Comment by Sam-Apostel** [comment]
Ventura 13.5.2 was released today. Can you verify if this update fixes the Ray app?

**Comment by agnonym** [comment]
After Ventura 13.5.2 upgrade and Ray 2.6.9 update, it's all good now 👍

**Comment by giovanniledda** [comment]
Same for me, I'm gonna close the issue.
