### ISSUE TITLE
Latest update broke ->color()

### ISSUE THREAD

**Issue by briandswan** [spatie/ray#846]
**Describe the bug**

**Versions**
2.7.5.0

You can use `composer show` to get the version numbers of:
spatie/laravel-ray                 1.33.0    Easily debug Laravel apps
spatie/ray                         1.38.0    Debug with Ray to fix problems faster

PHP version:
PHP 8.2.10 (cli) (built: Sep  7 2023 06:01:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.10, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

Laravel version (if applicable):
Laravel Framework 9.52.10

**To Reproduce**
Choose your output to send to Ray.
Set it up and send it to a color tab:
ray(__METHOD__ . ' :: ' . __LINE__ . " | Stats.", [
            'data1' => Queue::get(),
            'data2' => Stats::get(),
        ])->green();
Nothing outputs on the green tab.

**Expected behavior**
Output should appear on the green tab.

**Screenshots**
![image](https://github.com/spatie/ray/assets/19894586/39d41e25-3a0a-49e5-b6b9-b1b482c416ce)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 10.0.022621 Build 22621
 
 **Additional context**
Using Docker set up with Docker Engine v24.0.5 (Ubuntu 22.04.2 LTS (Jammy Jellyfish)
Linux version: Debian GNU/Linux 12 (bookworm)

**Comment by Sam-Apostel** [comment]
Can you verify for me if the item you send did come though without the color added?
This seems to be working for me

**Comment by briandswan** [comment]
I uninstalled and reinstalled and it seems fine now.  Strange.  Thank you!
