### ISSUE TITLE
Ray doesnt showcase Request Class in Laravel Nova Resources

### ISSUE THREAD

**Issue by Montrii** [spatie/ray#847]
**Describe the bug**
When i try to "print" a Request (That can be **any** Request inherited class meaning: `NovaRequest, Request, ResourceCreateOrAttachRequest` etc.) object within Laravel Ray within Laravel Nova, ray does not showcase anything about that object.
It does **not** print `null or undefined`, the object is initialised and does work normally.
When i parse the object into variables using `parse_str`, i can then sorta view the object.

**Versions**
2.7.5

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.38.0
- spatie/laravel-ray package version (if applicable): 1.33.0

PHP version: 8.2 (Running Laravel app on Laravel Herd)
Laravel version (if applicable): v10.22.0
Laravel Nova version (additional): 4.27.12

**To Reproduce**
1. Create a Eloquent Model, Factory, Seeder and Migration for a table in Laravel.
2. Create a Laravel Nova Ressource for the created Eloquent Model
3. Create Fields for the Model.
4. Try to print the $request variable with Ray in either the` fields(NovaRequest $request)` methods directly or in any method that gets a Request instance passed (`such as ->default(callback(ResourceCreateOrAttachRequest $request)`)
5. The error occures

**Expected behavior**
Request object should be printed normally into ray without issues.

**Desktop (please complete the following information):**
 - OS: macOS
 - Ventura 13.5
 
 **Additional context**
The issue seems to be related to the project? Using a different Laravel Nova Project with the following versions (Laravel: v.9.50.1, Nova: 4.21.0, spatie/ray: 1.36.0, spatie/laravel-ray: 1.32.1) causes no issue and returns expected behaviour. Printing any Request object in lets say a Controller via a Route works PERFECTLY fine. It only occurres in Laravel Nova Ressources.

**Comment by Vestibule** [comment]
Same problem here. No way to dump a Nova request through Ray.

**Comment by patinthehat** [comment]
@Montrii Does this occur if you only install the ray package  (and not laravel-ray)?
