### ISSUE TITLE
Ray not compatible with MacOS Sonoma

### ISSUE THREAD

**Issue by fernandoacosta** [spatie/ray#854]
I've just upgraded my Mac OS to Sonoma and Ray can't be installed. The OS says it is not compatible.

Mac OS Sonoma (14.0)
Ray version 2.7.5.

To reproduce, upgrade mac OS and try to install current Ray version.

**Comment by freekmurze** [comment]
It is working perfectly here. Could you try re-downloading it from our site?

**Comment by noge075** [comment]
For me it says:
![image](https://github.com/spatie/ray/assets/16837514/3f482a1f-f257-4133-a68d-67cb1a0c2f1a)
How can I make it work?
