### ISSUE TITLE
Ray not responding after a large dump and refused to clear logs on restart

### ISSUE THREAD

**Issue by digitlimit** [spatie/ray#861]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
I am using Ray in a Laravel application in Ubuntu 22.04.
I dumped an array of over 10000 rows

```
 ray()->clearAll();
 ray($array);
```

I think the array was sent multiple times on page reload, now Ray has frozen and cannot be scrolled.
I have tried restarting Ray by quitting and reopening Ray, however, the logs are still stuck in there and refuse to clear.

**Versions**
2.7.5

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version: 7.4
Laravel version (if applicable): Laravel 7

**To Reproduce**
N/A

**Expected behavior**
Clear all logs and become responsive, and scroolable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 22.04
 
 **Additional context**

**Comment by patinthehat** [comment]
@digitlimit When using Ray on Linux, I've thought that I terminated the application but it was still in fact running and did not exit.  Is it possible this is what you're running into? 
You can try killing the process manually with `pkill ray` (assuming the binary is named ray).  Let me know if this helps.
