### ISSUE TITLE
No data to Ray after new SoapClient in PHP

### ISSUE THREAD

**Issue by Adrian-MID** [spatie/ray#863]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
After creating a new PHP SoapClient, data stops posting to the Ray App. Example code and output to Ray have been provided in a screenshot below. All instances of ray after ray('test3'); do nothing like they aren't there.

**Versions**
Ray version (you can see this in "About Ray"):
Windows - 2.7.5.0
spatie/backtrace                  1.5.3              A better backtrace
spatie/macroable                  2.0.0              A trait to dynamically add methods to a class
spatie/ray                        1.40.0             Debug with Ray to fix problems faster

PHP version:
Laravel version (if applicable): 8.0.7

**Expected behavior**
I would expect Ray to keep working.

**Screenshots**
![image](https://github.com/spatie/ray/assets/77190026/fb8ba18e-b4eb-4c73-8bd6-9b717e2d82b4)
![image](https://github.com/spatie/ray/assets/77190026/835484bc-4732-4a9e-808c-1cf5e10d0db3)

**Desktop (please complete the following information):**
 - Windows 11
 - 
 **Additional context**
The script keeps running normally, I can echo and print data to the screen, it just doesn't go to ray.

**Comment by patinthehat** [comment]
@Adrian-MID Can you provide a snippet of code instead of a screenshot, a sample project that shows the issue, and/or unit tests that show the issue you're experiencing? Thanks! :+1:
