### ISSUE TITLE
Emails that contain a link with an ampersand are not rendering correctly

### ISSUE THREAD

**Issue by travisricks** [spatie/ray#877]
**Describe the bug**
I'm using Ray to preview mails sent by my application. After triggering a Jetstream email verification mail, the verification link rendered inside of Ray is not correct.

Expected url: `http://forum.test/email/verify/1/1e9bb8c1adf3a4e8ae985e4574a0a16ae1b8feb4?expires=1701572264&signature=bfea3a16f5b89bc753278e3b7a143e626ac9185f827ad977bac2a47caed47c49`
Rendered in Ray: `http://forum.test/email/verify/1/1e9bb8c1adf3a4e8ae985e4574a0a16ae1b8feb4?expires01572264&signature?ea3a16f5b89bc753278e3b7a143e626ac9185f827ad977bac2a47caed47c49`

The bit after `expires` seems to be rendering incorrectly.

**Versions**
Ray version (you can see this in "About Ray"): 2.7.5

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.40.1
- spatie/laravel-ray package version (if applicable): 1.33.0

PHP version: 8.2.13
Laravel version (if applicable): 10.34.2

**To Reproduce**
1. Set up Ray to preview mails
2. Trigger Jetstream email verification mail to be sent
3. Try copy/pasting the verification url at the bottom of the email
4. See 403 Invalid Signature error in the browser (because url has a space and timestamp is invalid)

**Expected behavior**
The link should be copyable from Ray to be used in the browser

**Screenshots**
![Ray-2023-12-03-000068@2x](https://github.com/spatie/ray/assets/289841/ba6111ef-e948-4654-9ead-82443b8eafa3)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.1.1
 
 **Additional context**
I was also unable to click the button in the email, is this expected?

**Comment by philipmclifton** [comment]
I am also experiencing this issue. Link is not clickable.

**Comment by Nutickets** [comment]
This one is really getting in the way of local email testing, I think this is a semi-recent issue as I recall our signed URLs working in ray previously.

**Comment by jonneroelofs** [comment]
I have just spent several hours debugging this issue before I came here to report it and found this issue.
A fix would be most welcome!

In my case the '=' after signature is rendered as '?' breaking the signed Url.

Original dumped before the markdown is converted:
![image](https://github.com/spatie/ray/assets/20800818/875b781a-50cb-4c30-90db-dab394cad100)

Rendered in ray:
![image](https://github.com/spatie/ray/assets/20800818/f7e7c748-ba43-44fa-97ad-23b240691917)

Rendered in an actual email:
![image](https://github.com/spatie/ray/assets/20800818/3a4f7c43-68ea-45e7-9db2-65e090e1a603)

Not sure if this is relevant but in my case these are transactional mails sent with spatie mailcoach v6.

**Comment by 1stevengrant** [comment]
I wonder if this is what I'm running into with #907

**Comment by travisricks** [comment]
I see this was closed because of staleness but has it been fixed?

**Comment by freekmurze** [comment]
This one was fixed indeed.
