### ISSUE TITLE
Linux: Clicking "view" button in notification doesn't do anything

### ISSUE THREAD

**Issue by patinthehat** [spatie/ray#88]
**Describe the bug**
When a notification payload is displayed by Ray, clicking the "view" button does not do anything.

**Versions**
- spatie/ray package version: 1.3.7
- Ray app version: 1.0.7
- PHP version: 7.4.13

**Sample Code**
```php
ray()->notify('hello world');
```

**To Reproduce**
1. Run the sample code
2. Click on 'view' in the notification that is displayed
3. Nothing happens

**Expected behavior**
Expected behavior is that clicking the "view" in the notification will open the Ray window and display/highlight the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/5508707/104109315-9dc05180-529a-11eb-824e-700ef1526e20.png)

**Desktop (please complete the following information):**
- OS: Ubuntu _(XFCE window manager)_
 - Version: 20.04

**Comment by freekmurze** [comment]
Could you post a screenshot of that notification?

**Comment by patinthehat** [comment]
@freekmurze 
Sorry about that, I accidentally clicked "submit" before I was done authoring the issue.

**Comment by freekmurze** [comment]
Do all other Linux notifications have a "View" button? If not, I'll research how to remove "View" from ours.

**Comment by patinthehat** [comment]
No.  Running the following command in bash displays a notification without a "view" button:

```bash
notify-send 'test message'
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/5508707/104109476-4a4f0300-529c-11eb-85f0-23eef1ac13b0.png)

**Comment by GraxMonzo** [comment]
Same on Windows

**Comment by GraxMonzo** [comment]
It also seems that notifications on Windows don't have icon and proper title
![image](https://user-images.githubusercontent.com/11737104/104185772-a2723a80-543f-11eb-9ba9-4b22086554cf.png)

**Comment by AdrianMrn** [comment]
Thanks for the report! This should be better in 1.0.8 (will release later tonight). Please let me know if the problem persists afterwards!

**Comment by GraxMonzo** [comment]
@AdrianMrn Thanks for update. Problem with no interaction was resolved. 😁

**Comment by patinthehat** [comment]
I can also confirm that this issue is resolved.  Clicking "view" now opens the Ray window.
