### ISSUE TITLE
Can't login to recover my license

### ISSUE THREAD

**Issue by wrtisans** [spatie/ray#886]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/ray/issues) or in [the discussions](https://github.com/spatie/ray/discussions).

If you are having troubles connecting your project to Ray, please check [our docs](https://spatie.be/products/ray) first, especially the configuration and environment specific configuration sections.

**Describe the bug**
im trying to activate in a new Mac my license, I've used Apple ID for the purchase but I can't login anymore, please help! 

**Versions**
2.7.5

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version:
Laravel version (if applicable):

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 
 **Additional context**

**Comment by freekmurze** [comment]
Hi, please contact support@spatie.be for this. If possible forward your original purchase mail too.
