### ISSUE TITLE
Updating to 2.8.0 broke ability to connect to servers

### ISSUE THREAD

**Issue by radoslavkuchar** [spatie/ray#915]
**Describe the bug**
My saved servers have been removed, and after trying to add new server, nothing happens.

**Versions**
Ray version (you can see this in "About Ray"):
2.8.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: not relevant to this case, as I'm unable to create a server to connect to at all
- spatie/laravel-ray package version (if applicable): not relevant to this case, as I'm unable to create a server to connect to at all

PHP version:
Laravel version (if applicable):

**To Reproduce**
Updating to 2.8.0

**Screenshots**
<img width="780" alt="image" src="https://github.com/spatie/ray/assets/85932040/238f5f15-4272-40a4-b62e-4632511372ed">

**Desktop (please complete the following information):**
 - OS: macos
 - Version: 14.4.1

**Comment by mpiosik** [comment]
I am experiencing the same issue after updating to version 2.8.0 (macOS 14.3.1).

**Comment by cornelRaiu** [comment]
Not seeing this with v2.8.0 on macOS 14.5

**Comment by freekmurze** [comment]
We're actively working on a fix for those who encounter this bug.
