### ISSUE TITLE
v2.8.0: JavaScript error after waking computer from sleep

### ISSUE THREAD

**Issue by cornelRaiu** [spatie/ray#916]
**Describe the bug**
After waking my computer up, I started getting this error since v2.8.0:

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Object has been destroyed
at ct (/Applications/Ray.app/Contents/Resources/app.asar/dist/main.js:8:100911)
at Screen.<anonymous> (/Applications/Ray.app/Contents/Resources/app.asar/dist/main.js:8:100825)
at Screen.emit (node:events:402:35)
```

It's multiple instances of the same error. For example I got 4 after the computer went to sleep for about 20 minutes. But accumulated 40+ overnight.

**Versions**
Ray version (you can see this in "About Ray"): 2.8.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: irrelevant
- spatie/laravel-ray package version (if applicable):  irrelevant

PHP version:
Laravel version (if applicable): irrelevant

**To Reproduce**
1. Open the Ray app
2. Connect it to a server. In my case it's a Parallels machine with Vagrant and Homestead on top
3. Allow the computer to go into sleep mode for 10+ minutes
5. On wake up you will get the same error as above.
6. After closing the error, depending on how long the computer was asleep, it will pop up more more instances of the same error.

**Expected behavior**
Obviously would expect this to not happen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Sonoma 14.5
 - Chip: M1 Max
 
 **Additional context**
Started happening after updating to v2.8.0 yesterday

I will also add a screenshot of the error next time I see it.
Also, I will try to disconnect it from the server before going to sleep and see if it still occurs then.

**Comment by cornelRaiu** [comment]
Here is a screenshot of the error.

![image](https://github.com/spatie/ray/assets/6166479/e8b76ff9-8780-4545-8bf3-356e5bc0b9ad)

**Comment by wkhayrattee** [comment]
I was getting this same error on the free-version - like a dozen of them on each call. 
It went away after I activated Ray with a license. Haven't had it since.

I tested on two different macbooks (M3 & Intel with latest macOS version to-date), same behaviour.

**Comment by cornelRaiu** [comment]
On my end it was activated since day 1.

I just tried to remove the license and reactivate. No luck.
Then I tried to uninstall the app and reinstall. No luck.

**Comment by cornelRaiu** [comment]
v2.8.1 fixed it.
