### ISSUE TITLE
I can't exit the program

### ISSUE THREAD

**Issue by nenadcvele** [spatie/ray#919]
When I open the app, I can use it normally, minimize, minimize to tray, capture... If I try clicking on exit (from tray) or Menu->Quit Ray it closes the window but the icon stays in the tray and I can see Ray in the task manager with 4 processes.

Ray version (you can see this in "About Ray"): 2.8.1

 - OS: Windows 11
 - Version: 23H2 Build 22631.3593

**Comment by chrispeeters** [comment]
I experience the same issue. I can't quit Ray. The only way I can do it is by killing Ray via the Activity Monitor
