### ISSUE TITLE
RemainingRayCallRule with php 8.4

### ISSUE THREAD

**Issue by striderxfossility** [spatie/ray#953]
**Describe the bug**
When i run phpstan with php 8.4 with the rule RemainingRayCallRule, it breaks

Internal error: Call to undefined method PhpParser\Node\Expr\Variable::getParts() while analysing file

**Versions**
"spatie/ray": "^1.41",

PHP version: 8.4

**Expected behavior**
To not give errors

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.4 (23E214)

**Comment by sweptsquash** [comment]
Hey @striderxfossility try updating to the latest tagged version [1.41.4](https://github.com/spatie/ray/releases/tag/1.41.4) this should resolve your issue.
