### ISSUE TITLE
Unexpected `null` in the caller method name

### ISSUE THREAD

**Issue by Mamaduka** [spatie/ray#99]
**Describe the bug**
The unexpected `null` is printed before the caller's name.
 
**Versions**
Ray version (you can see this in "About Ray"): 1.0.8

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.3.7
- spatie/wordpress-ray plugin version: 1.0.0 

PHP version: 8.0

**To Reproduce**
Place `ray()->caller();` inside  the function and check the Ray output. In my case, it's a simple namespaced function.

**Expected behavior**
Print caller name without a `null`.

**Screenshots**
![ray-null-prefix](https://user-images.githubusercontent.com/240569/104130878-9e391500-538c-11eb-8050-eeab348391c8.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.6

P.S. Thanks for the amazing app.

**Comment by freekmurze** [comment]
I've noticed this myself and this is on my list to fix very soon.

I'm not primarily working in WordPress and it gives me great joy that you got this up and running in WordPress.

I'm also looking for the best way to install this in WordPress. How did you install it? This might be helpful for me to know, when I create WordPress specific docs.

**Comment by Mamaduka** [comment]
I just cloned the plugin repo into the `plugins` directory. 

I think most people will use WP UI or WP CLI [command](https://developer.wordpress.org/cli/commands/plugin/install/) to install the plugin after it is available on the WP.org repository.

**Comment by freekmurze** [comment]
> I just cloned the plugin repo into the plugins directory.

If this is something that is typically done in the WordPress community, could you PR the step that you performed in de installation section of our docs?

**Comment by freekmurze** [comment]
You should also so know that I aim to add more WordPress specific functionality. I just need to figure out the best way to detect when a query is executed in WordPress, when an event is fired, etc... 

If you already know a good way and know how to do this, I'd appreciate a PR at the wordpress-ray repo. Of course, don't feel yourself obliged in any way.

**Comment by Mamaduka** [comment]
> If this is something that is typically done in the WordPress community, could you PR the step that you performed in de installation section of our docs?

We developers do it from time to time but I think installing from WP.org is the most preferred method.

Is there a WP section of the docs? I will try to contribute where I can.

Happy to contribute to the plugin as well.

[Query Monitor](https://github.com/johnbillion/query-monitor) can be a good starting point to borrow some logic. It's like Laravel Debugbar but for WordPress.

**Comment by freekmurze** [comment]
I've fixed that `null` caller method name in development.

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/483853/104217874-393cf800-543c-11eb-9f7b-11c0767f2e4f.png">


This will be part of Ray 1.2.1 which will be released later tonight.
